### ISSUE TITLE
python2 problems??

### ISSUE THREAD

**Issue by TermeHansen** [psi4/psi4#1000]
With the coming 1.2 release, I decided to test master instead of tags/v1.1 that I use as stable. all ctests fail with what I believe is python2 related.
```

315/399 Test: sapt1
Command: "/usr/bin/python2.7" "/media/BIGdisk/psi4/tests/runtest.py" "/media/BIGdisk/psi4/tests/sapt1/input.dat" "/home/termo/psibuild/testresults.log$
Directory: /home/termo/psibuild/tests/sapt1
"sapt1" start time: May 02 20:52 UTC
Output:
----------------------------------------------------------
Traceback (most recent call last):
  File "/home/termo/psibuild/stage/mnt/batch/tasks/shared/BIGdisk/psi4-12/bin/psi4", line 160, in <module>
    import psi4
  File "/home/termo/psibuild/stage/mnt/batch/tasks/shared/BIGdisk/psi4-12/lib//psi4/__init__.py", line 81, in <module>
    from .driver import endorsed_plugins
  File "/home/termo/psibuild/stage/mnt/batch/tasks/shared/BIGdisk/psi4-12/lib//psi4/driver/endorsed_plugins.py", line 44, in <module>
    if 'scipy' in e.msg:
AttributeError: 'exceptions.ImportError' object has no attribute 'msg'
Exit Status: infile ( 1 ); autotest ( None ); sowreap ( None ); overall ( 1 )
<end of output>

```

I use the same setup for cmake as for tags/v1.1, which pass fine ctest. Something I have overseen to pass to cmake in master?

**Comment by loriab** [comment]
Yup, I both introduced that and fixed it yesterday. It's in an incoming PR. Apply https://github.com/psi4/psi4/pull/998/commits/b8f18eceaa8b09af4b0d3527de5d47421fc14704#diff-3f00268a62165b84f5c659c8bb86ec7a or just comment out the snsmp2 part of that file (unless you're trying to use snsmp2)
