### ISSUE TITLE
New SCF types unrecognized by several downstream modules

### ISSUE THREAD

**Issue by dsirianni** [psi4/psi4#1021]
Several downstream codes do not recognize the new SCF types `mem_DF` and `disk_DF` (introduced in #961) when set directly within the input file.  I've attached [a tarball](https://github.com/psi4/psi4/files/2002517/eff-scftype-df.tar.gz) containing several such tests, adapted directly from the existing Psi4 test suite, which attempt to highlight these problems.  I've also attached the summary file (from the tarball) separately for easy web viewing [here](https://github.com/psi4/psi4/files/2002535/summary.txt).

Additionally worth note is that a few of these downstream codes fail gracefully (e.g., FNOCC for `scf_type mem_df`, as it assumes a disk algorithm) with helpful error messages, but others do not (e.g., CISD energies fail with PSIO errors and DLDF+D09 gradients segfault).  However, if failure is unavoidable, we should probably at least be verbose in the error message.

**Comment by loriab** [comment]
Posting Dom's very nice summary for easier perusal and searchability.

Effective `scf_type df` Testing: `mem_df` & `disk_df`
=====================================================

All tests listed below examine calls to both `energy()` and `gradient()` when
employing the `scf_type mem_df` and `scf_type disk_df` settings.  Each test
employs a different model chemistry (indicated in the test description) and the
Physicists' water molecule, unless otherwise indicated.

1. Physicists' water, HF/6-31G
    - **TEST FAILED**
    - Error message:
        ```
        Traceback (most recent call last):
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/bin/psi4", line 264, in <module>
            exec(content)
          File "<string>", line 30, in <module>
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/driver.py", line 444, in energy
            return driver_cbs._cbs_gufunc(energy, name, ptype='energy', **kwargs)
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/driver_cbs.py", line 1818, in _cbs_gufunc
            ptype_value, wfn = func(method_name, return_wfn=True, molecule=molecule, **kwargs)
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/driver.py", line 492, in energy
            wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/procrouting/proc.py", line 2038, in run_scf
            scf_wfn = scf_helper(name, post_scf=False, **kwargs)
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/procrouting/proc.py", line 1363, in scf_helper
            e_scf = scf_wfn.compute_energy()
        
        RuntimeError:
        Fatal Error: DFHelper (MemDFJK): cannot do cartesian auxiliary functions
        Error occurred in file: /Users/dasirianni/Gits/psi4/psi4/src/psi4/libfock/MemDFJK.cc on line: 89
        The most recent 5 function calls were:
        ```
2. HF/cc-pVDZ: Passed
3. AO DF-CASSCF/cc-pVDZ: Passed
4. DFT Smoketests
    - B2PLYP/cc-pVDZ: Passed
    - CAM-B3LYP/cc-pVDZ: **FAILED**
        ```
        Traceback (most recent call last):
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/bin/psi4", line 264, in <module>
            exec(content)
          File "<string>", line 31, in <module>
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/driver.py", line 444, in energy
            return driver_cbs._cbs_gufunc(energy, name, ptype='energy', **kwargs)
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/driver_cbs.py", line 1818, in _cbs_gufunc
            ptype_value, wfn = func(method_name, return_wfn=True, molecule=molecule, **kwargs)
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/driver.py", line 492, in energy
            wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/procrouting/proc.py", line 2038, in run_scf
            scf_wfn = scf_helper(name, post_scf=False, **kwargs)
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/procrouting/proc.py", line 1283, in scf_helper
            scf_wfn = scf_wavefunction_factory(name, base_wfn, core.get_option('SCF', 'REFERENCE'))
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/procrouting/proc.py", line 1000, in scf_wavefunction_factory
            superfunc, disp_type = dft_funcs.build_superfunctional(name, (reference in ["RKS", "RHF"]))
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/procrouting/dft_funcs/superfuncs.py", line 130, in build_superfunctional
            "SCF: SCF_TYPE (%s) not supported for range-separated functionals." % core.get_option("SCF", "SCF_TYPE"))
        
        ValidationError: SCF: SCF_TYPE (MEM_DF) not supported for range-separated functionals.
        ```
    - DLDF+D09/cc-pVDZ: **GRADIENTS FAILED**
        ```
        Segmentation fault: 11
        ```
        - Both `disk_DF` and `mem_DF` gradients yield above segfault, no message in outfile or message printed to stdout
    - PBE/cc-pVDZ: Passed
    - wPBE/cc-pVDZ: **FAILED**
        ```
        Traceback (most recent call last):
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/bin/psi4", line 264, in <module>
            exec(content)
          File "<string>", line 31, in <module>
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/driver.py", line 444, in energy
            return driver_cbs._cbs_gufunc(energy, name, ptype='energy', **kwargs)
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/driver_cbs.py", line 1818, in _cbs_gufunc
            ptype_value, wfn = func(method_name, return_wfn=True, molecule=molecule, **kwargs)
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/driver.py", line 492, in energy
            wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/procrouting/proc.py", line 2038, in run_scf
            scf_wfn = scf_helper(name, post_scf=False, **kwargs)
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/procrouting/proc.py", line 1283, in scf_helper
            scf_wfn = scf_wavefunction_factory(name, base_wfn, core.get_option('SCF', 'REFERENCE'))
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/procrouting/proc.py", line 1000, in scf_wavefunction_factory
            superfunc, disp_type = dft_funcs.build_superfunctional(name, (reference in ["RKS", "RHF"]))
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/procrouting/dft_funcs/superfuncs.py", line 130, in build_superfunctional
            "SCF: SCF_TYPE (%s) not supported for range-separated functionals." % core.get_option("SCF", "SCF_TYPE"))
        
        ValidationError: SCF: SCF_TYPE (MEM_DF) not supported for range-separated functionals.
        ```
5. SAPT0/cc-pVDZ (energies only; water dimer): Passed!
6. FNOCC
    - QCISD(T)/cc-pVDZ: **ENERGY FAILED**
        ```
        PSIO_ERROR: Can't find TOC Entry IWL Buffers
        PSIO_ERROR: unit = 33, errval = 13
        PSIO_ERROR: 13 (no such TOC entry)
        Traceback (most recent call last):
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/bin/psi4", line 264, in <module>
            exec(content)
          File "<string>", line 31, in <module>
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/driver.py", line 492, in energy
            wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/procrouting/proc.py", line 4052, in run_fnocc
            fnocc_wfn = core.fnocc(ref_wfn)
        
        RuntimeError:
        Fatal Error: PSIO Error
        Error occurred in file: /Users/dasirianni/Gits/psi4/psi4/src/psi4/libpsio/error.cc on line: 129
        The most recent 5 function calls were:
        ```
    - FNO-DF-CCSD(T)/cc-pVDZ: **memDF FAILED** (diskDF passed all)
        ```
        Traceback (most recent call last):
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/bin/psi4", line 264, in <module>
            exec(content)
          File "<string>", line 43, in <module>
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/driver.py", line 492, in energy
            wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/procrouting/proc.py", line 858, in select_ccsd_t_
            return func(name, **kwargs)
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/procrouting/proc.py", line 3907, in run_fnodfcc
            set_cholesky_from('CC_TYPE')
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/procrouting/proc.py", line 3897, in set_cholesky_from
            raise ValidationError("  FNOCC requires SCF_TYPE = DISK_DF")
        
        ValidationError:   FNOCC requires SCF_TYPE = DISK_DF
        ```
7. DFOCC (OMP2/cc-pVDZ): **memDF FAILED** (diskDF passed all)
    ```
    Traceback (most recent call last):
      File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/bin/psi4", line 264, in <module>
        exec(content)
      File "<string>", line 40, in <module>
      File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/driver.py", line 492, in energy
        wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
      File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/procrouting/proc.py", line 227, in select_omp2
        return func(name, **kwargs)
      File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/procrouting/proc.py", line 1558, in run_dfocc
        type_val = set_cholesky_from('MP2_TYPE')
      File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/procrouting/proc.py", line 1540, in set_cholesky_from
        raise ValidationError("  DFOCC requires SCF_TYPE = DISK_DF")
    
    ValidationError:   DFOCC requires SCF_TYPE = DISK_DF
    ```
8. CI
    - CISD/cc-pVDZ: **ALL FAILED**
        ```
        PSIO_ERROR: Can't find TOC Entry IWL Buffers
        PSIO_ERROR: unit = 33, errval = 13
        PSIO_ERROR: 13 (no such TOC entry)
        Traceback (most recent call last):
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/bin/psi4", line 264, in <module>
            exec(content)
          File "<string>", line 28, in <module>
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/driver.py", line 492, in energy
            wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/procrouting/proc.py", line 952, in select_cisd
            return func(name, **kwargs)
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/procrouting/proc.py", line 4156, in run_cepa
            fnocc_wfn = core.fnocc(ref_wfn)
        
        RuntimeError:
        Fatal Error: PSIO Error
        Error occurred in file: /Users/dasirianni/Gits/psi4/psi4/src/psi4/libpsio/error.cc on line: 129
        The most recent 5 function calls were:
        ```
    - MP3/cc-pVDZ & MP4/cc-pVDZ: **FAILED**
        ```
        PSIO_ERROR: Can't find TOC Entry IWL Buffers
        PSIO_ERROR: unit = 33, errval = 13
        PSIO_ERROR: 13 (no such TOC entry)
        Traceback (most recent call last):
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/bin/psi4", line 264, in <module>
            exec(content)
          File "<string>", line 28, in <module>
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/driver.py", line 492, in energy
            wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/procrouting/proc.py", line 333, in select_mp3
            return func(name, **kwargs)
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/procrouting/proc.py", line 1941, in run_occ
            occ_wfn = core.occ(ref_wfn)
        
        RuntimeError:
        Fatal Error: PSIO Error
        Error occurred in file: /Users/dasirianni/Gits/psi4/psi4/src/psi4/libpsio/error.cc on line: 129
        The most recent 5 function calls were:
        ```
    - CISD/cc-pVDZ via DETCI: **FAILED**
        ```
        PSIO_ERROR: Can't find TOC Entry IWL Buffers
        PSIO_ERROR: unit = 33, errval = 13
        PSIO_ERROR: 13 (no such TOC entry)
        Traceback (most recent call last):
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/bin/psi4", line 264, in <module>
            exec(content)
          File "<string>", line 29, in <module>
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/driver.py", line 492, in energy
            wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/procrouting/proc.py", line 952, in select_cisd
            return func(name, **kwargs)
          File "/Users/dasirianni/Gits/psi4/objdir/stage/Users/dasirianni/install/psi4/lib/psi4/driver/procrouting/proc.py", line 3062, in run_detci
            ciwfn = core.detci(ref_wfn)
        
        RuntimeError:
        Fatal Error: PSIO Error
        Error occurred in file: /Users/dasirianni/Gits/psi4/psi4/src/psi4/libpsio/error.cc on line: 129
        The most recent 5 function calls were:
        ```

**Comment by CDSherrill** [comment]
I suspect that in several of these, the problem is that the downstream
codes need the (conventional or DF) integrals written to disk.  This got
handled by some logic where necessary for scf_type = disk_df, apparently,
but did not get handled for mem_df.

Works ok for ccenergy?  It also needs conventional integrals written to
disk.  Maybe that is getting intercepted correctly.

**Comment by amjames** [comment]
@CDSherrill the integrals on disk issue is taken care of at the driver level. Looks like there is a simple helper that is called [here](https://github.com/psi4/psi4/blob/master/psi4/driver/procrouting/proc.py#L2335)
