### ISSUE TITLE
Density Fitting Incompatible with Frequencies

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#1093]
Any computation that attempts to compute frequencies of a density fitted method will crash unless the symmetry is explicitly set to c1. Gradients do not have this problem. The below input file demonstrates the problem and has been taken from the test cases. The only modifications are changing gradients to frequencies and CCSD(T) to MP2. The bug is there with both methods, and also CCSD. I haven't checked other DF methods.

```
#! DF-MP2 cc-pVDZ energy for the H2O molecule.


molecule h2o {
0 1
o
h 1 0.958
h 1 0.958 2 104.4776 
}

set {
  basis cc-pvdz
  df_basis_scf cc-pvdz-jkfit
  df_basis_cc cc-pvdz-ri
  scf_type df
  guess sad 
  freeze_core true
  cc_type df
  qc_module occ 
}

frequencies('mp2', dertype=0)
```
The crash gives the following error message:
```
Traceback (most recent call last):
  File "/Users/jonathonmisiewicz/psi4/objdir2/stage/usr/local/psi4/bin/psi4", line 264, in <module>
    exec(content)
  File "<string>", line 36, in <module>
  File "/Users/jonathonmisiewicz/psi4/objdir2/stage/usr/local/psi4/lib/psi4/driver/driver.py", line 1774, in frequency
    H, wfn = hessian(lowername, return_wfn=True, molecule=molecule, **kwargs)
  File "/Users/jonathonmisiewicz/psi4/objdir2/stage/usr/local/psi4/lib/psi4/driver/driver.py", line 1595, in hessian
    E, wfn = energy(lowername, return_wfn=True, molecule=moleculeclone, **kwargs)
  File "/Users/jonathonmisiewicz/psi4/objdir2/stage/usr/local/psi4/lib/psi4/driver/driver.py", line 492, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/Users/jonathonmisiewicz/psi4/objdir2/stage/usr/local/psi4/lib/psi4/driver/procrouting/proc.py", line 858, in select_ccsd_t_
    return func(name, **kwargs)
  File "/Users/jonathonmisiewicz/psi4/objdir2/stage/usr/local/psi4/lib/psi4/driver/procrouting/proc.py", line 1608, in run_dfocc
    "RIFIT", core.get_global_option("BASIS"))
  File "/Users/jonathonmisiewicz/psi4/objdir2/stage/usr/local/psi4/lib/psi4/driver/p4util/python_helpers.py", line 99, in pybuild_basis
    psibasis = core.BasisSet.construct_from_pydict(mol, basisdict, puream)

RuntimeError: 
Fatal Error: CoordEntry::basisset: Basisset not set for O and type of DF_BASIS_CC
Error occurred in file: /Users/jonathonmisiewicz/psi4/psi4/src/psi4/libmints/coordentry.cc on line: 134
```
My own investigations have partially uncovered the cause of this. During basis set construction, [basis set labels are set on all atoms](https://github.com/psi4/psi4/blob/master/psi4/src/export_mints.cc#L101). This occurs by [iterating over all atoms in full_atoms_](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/libmints/molecule.cc#L2879) and [setting basis set labels for them.](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/libmints/molecule.cc#L2880) However, there is a very subtle problem. The basis set is constructed from this labels [here](https://github.com/psi4/psi4/blob/master/psi4/src/export_mints.cc#L173). The [constructor](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/libmints/basisset.cc#L567) sets the basis by [calling atom_entry](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/libmints/basisset.cc#L651). The problem is that atom_entry is [tied not to full_atoms_ but to atoms_](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/libmints/molecule.cc#L2912). Setting the basis set labels for full_atoms_ atoms never set them for the atoms_ atoms, hence the error. I've confirmed directly this code sets the basis set label for the first atom of atoms_ in the non-bugged case of a gradient computation, but not in the case of a bugged frequency computation. In both cases, the first atom of full_atoms_ has its basis set labels properly submitted.

My hunch is that these two arrays are supposed to be synced up, modulo ghosts and dummies, so there was probably a problem with pointers somewhere that caused the objects in the two arrays to not be the same. Core devs, am I understanding atoms_ and full_atoms_ correctly?

**Comment by JonathonMisiewicz** [comment]
Fixed by #1108.
