### ISSUE TITLE
Simplify Input-File Side Error Info

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#1196]
Inspired by a recent [forum post](http://forum.psicode.org/t/psi4-run-time-error-module-exec-content/1064/2). If there's an error in the user's input file, the traceback could be much clearer. In particular:

-
```
Traceback (most recent call last):
  File "/opt/vulcan/opt/vulcan/linux-x86_64/intel-16.0.1/psi4-master-avducsgnonqrcpftiesq432gagal6y7r/bin/psi4", line 269, in <module>
    exec(content)
  File "<string>", line 30, in <module>
```
is not a good indicator that the problem is input file side.
- When the problem is input file side, we give the user the line number of the post-processed input file. To see the post-processed input file the line number corresponds to, the user needs to supply the -v flag.
- The line numbering doesn't match up, according to my demo. See the forum topic for details, but Psi told me I had a line 30 error when there was no line 30. (The error was instead by line 29.)

This is a "put this up so I don't forget about it" issue, not a thorough detailing of what should be done. As I recall, this was brought up at WWDC last November, but an issue was never posted.

**Comment by loriab** [comment]
need to get the executed line number out of https://github.com/psi4/psi4/blob/master/psi4/run_psi4.py#L270 then show +/–5 lines or so of `content`, which is `python` (<-- `Psithon`). hopefully that'll be enough of a clue for the user to find the corresponding lines in psithon input. python<-->psithon isn't a 1:1 mapping line-wise.
