### ISSUE TITLE
DCT: QC Algorithm and DF Lead to Crash

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#1353]
Attempts to use both density fitting and the quadratically convergent algorithm in DCT crash Psi. In particular, the following input file

```
molecule adduct {
O
H 1 1 
H 1 1 2 104.5
}

set {
    basis sto-3g
    reference uhf 
    dcft_type df
}

set dcft {
    algorithm qc
}

energy('dcft')
```

raises the following error

```
Traceback (most recent call last):
  File "/opt/vulcan/opt/vulcan/linux-x86_64/intel-16.0.1/psi4-master-avducsgnonqrcpftiesq432gagal6y7r/bin/psi4", line 272, in <module>
    exec(content)
  File "<string>", line 28, in <module>
  File "/opt/vulcan/opt/vulcan/linux-x86_64/intel-16.0.1/psi4-master-avducsgnonqrcpftiesq432gagal6y7r/lib/psi4/driver/driver.py", line 492, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/opt/vulcan/opt/vulcan/linux-x86_64/intel-16.0.1/psi4-master-avducsgnonqrcpftiesq432gagal6y7r/lib/psi4/driver/procrouting/proc.py", line 1489, in run_dcft
    dcft_wfn = core.dcft(ref_wfn)

RuntimeError: 
Fatal Error: PSIO Error
Error occurred in file: /home/vulcan/vadmin/programs/psi4/psi4/src/psi4/libpsio/error.cc on line: 128 
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)
psi::PSIO::read(unsigned long, char const*, char*, unsigned long, psi::psio_address, psi::psio_address*)
psi::IWL::fetch()
```

Public Enemy No. 2, we meet again...

My hunch is that this was never implemented, and an error just needs to be raised until it is implemented. However, it may actually be implemented, but just suffering from a bug. I'll be leaving this error message here until I can figure out which - that will take a while.

**Comment by ssh2** [comment]
I don't think we have ever implemented this. The QC code has always been experimental and I guess we just forgot to raise an exception in this case.
