### ISSUE TITLE
cdomp2-2 test suite failure with ATLAS

### ISSUE THREAD

**Issue by mbanck** [psi4/psi4#1461]
The only remaining test suite failure now is:

```
 22/140 Test  #84: cdomp2-2 .........................***Failed    1.17 sec
	Nuclear Repulsion Energy (a.u.)...................................PASSED
	CD-HF Energy (a.u.)...............................................PASSED
	CD-OMP2 Total Energy (a.u.): computed value (-129.5440268) does not match (-129.5897884) to 6 digits.
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/builddir/stage/usr/bin/psi4", line 269, in <module>
    exec(content)
  File "<string>", line 39, in <module>
  File "/<<PKGBUILDDIR>>/builddir/stage/usr/lib/x86_64-linux-gnu/psi4/driver/p4util/util.py", line 227, in compare_values
    raise TestComparisonError(message)

TestComparisonError: 	CD-OMP2 Total Energy (a.u.): computed value (-129.5440268) does not match (-129.5897884) to 6 digits.
Exit Status: infile ( 1 ); autotest ( None ); sowreap ( None ); overall ( 1 )
```

_Originally posted by @mbanck in https://github.com/psi4/psi4/issues/1457#issuecomment-451647367_

**Comment by mbanck** [comment]
Actually, I think it might make sense to keep this issue open (and retitled to "cdomp2-2 test suite failure when ATLAS is used" or so); this is something that should be tracked down eventually.

**Comment by mbanck** [comment]
Also interesting that the testcase passes on ia32 (i.e. 32bit Intel) machines, even with ATLAS: https://buildd.debian.org/status/fetch.php?pkg=psi4&arch=i386&ver=1%3A1.2.1-2&stamp=1546705469&raw=0

**Comment by dgasmith** [comment]
This seems more like an ATLAS issue than a Psi4 issue. What can we do here to help out ATLAS, we could consider preconditioning our eigensolve calls perhaps?

**Comment by susilehtola** [comment]
Lemme guess: Psi4 is using ATLAS inside OpenMP regions, but ATLAS is not compiled thread-safe?

**Comment by dgasmith** [comment]
That’s part it, which we can fix. The larger issue is their eigensolver being somewhat unreliable in our experience.

**Comment by loriab** [comment]
Without looking at ATLAS but extrapolating from OpenBLAS, unless the LAPACK is built with cmake components (or something similar), we can't even tell at psi-build+lapack-detection -time if the LAPACK has any chance of working. In OpenBLAS, of their 3 build modes (single, pthread, omp), the most commonly found, pthread, has no chance of working with psi, but one can't tell that from the blas installation.

**Comment by mbanck** [comment]
Couldn't you have a configure-time check for this (in case it can be broken down to a very small testcase), same as is usual in autoconf-world?

**Comment by susilehtola** [comment]
Should be doable: in ERKALE I run an eigendecomposition of a 100x100 random matrix in sequential mode and repeat the calculation in a parallel OpenMP section. If the decompositions of the individual threads don’t match the sequential one, then LAPACK is not thread safe.

Susi Lehtola
Sent from my phone so excuse my brevity.


On 20 Jan 2019, at 15.03, Michael Banck <notifications@github.com<mailto:notifications@github.com>> wrote:


Couldn't you have a configure-time check for this (in case it can be broken down to a very small testcase), same as is usual in autoconf-world?

**Comment by JonathonMisiewicz** [comment]
Marking `action-items-needed`. It isn't clear to me if there's anything for Psi to do about this one.
