### ISSUE TITLE
DCT gradients fail with ROHF starting orbitals

### ISSUE THREAD

**Issue by mdav2** [psi4/psi4#1482]
DCT gradients fail with the traceback below when ROHF starting orbitals are used. The same result is obtained for all DCT functionals w/ analytic gradients (ODC-13, ODC-12, ODC-06, DC-06). The calculation runs fine with UHF starting orbitals. Furthermore identical energies are obtained for the UHF calculation and the ROHF calculation, but the ROHF calculation fails out before computing the gradient. 

```    Molecular point group: c2v
    Full point group: C2v

    Geometry (in Bohr), charge = 0, multiplicity = 1:

       Center              X                  Y                   Z
    ------------   -----------------  -----------------  -----------------
         O            0.000000000000     0.000000000000    -0.124297814551
         H            0.000000000000    -1.434419280484     0.986348258811
         H            0.000000000000     1.434419280484     0.986348258811


Traceback (most recent call last):
  File "/home/mmd01986/anaconda3/envs/psi4/bin/psi4", line 269, in <module>
    exec(content)
  File "<string>", line 31, in <module>
  File "/home/mmd01986/anaconda3/envs/psi4/lib//python3.6/site-packages/psi4/driver/driver.py", line 638, in gradient
    wfn = procedures['gradient'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/mmd01986/anaconda3/envs/psi4/lib//python3.6/site-packages/psi4/driver/procrouting/proc.py", line 1501, in run_dcft_gradient
    grad = derivobj.compute()

RuntimeError:
Fatal Error: PSIO Error
Error occurred in file: /scratch/psilocaluser/conda-builds/psi4-multiout_1532493090788/work/psi4/src/psi4/libpsio/error.cc on line: 129
The most recent 5 function calls were:

psi::PSIO::read(unsigned long, char const*, char*, unsigned long, psi::psio_address, psi::psio_address*)
psi::PSIO::read_entry(unsigned long, char const*, char*, unsigned long)


    Psi4 stopped on: Friday, 18 January 2019 09:58AM
    Psi4 wall time for execution: 0:00:01.14

*** Psi4 encountered an error. Buy a developer more coffee!
*** Resources and help at github.com/psi4/psi4.
```

**Comment by JonathonMisiewicz** [comment]
I remarked at PsiCon that PSIO errors were public enemy no. 2, and I view this as further evidence.

I'll investigate.
