### ISSUE TITLE
Relativistic calculations referring to non-standard basis fails

### ISSUE THREAD

**Issue by tovrstra** [psi4/psi4#1613]
This problem was already mentioned in passing here: https://github.com/psi4/psi4/issues/662#issuecomment-475861476

This is a simple example input file showing the problem:

```
molecule {
  H
}

set {
    scf_type pk
    basis ano-rcc
    relativistic x2c
    reference uhf
}

energy('hf')
```

I have set my `$PSIPATH` to a directory containing the basis set file (downloaded from EMSL):

```bash
ll $PSIPATH
total 2.1M
drwxr-xr-x. 2 toon toon 4.0K Apr 29 17:13 .
drwxr-xr-x. 7 toon toon 4.0K Apr 29 16:34 ..
-rw-r--r--. 1 toon toon 2.1M Apr 29 15:49 ano-rcc.gbs
```

When running Psi4 on this input, I get the following error message:

```
Traceback (most recent call last):
  File "/home/toon/miniconda3/envs/p4dev/bin/psi4", line 287, in <module>
    exec(content)
  File "<string>", line 26, in <module>
  File "/home/toon/miniconda3/envs/p4dev/lib/psi4/driver/driver.py", line 561, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/toon/miniconda3/envs/p4dev/lib/psi4/driver/procrouting/proc.py", line 2045, in run_scf
    scf_wfn = scf_helper(name, post_scf=False, **kwargs)
  File "/home/toon/miniconda3/envs/p4dev/lib/psi4/driver/procrouting/proc.py", line 1281, in scf_helper
    scf_wfn = scf_wavefunction_factory(name, base_wfn, core.get_option('SCF', 'REFERENCE'), **kwargs)
  File "/home/toon/miniconda3/envs/p4dev/lib/psi4/driver/procrouting/proc.py", line 1056, in scf_wavefunction_factory
    puream=wfn.basisset().has_puream())
  File "/home/toon/miniconda3/envs/p4dev/lib/psi4/driver/p4util/python_helpers.py", line 80, in _pybuild_basis
    mol.to_dict(), key, resolved_target, fitrole, other, return_dict=True, return_atomlist=return_atomlist)
  File "/home/toon/miniconda3/envs/p4dev/lib/psi4/driver/qcdb/libmintsbasisset.py", line 679, in pyconstruct
    verbose=verbose)
  File "/home/toon/miniconda3/envs/p4dev/lib/psi4/driver/qcdb/libmintsbasisset.py", line 838, in construct
    filename = cls.make_filename(basgbs)
  File "/home/toon/miniconda3/envs/p4dev/lib/psi4/driver/qcdb/libmintsbasisset.py", line 1396, in make_filename
    basisname = basisname.lower()

AttributeError: 'NoneType' object has no attribute 'lower'

Printing out the relevant lines from the Psithon --> Python processed input file:
    core.IO.set_default_namespace("")
    core.set_global_option("SCF_TYPE", "pk")
    core.set_global_option("BASIS", "ano-rcc")
    core.set_global_option("RELATIVISTIC", "x2c")
    core.set_global_option("REFERENCE", "uhf")
--> energy('hf')
```

This problem was previously also brought up on the forum: http://forum.psicode.org/t/scf-problems-please-help/765/1

**Comment by tovrstra** [comment]
P.S. The following two similar inputs do work, but correspond to different calculations, I assume:

```
molecule {
  H
}

set {
    scf_type pk
    basis ano-rcc
    basis_relativistic ano-rcc
    relativistic x2c
    reference uhf
}

energy('hf')
```

and 

```
molecule {
  H
}

set {
    scf_type pk
    basis ano-rcc
    reference uhf
}

energy('hf')
```

**Comment by loriab** [comment]
Did you put the sph/cart flag at the top of the basis file? MolSSI's new library does it automatically if you select "psi4" format, but it has to be by hand for the old one. It at least runs for me -- output is below for a sanity check.

```
>>> head stage/share/psi4/basis/ano-rcc.gbs
cartesian

!----------------------------------------------------------------------
! Basis Set Exchange
! Version v0.7.0
! https://www.basissetexchange.org
!----------------------------------------------------------------------
!   Basis set: ANO-RCC
! Description: Full ANO-RCC basis
!        Role: orbital
```

```>>> cat toon.out 

    -----------------------------------------------------------------------
          Psi4: An Open-Source Ab Initio Electronic Structure Package
                               Psi4 1.4a1.dev99 

                         Git: Rev {cphfconv} bddb364 dirty


    R. M. Parrish, L. A. Burns, D. G. A. Smith, A. C. Simmonett,
    A. E. DePrince III, E. G. Hohenstein, U. Bozkaya, A. Yu. Sokolov,
    R. Di Remigio, R. M. Richard, J. F. Gonthier, A. M. James,
    H. R. McAlexander, A. Kumar, M. Saitow, X. Wang, B. P. Pritchard,
    P. Verma, H. F. Schaefer III, K. Patkowski, R. A. King, E. F. Valeev,
    F. A. Evangelista, J. M. Turney, T. D. Crawford, and C. D. Sherrill,
    J. Chem. Theory Comput. 13(7) pp 3185--3197 (2017).
    (doi: 10.1021/acs.jctc.7b00174)


                         Additional Contributions by
    P. Kraus, H. Kruse, M. H. Lechner, M. C. Schieber, R. A. Shaw,
    A. Alenaizan, R. Galvelis, Z. L. Glick, S. Lehtola, and J. P. Misiewicz

    -----------------------------------------------------------------------


    Psi4 started on: Monday, 29 April 2019 11:26AM

    Process ID: 25534
    Host:       psinet
    PSIDATADIR: /home/psilocaluser/gits/hrw-quaternary/objdir37/stage/share/psi4
    Memory:     500.0 MiB
    Threads:    1
    
  ==> Input File <==

--------------------------------------------------------------------------
molecule {
  H
}

set {
    scf_type pk
    basis ano-rcc
    relativistic x2c
    reference uhf
}

energy('hf')


--------------------------------------------------------------------------

*** tstart() called on psinet
*** at Mon Apr 29 11:26:26 2019

   => Loading Basis Set <=

    Name: ANO-RCC
    Role: ORBITAL
    Keyword: BASIS
    atoms 1 entry H          line    17 file /home/psilocaluser/gits/hrw-quaternary/objdir37/stage/share/psi4/basis/ano-rcc.gbs 


         ---------------------------------------------------------
                                   SCF
               by Justin Turney, Rob Parrish, Andy Simmonett
                          and Daniel G. A. Smith
                              UHF Reference
                        1 Threads,    500 MiB Core
         ---------------------------------------------------------

  ==> Geometry <==

    Molecular point group: d2h
    Geometry (in Angstrom), charge = 0, multiplicity = 2:

       Center              X                  Y                   Z               Mass       
    ------------   -----------------  -----------------  -----------------  -----------------
         H            0.000000000000     0.000000000000     0.000000000000     1.007825032230

  Running in d2h symmetry.

  Rotational constants: A = ************  B = ************  C = ************ [cm^-1]
  Rotational constants: A = ************  B = ************  C = ************ [MHz]
  Nuclear repulsion =    0.000000000000000

  Charge       = 0
  Multiplicity = 2
  Electrons    = 1
  Nalpha       = 1
  Nbeta        = 0

  ==> Algorithm <==

  SCF Algorithm Type is PK.
  DIIS enabled.
  MOM disabled.
  Fractional occupation disabled.
  Guess Type is CORE.
  Energy threshold   = 1.00e-06
  Density threshold  = 1.00e-06
  Integral threshold = 0.00e+00

  ==> Primary Basis <==

  Basis Set: ANO-RCC
    Blend: ANO-RCC
    Number of shells: 14
    Number of basis function: 46
    Number of Cartesian functions: 46
    Spherical Harmonics?: false
    Max angular momentum: 3

   => Loading Basis Set <=

    Name: (ANO-RCC AUX)
    Role: DECON
    Keyword: BASIS_RELATIVISTIC
    atoms 1 entry H          line    17 file /home/psilocaluser/gits/hrw-quaternary/objdir37/stage/share/psi4/basis/ano-rcc.gbs func decontract

  ==> Pre-Iterations <==

   -------------------------------------------------------
    Irrep   Nso     Nmo     Nalpha   Nbeta   Ndocc  Nsocc
   -------------------------------------------------------
     Ag        15      15       0       0       0       0
     B1g        3       3       0       0       0       0
     B2g        3       3       0       0       0       0
     B3g        3       3       0       0       0       0
     Au         1       1       0       0       0       0
     B1u        7       7       0       0       0       0
     B2u        7       7       0       0       0       0
     B3u        7       7       0       0       0       0
   -------------------------------------------------------
    Total      46      46       1       0       0       1
   -------------------------------------------------------

  ==> Integral Setup <==

 OEINTS: Using relativistic (X2C) overlap, kinetic, and potential integrals.
         ------------------------------------------------------------
         Spin-Free X2C Integrals at the One-Electron Level (SFX2C-1e)
                 by Prakash Verma and Francesco A. Evangelista
         ------------------------------------------------------------

  ==> X2C Options <==

    Computational Basis: ANO-RCC
    X2C Basis: (ANO-RCC AUX)
    The X2C Hamiltonian will be computed in the X2C Basis

    Comparing only 15 out of 17 elements of H_Dirac

    The 1-norm of |H_X2C - H_Dirac| is: 9.762433630521

    WARNING: The X2C and Dirac Hamiltonians have substatially different eigenvalues!
             This is probably caused by the recontraction of the basis set.

  Using in-core PK algorithm.
   Calculation information:
      Number of atoms:                   1
      Number of AO shells:              14
      Number of primitives:             74
      Number of atomic orbitals:        46
      Number of basis functions:        46

      Integral cutoff                 1.00e-12
      Number of threads:                 1

  Performing in-core PK
  Using 1169642 doubles for integral storage.
  We computed 5565 shell quartets total.
  Whereas there are 5565 unique shell quartets.

  ==> DiskJK: Disk-Based J/K Matrices <==

    J tasked:                  Yes
    K tasked:                  Yes
    wK tasked:                  No
    Memory [MiB]:              375
    Schwarz Cutoff:          1E-12

    OpenMP threads:              1

  Minimum eigenvalue in the overlap matrix is 1.6573405367E-05.
  Using Symmetric Orthogonalization.

  SCF Guess: Core (One-Electron) Hamiltonian.

  ==> Iterations <==

                        Total Energy        Delta E     RMS |[F,P]|

   @UHF iter   1:    -0.49999200764265   -4.99992e-01   2.73366e-14 DIIS
   @UHF iter   2:    -0.49999200764259    5.80092e-14   1.96206e-14 DIIS
  Energy and wave function converged.


  ==> Post-Iterations <==

   @Spin Contamination Metric:   0.000000000E+00
   @S^2 Expected:                7.500000000E-01
   @S^2 Observed:                7.500000000E-01
   @S   Expected:                5.000000000E-01
   @S   Observed:                5.000000000E-01

    Orbital Energies [Eh]
    ---------------------

    Alpha Occupied:                                                       

       1Ag    -0.499992  

    Alpha Virtual:                                                        

       2Ag     0.054719     1B1u    0.189699     1B3u    0.189699  
       1B2u    0.189699     3Ag     0.302215     2B3u    0.741625  
       2B2u    0.741625     2B1u    0.741625     4Ag     0.880345  
       1B2g    0.880345     1B3g    0.880345     1B1g    0.880345  
       5Ag     0.880345     6Ag     0.985424     3B2u    2.200372  
       3B3u    2.200372     3B1u    2.200372     7Ag     2.508422  
       8Ag     2.916076     2B1g    2.916076     2B3g    2.916076  
       2B2g    2.916076     9Ag     2.916076     4B3u    4.215041  
       4B1u    4.215041     4B2u    4.215041     5B1u    4.215041  
       1Au     4.215041     5B3u    4.215041     5B2u    4.215041  
      10Ag     5.006734     6B3u    5.367541     6B2u    5.367541  
       6B1u    5.367541    11Ag     8.068526    12Ag     8.272193  
       3B3g    8.272193     3B2g    8.272193     3B1g    8.272193  
      13Ag     8.272193     7B3u   11.798691     7B2u   11.798691  
       7B1u   11.798691    14Ag    14.696251    15Ag    34.149342  

    Beta Occupied:                                                        

    

    Beta Virtual:                                                         

       1Ag     0.016098     2Ag     0.109076     1B2u    0.211108  
       1B1u    0.211108     1B3u    0.211108     3Ag     0.385413  
       2B1u    0.802773     2B2u    0.802773     2B3u    0.802773  
       4Ag     0.900610     1B3g    0.900610     1B2g    0.900610  
       1B1g    0.900610     5Ag     0.900610     6Ag     1.071716  
       3B1u    2.265097     3B3u    2.265097     3B2u    2.265097  
       7Ag     2.575158     8Ag     2.953058     2B2g    2.953058  
       2B3g    2.953058     2B1g    2.953058     9Ag     2.953058  
       4B1u    4.243456     4B3u    4.243456     4B2u    4.243456  
       5B1u    4.243456     1Au     4.243456     5B3u    4.243456  
       5B2u    4.243456    10Ag     5.042050     6B3u    5.416218  
       6B1u    5.416218     6B2u    5.416218    11Ag     8.101653  
      12Ag     8.311198     3B3g    8.311198     3B2g    8.311198  
       3B1g    8.311198    13Ag     8.311198     7B3u   11.838258  
       7B2u   11.838258     7B1u   11.838258    14Ag    14.727369  
      15Ag    34.174361  

    Final Occupation by Irrep:
             Ag   B1g   B2g   B3g    Au   B1u   B2u   B3u 
    DOCC [     0,    0,    0,    0,    0,    0,    0,    0 ]
    SOCC [     1,    0,    0,    0,    0,    0,    0,    0 ]

  @UHF Final Energy:    -0.49999200764259

   => Energetics <=

    Nuclear Repulsion Energy =              0.0000000000000000
    One-Electron Energy =                  -0.4999920076425929
    Two-Electron Energy =                   0.0000000000000002
    Total Energy =                         -0.4999920076425927

  UHF NO Occupations:
  HONO-0 :    1 Ag 1.0000000
  LUNO+0 :    2 Ag 0.0000000
  LUNO+1 :    3 Ag 0.0000000
  LUNO+2 :    4 Ag 0.0000000
  LUNO+3 :    5 Ag 0.0000000


Computation Completed


Properties will be evaluated at   0.000000,   0.000000,   0.000000 [a0]

Properties computed using the SCF density matrix

  Nuclear Dipole Moment: [e a0]
     X:     0.0000      Y:     0.0000      Z:     0.0000

  Electronic Dipole Moment: [e a0]
     X:     0.0000      Y:     0.0000      Z:     0.0000

  Dipole Moment: [e a0]
     X:     0.0000      Y:     0.0000      Z:     0.0000     Total:     0.0000

  Dipole Moment: [D]
     X:     0.0000      Y:     0.0000      Z:     0.0000     Total:     0.0000


*** tstop() called on psinet at Mon Apr 29 11:26:27 2019
Module time:
	user time   =       0.87 seconds =       0.01 minutes
	system time =       0.02 seconds =       0.00 minutes
	total time  =          1 seconds =       0.02 minutes
Total time:
	user time   =       0.87 seconds =       0.01 minutes
	system time =       0.02 seconds =       0.00 minutes
	total time  =          1 seconds =       0.02 minutes

    Psi4 stopped on: Monday, 29 April 2019 11:26AM
    Psi4 wall time for execution: 0:00:00.91

*** Psi4 exiting successfully. Buy a developer a beer!
```

**Comment by tovrstra** [comment]
@loriab I did. I guess you don't encounter the error because you are not using `$PSIPATH`, see http://www.psicode.org/psi4manual/master/external.html#envvar-PSIPATH. (I'm using this to reproduce the situation of a user who wants to use a custom basis set file on a system-wide PSI4 installation to which he/she does not have write access.) It seems that basis set files in `$PSIPATH` are somehow handled differently. These are my corresponding files:

```
head $PSIPATH/ano-rcc.gbs
cartesian

!----------------------------------------------------------------------
! Basis Set Exchange
! Version v0.7.0
! https://www.basissetexchange.org
!----------------------------------------------------------------------
!   Basis set: ANO-RCC
! Description: Full ANO-RCC basis
!        Role: orbital
```

```

    -----------------------------------------------------------------------
          Psi4: An Open-Source Ab Initio Electronic Structure Package
                               Psi4 1.4a1.dev101 

                         Git: Rev {master} 302cd1d dirty


    R. M. Parrish, L. A. Burns, D. G. A. Smith, A. C. Simmonett,
    A. E. DePrince III, E. G. Hohenstein, U. Bozkaya, A. Yu. Sokolov,
    R. Di Remigio, R. M. Richard, J. F. Gonthier, A. M. James,
    H. R. McAlexander, A. Kumar, M. Saitow, X. Wang, B. P. Pritchard,
    P. Verma, H. F. Schaefer III, K. Patkowski, R. A. King, E. F. Valeev,
    F. A. Evangelista, J. M. Turney, T. D. Crawford, and C. D. Sherrill,
    J. Chem. Theory Comput. 13(7) pp 3185--3197 (2017).
    (doi: 10.1021/acs.jctc.7b00174)


                         Additional Contributions by
    P. Kraus, H. Kruse, M. H. Lechner, M. C. Schieber, R. A. Shaw,
    A. Alenaizan, R. Galvelis, Z. L. Glick, S. Lehtola, and J. P. Misiewicz

    -----------------------------------------------------------------------


    Psi4 started on: Monday, 29 April 2019 07:36PM

    Process ID: 6146
    Host:       molmod00.ugent.be
    PSIDATADIR: /home/toon/miniconda3/envs/p4dev/share/psi4
    Memory:     500.0 MiB
    Threads:    1
    
  ==> Input File <==

--------------------------------------------------------------------------
molecule {
  H
}

set {
    scf_type pk
    basis ano-rcc
    relativistic x2c
    reference uhf
}

energy('hf')
--------------------------------------------------------------------------

*** tstart() called on molmod00.ugent.be
*** at Mon Apr 29 19:36:44 2019

   => Loading Basis Set <=

    Name: ANO-RCC
    Role: ORBITAL
    Keyword: BASIS
    atoms 1 entry H          line    16 file /home/toon/Downloads/jobs/basis/ano-rcc.gbs 


         ---------------------------------------------------------
                                   SCF
               by Justin Turney, Rob Parrish, Andy Simmonett
                          and Daniel G. A. Smith
                              UHF Reference
                        1 Threads,    500 MiB Core
         ---------------------------------------------------------

  ==> Geometry <==

    Molecular point group: d2h
    Geometry (in Angstrom), charge = 0, multiplicity = 2:

       Center              X                  Y                   Z               Mass       
    ------------   -----------------  -----------------  -----------------  -----------------
         H            0.000000000000     0.000000000000     0.000000000000     1.007825032230

  Running in d2h symmetry.

  Rotational constants: A = ************  B = ************  C = ************ [cm^-1]
  Rotational constants: A = ************  B = ************  C = ************ [MHz]
  Nuclear repulsion =    0.000000000000000

  Charge       = 0
  Multiplicity = 2
  Electrons    = 1
  Nalpha       = 1
  Nbeta        = 0

  ==> Algorithm <==

  SCF Algorithm Type is PK.
  DIIS enabled.
  MOM disabled.
  Fractional occupation disabled.
  Guess Type is CORE.
  Energy threshold   = 1.00e-06
  Density threshold  = 1.00e-06
  Integral threshold = 0.00e+00

  ==> Primary Basis <==

  Basis Set: ANO-RCC
    Blend: ANO-RCC
    Number of shells: 14
    Number of basis function: 46
    Number of Cartesian functions: 46
    Spherical Harmonics?: false
    Max angular momentum: 3


Traceback (most recent call last):
  File "/home/toon/miniconda3/envs/p4dev/bin/psi4", line 287, in <module>
    exec(content)
  File "<string>", line 26, in <module>
  File "/home/toon/miniconda3/envs/p4dev/lib/psi4/driver/driver.py", line 561, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/toon/miniconda3/envs/p4dev/lib/psi4/driver/procrouting/proc.py", line 2045, in run_scf
    scf_wfn = scf_helper(name, post_scf=False, **kwargs)
  File "/home/toon/miniconda3/envs/p4dev/lib/psi4/driver/procrouting/proc.py", line 1281, in scf_helper
    scf_wfn = scf_wavefunction_factory(name, base_wfn, core.get_option('SCF', 'REFERENCE'), **kwargs)
  File "/home/toon/miniconda3/envs/p4dev/lib/psi4/driver/procrouting/proc.py", line 1056, in scf_wavefunction_factory
    puream=wfn.basisset().has_puream())
  File "/home/toon/miniconda3/envs/p4dev/lib/psi4/driver/p4util/python_helpers.py", line 80, in _pybuild_basis
    mol.to_dict(), key, resolved_target, fitrole, other, return_dict=True, return_atomlist=return_atomlist)
  File "/home/toon/miniconda3/envs/p4dev/lib/psi4/driver/qcdb/libmintsbasisset.py", line 679, in pyconstruct
    verbose=verbose)
  File "/home/toon/miniconda3/envs/p4dev/lib/psi4/driver/qcdb/libmintsbasisset.py", line 838, in construct
    filename = cls.make_filename(basgbs)
  File "/home/toon/miniconda3/envs/p4dev/lib/psi4/driver/qcdb/libmintsbasisset.py", line 1396, in make_filename
    basisname = basisname.lower()

AttributeError: 'NoneType' object has no attribute 'lower'


Printing out the relevant lines from the Psithon --> Python processed input file:
    core.IO.set_default_namespace("")
    core.set_global_option("SCF_TYPE", "pk")
    core.set_global_option("BASIS", "ano-rcc")
    core.set_global_option("RELATIVISTIC", "x2c")
    core.set_global_option("REFERENCE", "uhf")
--> energy('hf')

    Psi4 stopped on: Monday, 29 April 2019 07:36PM
    Psi4 wall time for execution: 0:00:00.18

*** Psi4 encountered an error. Buy a developer more coffee!
*** Resources and help at github.com/psi4/psi4.
```

**Comment by loriab** [comment]
you're right. it's hitting [this logic](https://github.com/psi4/psi4/blob/master/psi4/driver/qcdb/libmintsbasisset.py#L802) which didn't have aux-basis-sets-derived-from-orbital-basis-sets in mind when it was derived. two solutions:

a) forget envvar `PSIPATH`. instead, put the `ano-rcc.gbs` in the same directory as the input file. `.` is in the search path.
b) edit `libraryPath` to `basisPath` [here](https://github.com/psi4/psi4/blob/master/psi4/driver/qcdb/libmintsbasisset.py#L811) and remake (and possibly re-install) to copy into right place.

Without write access, (a) is probably the way to go. Sorry for the trouble.

**Comment by tovrstra** [comment]
No problem. We're very grateful for your help and all the nice work in general!

Would option (b) be useful as a permanent change to the code? Or is it more like a hack?
