### ISSUE TITLE
DF-MP2.5 failure for large inputs

### ISSUE THREAD

**Issue by dgasmith** [psi4/psi4#1679]
Input:
```
memory 850 Gb

molecule m2 {
0 1
O       1.87689999999999E+01    1.03741400000000E+01    1.10736100000000E+01
H       1.95618799999999E+01    9.95786999999999E+00    1.14117900000000E+01
H       1.88049399999999E+01    1.12689299999999E+01    1.14117900000000E+01
O       1.42767500000000E+01    1.03741400000000E+01    1.10736100000000E+01
H       1.50696300000000E+01    9.95786999999999E+00    1.14117900000000E+01
H       1.43126900000000E+01    1.12689299999999E+01    1.14117900000000E+01
O       1.87689999999999E+01    1.81549400000000E+01    1.10736100000000E+01
H       1.95618799999999E+01    1.77386700000000E+01    1.14117900000000E+01
H       1.88049399999999E+01    1.90497300000000E+01    1.14117900000000E+01
O       1.42767500000000E+01    1.81549400000000E+01    1.10736100000000E+01
H       1.50696300000000E+01    1.77386700000000E+01    1.14117900000000E+01
H       1.43126900000000E+01    1.90497300000000E+01    1.14117900000000E+01
O       2.10151299999999E+01    1.42645400000000E+01    1.10736100000000E+01
H       2.10510600000000E+01    1.51593300000000E+01    1.14117900000000E+01
H       2.18080100000000E+01    1.38482699999999E+01    1.14117900000000E+01
O       1.65228700000000E+01    1.42645400000000E+01    1.10736100000000E+01
H       1.65588100000000E+01    1.51593300000000E+01    1.14117900000000E+01
H       1.73157600000000E+01    1.38482699999999E+01    1.14117900000000E+01
O       1.20306300000000E+01    1.42645400000000E+01    1.10736100000000E+01
H       1.20665600000000E+01    1.51593300000000E+01    1.14117900000000E+01
H       1.28235100000000E+01    1.38482699999999E+01    1.14117900000000E+01
O       1.21095083453578E+01    9.10387260269542E+00    1.20022646359687E+01
H       1.21943358070284E+01    9.15273995464783E+00    1.29734044128096E+01
H       1.29300805996214E+01    9.58461898853126E+00    1.16469344031894E+01
O       1.21095208678102E+01    1.68846547306178E+01    1.20022498221129E+01
H       1.21943617813608E+01    1.69335067657059E+01    1.29733883090420E+01
H       1.29300899615499E+01    1.73654235297822E+01    1.16469127541986E+01
O       2.10924185275090E+01    9.10246547828137E+00    1.20029965898670E+01
H       2.11723528985463E+01    9.15368354935812E+00    1.29747159594611E+01
H       2.19127023812585E+01    9.58419232275556E+00    1.16495779080706E+01
O       1.66000963859389E+01    9.10393878304366E+00    1.20018930264312E+01
H       1.66862678724844E+01    9.15106189269160E+00    1.29733896681495E+01
H       1.74208808173953E+01    9.58447870262053E+00    1.16469328356722E+01
O       2.10924406367978E+01    1.68832684376857E+01    1.20029556700182E+01
H       2.11724374304327E+01    1.69344491039565E+01    1.29747092928667E+01
H       2.19127120650509E+01    1.73649867268274E+01    1.16495241352093E+01
O       1.66001175009873E+01    1.68847213502115E+01    1.20018639379116E+01
H       1.66863065463536E+01    1.69318387695251E+01    1.29733879832984E+01
H       1.74208858618342E+01    1.73652789519844E+01    1.16468995475923E+01
O       1.88431375700750E+01    1.30109988980166E+01    1.19983531520136E+01
H       1.89282402555765E+01    1.30611209267480E+01    1.29697750466024E+01
H       1.96664898627493E+01    1.34868752802308E+01    1.16416190108971E+01
O       1.43526763532959E+01    1.30113970569431E+01    1.19978051198750E+01
H       1.44424504488042E+01    1.30589832954827E+01    1.29686420001814E+01
H       1.51761320099903E+01    1.34867010754835E+01    1.16393171667026E+01
}

set {
  freeze_core true
  scf_type df
  mp_type df
  basis aug-cc-pvtz
  DF_BASIS_MP2  cc-pVQZ-RI
}

energy('mp2.5')
```

Failure:

```
==============================================================================
 ==============================================================================
 ==============================================================================

                    DF-MP2.5
              Program Written by Ugur Bozkaya
              Latest Revision September 9, 2017

 ==============================================================================
 ==============================================================================
 ==============================================================================

        MO spaces...

         FC   OCC   VIR   FV
        ----------------------
         15   60   1305    0

        Number of basis functions in the DF-CC basis: 2970

        Available memory                      : 810623.17 MB
        Memory requirement for 3-index ints   :  40445.15 MB
        Memory requirement for DF-CC int trans:  24244.87 MB
        Memory requirement for CC contractions:  56027.91 MB
        Total memory requirement for DF+CC int:  96473.07 MB
        Memory requirement for Wabef term     :  75373.62 MB

Traceback (most recent call last):
  File "/home/416653/PSI4/bin/psi4", line 287, in <module>
    exec(content)
  File "<string>", line 76, in <module>
  File "/home/416653/PSI4/lib/psi4/driver/driver.py", line 561, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/416653/PSI4/lib/psi4/driver/procrouting/proc.py", line 456, in select_mp2p5
    return func(name, **kwargs)
  File "/home/416653/PSI4/lib/psi4/driver/procrouting/proc.py", line 1607, in run_dfocc
    dfocc_wfn = core.dfocc(ref_wfn)

MemoryError: std::bad_array_new_length


Printing out the relevant lines from the Psithon --> Python processed input file:
    core.set_global_option("FREEZE_CORE", "true")
    core.set_global_option("SCF_TYPE", "df")
    core.set_global_option("MP_TYPE", "df")
    core.set_global_option("BASIS", "aug-cc-pvtz")
    core.set_global_option("DF_BASIS_MP2", "cc-pVQZ-RI")
--> energy('mp2.5')

    Psi4 stopped on: Thursday, 02 May 2019 01:23PM
    Psi4 wall time for execution: 0:18:04.56
```

Looks like the error is somewhere around [here](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/dfocc/manager.cc#L2546). The `std::bad_array_new_length` is usually (but not always) thrown for negative lengths.

@bozkaya any ideas?

**Comment by bozkaya** [comment]
To say anything I need to debug it. However, I do not have that much memory to run the input. I guess the situation may be related int variables, which should be defined as long int for such large molecules. @dgasmith

**Comment by hokru** [comment]
I also ran this and can confirm. From the `timer.dat` file it looks like it finished `Build (IA|JB)` for the `1st-order T2` part.  The `1st-order T2` timer is `0.000w` so I assume it has not finished.

Not much happening with integers between this besides perhaps writing the T2 matrix to disk? https://github.com/psi4/psi4/blob/master/psi4/src/psi4/dfocc/t2_1st_sc.cc#L191

Btw, changing the auxbasis needs to be done via `DF_BASIS_CC`

**Comment by dbenoit1** [comment]
Thank you for the extra information! I was wondering if there was a quick way of promoting int to long int... Perhaps with a compile flag, so that we can check the hypothesis?

**Comment by hokru** [comment]
> Perhaps with a compile flag,

I doubt that is a good idea. Too many interoperating libraries.

```
void Tensor2d::write_symm(std::shared_ptr<psi::PSIO> psio, size_t fileno) {
    // Form Lower triangular part
    int ntri_col = 0.5 * dim1_ * (dim1_ + 1);
```

so  `dim1_` of the `T2` matrix is `nocc*nvirt=60*1305=78300`, leading to
`0.5*(78300)*(78300+1)=3065484150` for `int ntri_col`, which is larger than what `int` can hold `2,147,483,647`.

But I am sort of confused why other large matrices seem to work. Though I don't know the code well enough.

**Comment by bozkaya** [comment]
I have also reached the same conclusion, the size of ntri_col is larger than the maximum value of int. hence, changing it to ULI would work. 

The reason why not other matrices works is that other matrices are not using "write_symm" function, where there is packing. The most of other matrices use "write" function. @dgasmith @hokru

**Comment by hokru** [comment]
Excellent. Someone do it  :-) 

However, I still wonder if it's feasible to run this at all. 1300 virtuals is enormous for MP3!
water clusters need diffuse functions, but maybe not the full `aug` set.

**Comment by dgasmith** [comment]
Can we simply replace all ints with a `long long int`? Or should it be more surgical and only touch the compound index files and consciously coerce them to `size_t`?

**Comment by dbenoit1** [comment]
OK, this sounds like a possible plan. I'm going to try to update dfocc.h and replace orbital related ints with long long ints... fingers crossed it'll work :)

**Comment by loriab** [comment]
Many of the modules got a size_t pass (eff. long int) during lgtm season. But no one dares touch Bozkaya modules until that PR (in my name) goes in, and that needs several  tests added to ensure we’re not breaking stuff as we go.

**Comment by hokru** [comment]
> replace orbital related ints with long long ints... fingers crossed it'll work :)

You may need to fix both the `write/read_symm` functions.
