### ISSUE TITLE
v2rdm_casscf build was not compatible with the psi4-1.3.2+ecbda83 version

### ISSUE THREAD

**Issue by chrinide** [psi4/psi4#1775]
Hi all,

Just a report.

Current conda v2rdm_casscf build was not compatible with the production psi4-1.3.2+ecbda83 version(Tested under Win10 WSL Ubuntu1804).

```
Traceback (most recent call last):
  File "/root/miniconda3/envs/psi/bin/psi4", line 177, in <module>
    import psi4
  File "/root/miniconda3/envs/psi/lib//python3.6/site-packages/psi4/__init__.py", line 82, in <module>
    from .driver import endorsed_plugins
  File "/root/miniconda3/envs/psi/lib//python3.6/site-packages/psi4/driver/endorsed_plugins.py", line 33, in <module>
    import v2rdm_casscf
  File "/root/miniconda3/envs/psi/lib//python3.6/site-packages/v2rdm_casscf/__init__.py", line 45, in <module>
    psi4.core.plugin_load(sofile)
RuntimeError:
Fatal Error: load_plugin: Cannot open library: core.so: cannot open shared object file: No such file or directory
Error occurred in file: /scratch/psilocaluser/conda-builds/psi4-multiout_1563933640427/work/psi4/src/psi4/libplugin/load_plugin.cc on line: 52
The most recent 5 function calls were:


forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
libgdma.so         00007F0370F460DC  for__signal_handl     Unknown  Unknown
libpthread-2.27.s  00007F03763F2890  Unknown               Unknown  Unknown
ld-2.27.so         00007F0376616A31  Unknown               Unknown  Unknown
libc-2.27.so       00007F03761472DF  _dl_catch_excepti     Unknown  Unknown
libc-2.27.so       00007F037614736F  _dl_catch_error       Unknown  Unknown
libdl-2.27.so      00007F0375DD1735  Unknown               Unknown  Unknown
libdl-2.27.so      00007F0375DD10B3  dlclose               Unknown  Unknown
core.cpython-36m-  00007F0371E280E7  Unknown               Unknown  Unknown
core.cpython-36m-  00007F037202C9B2  Unknown               Unknown  Unknown
core.cpython-36m-  00007F03720539F6  Unknown               Unknown  Unknown
core.cpython-36m-  00007F0371AFD0D6  Unknown               Unknown  Unknown
python3.6          00007F03769C4B36  PyCFunction_Call      Unknown  Unknown
python3.6          00007F03769C1A5E  PyObject_Call         Unknown  Unknown
python3.6          00007F0376AC1834  Unknown               Unknown  Unknown
python3.6          00007F0376ABF37F  Py_FinalizeEx         Unknown  Unknown
python3.6          00007F0376AC957E  Py_Main               Unknown  Unknown
python3.6          00007F037699388E  main                  Unknown  Unknown
libc-2.27.so       00007F0376001B97  __libc_start_main     Unknown  Unknown
python3.6          00007F0376A73160  Unknown               Unknown  Unknown
```

**Comment by loriab** [comment]
Thanks for the report. Just to be clear, the stable release psi v1.3.2 (`-c psi4`) isn't expected to be compatible with the latest v2rdm from `-c psi4/label/dev` which has build version (can see in `conda list`) that ends in `_11`. Instead, it should be compatible with the latest v2rdm installable from `-c psi4` which ends in `_6`. Could you be trying to mix conda channel labels?
