### ISSUE TITLE
Error Extraction Mangles Message

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#1920]
Sorry, @hokru. I've been trying to build Francesco and Shuhe's [DSRG-PT2 gradient plugin](https://github.com/ustcwsh/Shuhe_Project) to test a theory. (In multiple senses of "theory.") Shuhe's code was written for Python 2, so Psi rightly complains about invalid syntax.

```
Traceback (most recent call last):
  File "/Users/jonathonmisiewicz/psi4/objdir/stage/bin/psi4", line 331, in <module>
    exec(content)
  File "<string>", line 19, in <module>

  File "./../dsrgpt2_plug/__init__.py", line 45
    print "imported so file: ", sofile
                             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("imported so file: ", sofile)?
```

The error message that Holger's message extractor gives me is less readable.

```
!----------------------------------------------------------------------------------!
!                                                                                  !
!  ", sofile                                                                       !
! ,                             ^                                                  !
! ,SyntaxError: Missing parentheses in call to 'print'. Did you mean               !
!     print("imported so file: ", sofile)?                                         !
!                                                                                  !
!----------------------------------------------------------------------------------!
```

The error extractor should be patched to just report the SyntaxError.

**Comment by hokru** [comment]
A `SyntaxError` in the traceback prints also the offending line before the exception message. That isn't caught.

**Comment by JonathonMisiewicz** [comment]
I don't follow. Isn't the offending line `print "imported so file: ", sofile`? In that case, the two commas afterwards shouldn't be there, and the entire line should display, right?

**Comment by hokru** [comment]
I haven't tested it, but one issues seems (as far as I read the traceback docs) that the exception message from the `SyntaxError` contains the offending line before the normal content, which is `ExceptionName: <text>`. 

Though syntax errors usually crash for me like this:

```
Traceback (most recent call last):
  File "/Users/kruse/qc/psi4.bin/bin/psi4", line 331, in <module>
    exec(content)
  File "<string>", line 29
    print '1'
            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('1')?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kruse/qc/psi4.bin/bin/psi4", line 348, in <module>
    suspect_lineno = traceback.extract_tb(exc_traceback)[1].lineno - 1  # -1 for 0 indexing
IndexError: list index out of range
```
