### ISSUE TITLE
Crash due to printing

### ISSUE THREAD

**Issue by jevandezande** [psi4/psi4#1983]
When I run psi4 on a remote computer with `psi4 & disown` and exit before the job is complete, it crashes with messages like the following.

```
Traceback (most recent call last):
  File "/path/to/conda/envs/p4env/bin/psi4", line 337, in <module>
    exec(content)
File "<string>", line 49, in <module>
File "/path/to/conda/envs/p4env/lib//python3.8/site-packages/psi4/driver/driver.py", line 1360, in optimize                                                                                                                                                              print('Optimizer: Optimization complete!')
```

```
Traceback (most recent call last):
  File "/path/to/conda/envs/p4env/bin/psi4", line 337, in <module>
    exec(content)
  File "<string>", line 26, in <module>
  File "/path/to/conda/envs/p4env/lib//python3.8/site-packages/psi4/driver/driver.py", line 1727, in frequency
    H, wfn = hessian(name, return_wfn=True, molecule=molecule, **kwargs)
  File "/path/to/conda/envs/p4env/lib//python3.8/site-packages/psi4/driver/driver.py", line 1466, in hessian
    return driver_cbs._cbs_gufunc(hessian, name.lower(), **kwargs, ptype="hessian")
  File "/path/to/conda/envs/p4env/lib//python3.8/site-packages/psi4/driver/driver_cbs.py", line 1955, in _cbs_gufunc
    ptype_value, wfn = func(method_name, return_wfn=True, molecule=molecule, **kwargs)File "/path/to/conda/envs/p4env/lib//python3.8/site-packages/psi4/driver/driver.py", line 1562, in hessian
  File "/path/to/conda/envs/p4env/lib//python3.8/site-packages/psi4/driver/driver.py", line 1562, in hessian
    _process_displacement(
  File "/path/to/conda/envs/p4env/lib//python3.8/site-packages/psi4/driver/driver.py", line 167, in _process_displacement
    sys.stdout.flush()
```

It seems to work if I add a redirect of the output to /dev/null, `psi4 > /dev/null & disown`, but I was wondering if there would be a way to fix this inside of psi4 (might require the removal of all print statements). It took me way too long to figure out this problem, so if nothing else, I hope that posting this issue will help others with this problem.

**Comment by loriab** [comment]
Yes, `print_out()`s vastly outnumber `printf`s or `print()`s, but there are still a few, with options errors ("Did you mean ...?") and optimization reports being the most likely encountered. They were left because they were thought helpful for non-background runs and there weren't downsides. Looks like you've found one. (I guess I always redirect with background & disown.) The optimization printing should go away with the switch to pyoptking and the ddd driver. Sounds like considering a purge of other direct printing then would be good, too.

Good to leave this open. Thanks for the report.

**Comment by hokru** [comment]
Another, and generally safer, option is to use `nohup psi4  &` on remote machines as this will always decouple `stdout` from the job, something `disown` is not doing.

**Comment by TiborGY** [comment]
In my experience (at least on remote hosts running relatively modern versions of Ubuntu derivatives, 18.04 and up), starting a process in the background and then doing a `logout` keeps the process running indefinitely. Simply closing the Putty window, etc. does not, the same happens if the network connection is interrupted.
