### ISSUE TITLE
QCEngine wavefunction error

### ISSUE THREAD

**Issue by jthorton** [psi4/psi4#1987]
When requesting the wavefunction as part of the result via the protocol in QCEngine only the `orbitals_and_eigenvalues` option works successfully. I think this is due to an error in the returned dictionary here https://github.com/psi4/psi4/blob/5de566ed7d4bf51816c673c4ea1def449e4e8618/psi4/driver/schema_wrapper.py#L324.I think this line should say `"density_a": "scf_density_a",`.

QCEngine error:
```
QCEngine Unknown Error: Traceback (most recent call last):
  File "/Users/joshuahorton/miniconda3/envs/qcfractal/lib//python3.7/site-packages/psi4/driver/schema_wrapper.py", line 400, in run_qcschema
    ret = qcel.models.Result(**ret_data, stdout=_read_output(outfile))
  File "/Users/joshuahorton/miniconda3/envs/qcfractal/lib/python3.7/site-packages/qcelemental/models/results.py", line 520, in __init__
    super().__init__(*args, **kwargs)
  File "pydantic/main.py", line 344, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 900, in pydantic.main.validate_model
  File "pydantic/fields.py", line 556, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 732, in pydantic.fields.ModelField._apply_validators
  File "pydantic/class_validators.py", line 280, in pydantic.class_validators._generic_validator_cls.lambda4
  File "/Users/joshuahorton/miniconda3/envs/qcfractal/lib/python3.7/site-packages/qcelemental/models/results.py", line 463, in _wavefunction_protocol
    ret_wfn[key] = wfn[key]
KeyError: 'scf_density_ba'
```

**Comment by hokru** [comment]
I'm not very familiar with the schema_wrapper but that does look like a typo. Thanks!

**Comment by jthorton** [comment]
Thanks for fixing that one! I have found another however which comes up when I request to save all wavefunction properties via QCEngine using the latest dev version of psi4, here is the error message.
```
QCEngine Input Error: Traceback (most recent call last):
File "/Users/joshua/miniconda3/envs/psi4/lib//python3.8/site-packages/psi4/driver/schema_wrapper.py", line 410, in run_qcschema
ret = qcel.models.AtomicResult(**ret_data, stdout=_read_output(outfile))
File "pydantic/main.py", line 274, in pydantic.main.BaseModel.__init__\npydantic.error_wrappers.ValidationError: 1 validation error for AtomicResult\nwavefunction -> occupations_a
  Return quantity scf_occupations_a does not exist in the values. (type=value_error)
```

I think this is related to the lines here which pulls out the occupations which have been commented out I am not sure if these simply need to be uncommented or if there is some formatting that needs to be worked out https://github.com/psi4/psi4/blob/670a85012a2864dd6673ac4a39243156205c500e/psi4/driver/schema_wrapper.py#L344

ccing @dgasmith in case he knows the status of this

**Comment by SimonBoothroyd** [comment]
This second issue seems like it would be fixed by #2036.

**Comment by zachglick** [comment]
Yeah, that `scf_occupations_a` error is exactly what #2036 should fix, I didn't realize an issue had already been raised

**Comment by PeterKraus** [comment]
@jthorton This should now be fixed, I'll close this issue.
