### ISSUE TITLE
Problem with fchk function

### ISSUE THREAD

**Issue by zjing7** [psi4/psi4#2177]
There is a problem "Orbital basis argument must not be empty" when calling fchk() after the method and basis are defined in the energy() function call.
This problem is found in the latest development version 1.4rc2.dev97.
v1.3.x did not have this problem.

```
molecule {
0 1
 O    3.031916    1.669683    2.276015
 H    2.818359    1.127467    3.035217
 H    2.894980    2.585172    2.519181
}
E, wfn = energy('mp2/6-311G**',properties=['dipole'],return_wfn=True)
fchk(wfn, "test4-dma.fchk")
clean()
```

```
Traceback (most recent call last):
  File "/home/zj2244/Public/Software/anaconda3/envs/p4dev1/bin/psi4", line 332, in <module>
    exec(content)
  File "<string>", line 69, in <module>
  File "/home/zj2244/Public/Software/anaconda3/envs/p4dev1/lib//python3.6/site-packages/psi4/driver/driver.py", line 1993, in fchk
    wfn_ = core.Wavefunction.build(wfn.molecule(), core.get_global_option('BASIS'))
  File "/home/zj2244/Public/Software/anaconda3/envs/p4dev1/lib//python3.6/site-packages/psi4/driver/p4util/python_helpers.py", line 125, in _core_wavefunction_build
    basis = core.BasisSet.build(mol, "ORBITAL", basis)
  File "/home/zj2244/Public/Software/anaconda3/envs/p4dev1/lib//python3.6/site-packages/psi4/driver/p4util/python_helpers.py", line 90, in _pybuild_basis
    return_atomlist=return_atomlist)
  File "/home/zj2244/Public/Software/anaconda3/envs/p4dev1/lib//python3.6/site-packages/psi4/driver/qcdb/libmintsbasisset.py", line 646, in pyconstruct
    raise ValidationError("""Orbital basis argument must not be empty.""")

psi4.driver.qcdb.exceptions.ValidationError: Orbital basis argument must not be empty.


Printing out the relevant lines from the Psithon --> Python processed input file:
     H    2.818359    1.127467    3.035217
     H    2.894980    2.585172    2.519181
    """)
    core.IO.set_default_namespace("")
    E, wfn = energy('mp2/6-311G**',properties=['dipole'],return_wfn=True)
--> fchk(wfn, "test4-dma.fchk")
    clean()

!--------------------------------------------!
!                                            !
!  Orbital basis argument must not be empty. !
!                                            !
!--------------------------------------------!

```

**Comment by hokru** [comment]
Thanks for the report.

The command for MP2 dipoles is `E, wfn = properties('mp2/6-311G**', properties=['dipole'],return_wfn=True)`.

However it appears the global variable for the basis set is not set through this and the new fchk writer complains.
As a workaround you can do it like this:
```
set basis 6-311G**
E, wfn = properties('mp2, properties=['dipole'] ,return_wfn=True)
fchk(wfn, "test4-dma.fchk")
```
