### ISSUE TITLE
issue installing from downloaded .exe

### ISSUE THREAD

**Issue by ErikCVik** [psi4/psi4#2236]
OS: Windows 10

I downloaded the psi4 installation executable and ran the commands from the manual as described.

>>>  start /wait "" Psi4conda-1.4rc1-py38-Windows-x86_64.exe /InstallationType=JustMe /RegisterPython=0 /S /D=%UserProfile%\psi4conda
>>>  psi4 --test

psi4 is unrecognizable after installation, but I added the directory to my path. 

rerunning psi4 -- test gives following error:

`C:\Users\erikc>psi4 --test
Traceback (most recent call last):
  File "C:\Users\erikc\psi4conda\lib\site-packages\psi4\__init__.py", line 55, in <module>
    from . import core
ImportError: DLL load failed while importing core: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erikc\psi4conda\Scripts\psi4-script.py", line 182, in <module>
    import psi4  # isort:skip
  File "C:\Users\erikc\psi4conda\lib\site-packages\psi4\__init__.py", line 60, in <module>
    raise ImportError("{0}".format(err))
ImportError: DLL load failed while importing core: The specified module could not be found.`

**Comment by loriab** [comment]
Any chance the rc2 installer behaves differently?

**Comment by ErikCVik** [comment]
I am not sure what the rc2 installer is or what it could be compared to

**Comment by loriab** [comment]
Oh, I meant that it looks like your installer was from this page (https://psicode.netlify.app/installs/v14rc1/) rather than this page (https://psicode.netlify.app/installs/v14rc2/). May as well try the most recent.

**Comment by ErikCVik** [comment]
I reinstalled with the rc2 installer and the same error persists.

I am looking in the psi4 python module and the "core" file seems to not have been compiled correctly? I am guessing it should be a .py file but in my directory its a .pyd file and has a name "core.cp38-win_amd64"

Can anyone confirm this and/or point me to where the corrrect file is here so I can download and replace?

**Comment by loriab** [comment]
The `core` file is compiled, so the extension is likely ok. 

A few background questions-- 
* do other conda packages like NumPy work for you? 
*  can/did you do the Windows equivalent of log out then log back in? 
* what exactly was your "added the directory to my path" command? 
* what does `psi4 --version` say?

I know these seem basic, but no one here actually uses Windows (the installers are built on CI), so we have to feel around on debugging Windows installation.

**Comment by ErikCVik** [comment]
(1) do other conda packages like NumPy work for you?
Yes, I just opened pycharm using conda as the interpreter, import numpy and converted a list to a np array

(2) can/did you do the Windows equivalent of log out then log back in?
I just restarted my computer, error still persists 

(3) what exactly was your "added the directory to my path" command?
I went system properties --> environment manager --> Path 
then added the following code in "C:\Users\erikc\psi4conda"

(4) what does psi4 --version say?
C:\Users\erikc>psi4 --version
Traceback (most recent call last):
  File "C:\Users\erikc\psi4conda\lib\site-packages\psi4\__init__.py", line 55, in <module>
    from . import core
ImportError: DLL load failed while importing core: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erikc\psi4conda\Scripts\psi4-script.py", line 182, in <module>
    import psi4  # isort:skip
  File "C:\Users\erikc\psi4conda\lib\site-packages\psi4\__init__.py", line 60, in <module>
    raise ImportError("{0}".format(err))
ImportError: DLL load failed while importing core: The specified module could not be found.

**Comment by ErikCVik** [comment]
I also tried reinstalling via executing the .exe file in my downloads directory and the same error pops up 

"C:\Users\erikc>psi4 --test
Traceback (most recent call last):
  File "C:\Users\erikc\psi4conda\lib\site-packages\psi4\__init__.py", line 55, in <module>
    from . import core
ImportError: DLL load failed while importing core: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erikc\psi4conda\Scripts\psi4-script.py", line 182, in <module>
    import psi4  # isort:skip
  File "C:\Users\erikc\psi4conda\lib\site-packages\psi4\__init__.py", line 60, in <module>
    raise ImportError("{0}".format(err))
ImportError: DLL load failed while importing core: The specified module could not be found."

**Comment by ErikCVik** [comment]
Doesn't 
> from . import core
mean look up one directory for the package core?

If that is true I do not see "core" in the site-packages folder in psi4conda

**Comment by loriab** [comment]
`Lib/site-packages/psi4/core.cp38-win_amd64.pyd` is indeed the name for the fat compiled file.

The `site-packages\psi4\__init__.py` has the `from . import core`. The dot is "here", so it's seeking the `site-packages\psi4\core.*pyd` file, so all's well there, I think.

For adding to PATH, I think it'd be `psi4conda\Scripts` to add, not the parent directory.

But I wonder if you could be using the ordinary Windows prompt instead of the Anaconda command prompt. Worth trying the left-side "Recommended Approach" in step 6 of https://www.datacamp.com/community/tutorials/installing-anaconda-windows rather than the right-side setup, if you aren't already.

**Comment by ErikCVik** [comment]
Sorry, ```C:\Users\erikc\psi4conda\Scripts ``` was what was in my Path

I double checked via ```psi4 --test``` in cmd and the same error pops up

I also just reinstalled anaconda without adding it to my path and then reinstalling psi4. Nothing changed

**Comment by loriab** [comment]
To make sure we're clear, an Ana/Mini/Psi4conda installation are all independent. That is, `where conda`, `where python`, and `where psi4` should all start the same. If you've already got an Ana/Miniconda installation, maybe try skipping the Psi4conda installer, and try installing the psi4 package directly: `conda create -n <p4env> psi4 -c psi4/label/dev`, where `<p4env>` is your choice.

**Comment by ErikCVik** [comment]
I installed anaconda and psi4 independently. does the code below help?

```
(base) C:\Users\erikc>where conda
C:\Users\erikc\anaconda3\Library\bin\conda.bat
C:\Users\erikc\anaconda3\Scripts\conda.exe
C:\Users\erikc\psi4conda\condabin\conda.bat
C:\Users\erikc\psi4conda\Scripts\conda.exe

(base) C:\Users\erikc>where python
C:\Users\erikc\anaconda3\python.exe

(base) C:\Users\erikc>where psi4
C:\Users\erikc\psi4conda\Scripts\psi4.exe

(base) C:\Users\erikc>conda create -n psi4env psi4 -c psi4/label/dev
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError:


(base) C:\Users\erikc>
```

**Comment by loriab** [comment]
Whoops, I forgot psi4 on windows is conda-forge based. Use `conda create -n <p4env> psi4 -c psi4/label/dev -c conda-forge`. 

I'm nervous to see psi4 and python executables from different (psi4conda and anaconda3) locations, so maybe ditch psiconda from path, and create a p4env with anaconda3.

**Comment by ErikCVik** [comment]
I ran  ```conda create -n <p4env> psi4 -c psi4/label/dev -c conda-forge''' and it worked.```

makes sense since rdkit uses conda-forge as well

I then ran ```psi4 --test``` and here are the results. does it matter some were skipped/ failed?

```
(psi4env) C:\Users\erikc>psi4 --test
=========================================================================== test session starts ===========================================================================
platform win32 -- Python 3.8.10, pytest-6.2.4, py-1.10.0, pluggy-0.13.1 -- C:\Users\erikc\psi4conda\envs\psi4env\python.exe
cachedir: .pytest_cache
rootdir: C:\Users\erikc
collected 3356 items / 3301 deselected / 55 selected

psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons.py::test_gdma SKIPPED (Not detecting module gdma. Install package if necessary to enable tests.)     [  1%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons.py::test_ipi_broker1 PASSED                                                                          [  3%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons.py::test_ipi_broker2 PASSED                                                                          [  5%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons.py::test_mrcc SKIPPED (Not detecting module mrcc. Install package if necessary to enable tests.)     [  7%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons.py::test_chemps2 SKIPPED (Not detecting module chemps2. Install package if necessary to enable t...) [  9%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons.py::test_mp2d SKIPPED (Not detecting module mp2d. Install package if necessary to enable tests.)     [ 10%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons.py::test_dftd3 PASSED                                                                                [ 12%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons.py::test_libefp SKIPPED (Not detecting module libefp. Install package if necessary to enable tests.) [ 14%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons.py::test_pcmsolver[pcm_helper] SKIPPED (Not detecting module pcmsolver. Install package if neces...) [ 16%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons.py::test_erd SKIPPED (Not detecting module erd. Install package if necessary to enable tests.)       [ 18%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons.py::test_simint SKIPPED (Not detecting module simint. Install package if necessary to enable tests.) [ 20%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons.py::test_json PASSED                                                                                 [ 21%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons.py::test_cfour SKIPPED (Not detecting module cfour. Install package if necessary to enable tests.)   [ 23%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons.py::test_v2rdm_casscf SKIPPED (Not detecting module v2rdm_casscf. Install package if necessary t...) [ 25%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons.py::test_gpu_dfcc SKIPPED (Not detecting module gpu_dfcc. Install package if necessary to enable...) [ 27%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons.py::test_grimme_3c PASSED                                                                            [ 29%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons.py::test_dkh SKIPPED (Not detecting module dkh. Install package if necessary to enable tests.)       [ 30%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons.py::test_snsmp2 SKIPPED (Not detecting module snsmp2. Install package if necessary to enable tests.) [ 32%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons.py::test_resp SKIPPED (Not detecting module resp. Install package if necessary to enable tests.)     [ 34%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons.py::test_resp_2 SKIPPED (Not detecting module resp. Install package if necessary to enable tests.)   [ 36%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons.py::test_psi4fockci SKIPPED (Not detecting module fockci. Install package if necessary to enable...) [ 38%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons.py::test_cppe SKIPPED (Not detecting module cppe. Install package if necessary to enable tests.)     [ 40%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons.py::test_cct3 SKIPPED (Not detecting module cct3. Install package if necessary to enable tests.)     [ 41%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons.py::test_psixas SKIPPED (Not detecting module psixas. Install package if necessary to enable tests.) [ 43%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons_qcschema.py::test_gdma SKIPPED (Not detecting module gdma. Install package if necessary to enabl...) [ 45%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons_qcschema.py::test_ipi_broker1 SKIPPED (Not detecting module ipi. Install package if necessary to...) [ 47%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons_qcschema.py::test_chemps2 SKIPPED (Not detecting module chemps2. Install package if necessary to...) [ 49%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons_qcschema.py::test_mp2d SKIPPED (Not detecting module mp2d. Install package if necessary to enabl...) [ 50%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons_qcschema.py::test_dftd3 PASSED                                                                       [ 52%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons_qcschema.py::test_libefp SKIPPED (Not detecting module libefp. Install package if necessary to e...) [ 54%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons_qcschema.py::test_pcmsolver SKIPPED (Not detecting module pcmsolver. Install package if necessar...) [ 56%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons_qcschema.py::test_integrals[libint2] PASSED                                                          [ 58%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons_qcschema.py::test_integrals[simint] SKIPPED (Not detecting module simint. Install package if nec...) [ 60%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons_qcschema.py::test_json PASSED                                                                        [ 61%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons_qcschema.py::test_v2rdm_casscf SKIPPED (Not detecting module v2rdm_casscf. Install package if ne...) [ 63%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons_qcschema.py::test_grimme_3c PASSED                                                                   [ 65%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons_qcschema.py::test_dkh SKIPPED (Not detecting module dkh. Install package if necessary to enable ...) [ 67%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons_qcschema.py::test_snsmp2 SKIPPED (Not detecting module snsmp2. Install package if necessary to e...) [ 69%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons_qcschema.py::test_resp SKIPPED (Not detecting module resp. Install package if necessary to enabl...) [ 70%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons_qcschema.py::test_psi4fockci SKIPPED (Not detecting module fockci. Install package if necessary ...) [ 72%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons_qcschema.py::test_cppe SKIPPED (Not detecting module cppe. Install package if necessary to enabl...) [ 74%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_mdi.py::test_mdi_water SKIPPED (Not detecting module mdi. Install package if necessary to enable tests.)    [ 76%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_option.py::test_spacious_option PASSED                                                                      [ 78%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_psi4.py::test_psi4_basic PASSED                                                                             [ 80%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_psi4.py::test_psi4_cc PASSED                                                                                [ 81%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_psi4.py::test_psi4_cas PASSED                                                                               [ 83%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_psi4.py::test_psi4_dfmp2 PASSED                                                                             [ 85%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_psi4.py::test_psi4_sapt PASSED                                                                              [ 87%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_psi4.py::test_psi4_scfproperty PASSED                                                                       [ 89%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_psi4_qcschema.py::test_psi4_basic PASSED                                                                    [ 90%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_psi4_qcschema.py::test_psi4_cc XFAIL (no AtomicInput optimization)                                          [ 92%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_psi4_qcschema.py::test_psi4_cas PASSED                                                                      [ 94%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_psi4_qcschema.py::test_psi4_dfmp2 PASSED                                                                    [ 96%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_psi4_qcschema.py::test_psi4_sapt PASSED                                                                     [ 98%]
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_psi4_qcschema.py::test_psi4_scfproperty PASSED                                                              [100%]

============================================================================ warnings summary =============================================================================
psi4conda\envs\psi4env\lib\site-packages\qcelemental\molparse\from_arrays.py:599: 3 warnings
psi4conda\envs\psi4env\lib\site-packages\qcelemental\molparse\from_arrays.py:701: 3 warnings
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons.py: 2700 warnings
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons_qcschema.py: 1773 warnings
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_option.py: 92 warnings
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_psi4.py: 2330 warnings
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_psi4_qcschema.py: 2270 warnings
  `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

psi4conda\envs\psi4env\lib\site-packages\qcelemental\molparse\from_arrays.py:698: 3 warnings
psi4conda\envs\psi4env\lib\site-packages\qcelemental\molparse\from_arrays.py:699: 3 warnings
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons.py: 1414 warnings
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons_qcschema.py: 954 warnings
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_option.py: 48 warnings
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_psi4.py: 1302 warnings
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_psi4_qcschema.py: 1266 warnings
  `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

psi4conda\envs\psi4env\lib\site-packages\qcelemental\molparse\from_arrays.py:702: 3 warnings
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons.py: 707 warnings
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons_qcschema.py: 477 warnings
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_option.py: 24 warnings
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_psi4.py: 651 warnings
psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_psi4_qcschema.py: 633 warnings
  `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

psi4conda/envs/psi4env/lib/site-packages/psi4/tests/test_addons.py::test_json
  Using `psi4.json_wrapper.run_json` instead of `psi4.schema_wrapper.run_qcschema` is deprecated, and in 1.5 it will stop working

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================================= short test summary info =========================================================================
SKIPPED [1] psi4conda\envs\psi4env\lib\site-packages\psi4\tests\test_addons.py:13: Not detecting module gdma. Install package if necessary to enable tests.
SKIPPED [1] psi4conda\envs\psi4env\lib\site-packages\psi4\tests\test_addons.py:162: Not detecting module mrcc. Install package if necessary to enable tests.
SKIPPED [1] psi4conda\envs\psi4env\lib\site-packages\psi4\tests\test_addons.py:186: Not detecting module chemps2. Install package if necessary to enable tests.
SKIPPED [1] psi4conda\envs\psi4env\lib\site-packages\psi4\tests\test_addons.py:233: Not detecting module mp2d. Install package if necessary to enable tests.
SKIPPED [1] psi4conda\envs\psi4env\lib\site-packages\psi4\tests\test_addons.py:428: Not detecting module libefp. Install package if necessary to enable tests.
SKIPPED [1] psi4conda\envs\psi4env\lib\site-packages\psi4\tests\test_addons.py:486: Not detecting module pcmsolver. Install package if necessary to enable tests.
SKIPPED [1] psi4conda\envs\psi4env\lib\site-packages\psi4\tests\test_addons.py:733: Not detecting module erd. Install package if necessary to enable tests.
SKIPPED [1] psi4conda\envs\psi4env\lib\site-packages\psi4\tests\test_addons.py:741: Not detecting module simint. Install package if necessary to enable tests.
SKIPPED [1] psi4conda\envs\psi4env\lib\site-packages\psi4\tests\test_addons.py:783: Not detecting module cfour. Install package if necessary to enable tests.
SKIPPED [1] psi4conda\envs\psi4env\lib\site-packages\psi4\tests\test_addons.py:816: Not detecting module v2rdm_casscf. Install package if necessary to enable tests.
SKIPPED [1] psi4conda\envs\psi4env\lib\site-packages\psi4\tests\test_addons.py:868: Not detecting module gpu_dfcc. Install package if necessary to enable tests.
SKIPPED [1] psi4conda\envs\psi4env\lib\site-packages\psi4\tests\test_addons.py:931: Not detecting module dkh. Install package if necessary to enable tests.
SKIPPED [1] psi4conda\envs\psi4env\lib\site-packages\psi4\tests\test_addons.py:1015: Not detecting module snsmp2. Install package if necessary to enable tests.
SKIPPED [1] psi4conda\envs\psi4env\lib\site-packages\psi4\tests\test_addons.py:1031: Not detecting module resp. Install package if necessary to enable tests.
SKIPPED [1] psi4conda\envs\psi4env\lib\site-packages\psi4\tests\test_addons.py:1099: Not detecting module resp. Install package if necessary to enable tests.
SKIPPED [1] psi4conda\envs\psi4env\lib\site-packages\psi4\tests\test_addons.py:1189: Not detecting module fockci. Install package if necessary to enable tests.
SKIPPED [1] psi4conda\envs\psi4env\lib\site-packages\psi4\tests\test_addons.py:1213: Not detecting module cppe. Install package if necessary to enable tests.
SKIPPED [1] psi4conda\envs\psi4env\lib\site-packages\psi4\tests\test_addons.py:1240: Not detecting module cct3. Install package if necessary to enable tests.
SKIPPED [1] psi4conda\envs\psi4env\lib\site-packages\psi4\tests\test_addons.py:1286: Not detecting module psixas. Install package if necessary to enable tests.
SKIPPED [1] psi4conda\envs\psi4env\lib\site-packages\psi4\tests\test_addons_qcschema.py:25: Not detecting module gdma. Install package if necessary to enable tests.
SKIPPED [1] psi4conda\envs\psi4env\lib\site-packages\psi4\tests\test_addons_qcschema.py:75: Not detecting module ipi. Install package if necessary to enable tests.
SKIPPED [1] psi4conda\envs\psi4env\lib\site-packages\psi4\tests\test_addons_qcschema.py:185: Not detecting module chemps2. Install package if necessary to enable tests.
SKIPPED [1] psi4conda\envs\psi4env\lib\site-packages\psi4\tests\test_addons_qcschema.py:196: Not detecting module mp2d. Install package if necessary to enable tests.
SKIPPED [1] psi4conda\envs\psi4env\lib\site-packages\psi4\tests\test_addons_qcschema.py:242: Not detecting module libefp. Install package if necessary to enable tests.
SKIPPED [1] psi4conda\envs\psi4env\lib\site-packages\psi4\tests\test_addons_qcschema.py:308: Not detecting module pcmsolver. Install package if necessary to enable tests.
SKIPPED [1] psi4conda\envs\psi4env\lib\site-packages\psi4\tests\test_addons_qcschema.py:377: Not detecting module simint. Install package if necessary to enable tests.
SKIPPED [1] psi4conda\envs\psi4env\lib\site-packages\psi4\tests\test_addons_qcschema.py:489: Not detecting module v2rdm_casscf. Install package if necessary to enable tests.
SKIPPED [1] psi4conda\envs\psi4env\lib\site-packages\psi4\tests\test_addons_qcschema.py:584: Not detecting module dkh. Install package if necessary to enable tests.
SKIPPED [1] psi4conda\envs\psi4env\lib\site-packages\psi4\tests\test_addons_qcschema.py:666: Not detecting module snsmp2. Install package if necessary to enable tests.
SKIPPED [1] psi4conda\envs\psi4env\lib\site-packages\psi4\tests\test_addons_qcschema.py:681: Not detecting module resp. Install package if necessary to enable tests.
SKIPPED [1] psi4conda\envs\psi4env\lib\site-packages\psi4\tests\test_addons_qcschema.py:688: Not detecting module fockci. Install package if necessary to enable tests.
SKIPPED [1] psi4conda\envs\psi4env\lib\site-packages\psi4\tests\test_addons_qcschema.py:708: Not detecting module cppe. Install package if necessary to enable tests.
SKIPPED [1] psi4conda\envs\psi4env\lib\site-packages\psi4\tests\test_mdi.py:11: Not detecting module mdi. Install package if necessary to enable tests.
========================================== 21 passed, 33 skipped, 3301 deselected, 1 xfailed, 16657 warnings in 72.64s (0:01:12) ==========================================
```

**Comment by loriab** [comment]
Hooray, that looks great. Skipped or xfailed is no problem (just how we handle testing optional dependencies). Outright failed is a problem, but I don't see any of those.

I think you're good to go. I wish I understood clearly what was causing your psi4conda problem, but that's awkward to debug. I suspect interference in python path btwn active python (in anaconda) and active psi4 (in psi4conda).

**Comment by JonathonMisiewicz** [comment]
To elaborate:

`xfailed`: expected failure. Just looking at the test, I'm not clear why we expect that particular test to fail, but as Lori said, it has to do with a program external to Psi4.
skipped: this tests the interface to a plugin you don't have and is only a concern if you need that particular plugin.

**Comment by JonathonMisiewicz** [comment]
@ErikCVik Do you need anything else, or can I close this issue (and the other one you raised)?

**Comment by ErikCVik** [comment]
@JonathonMisiewicz you can close both issues. I ran psi4 from pycharm as a python module and from the command line, both instances finished the jobs successfully.

@loriab thank you so much for your help!

**Comment by loriab** [comment]
I hit your error today in building the rc3 installer. It didn't happen when the rc2 installer was originally built or for recent plain `conda install psi4` installations like you ended up with, so it has to do with available packages upstream. I've fixed it by switching channel order in the installer. If you should try a Psi4conda install again with rc3, I'd be interested to hear success/failure.
