### ISSUE TITLE
1.4rc3 returns invalid QCSchema: missing wavefunction

### ISSUE THREAD

**Issue by berquist** [psi4/psi4#2242]
Using 080dba6, this input, which doesn't produce any wavefunction data,
```python
import json

import numpy as np

import psi4
import qcelemental as qcel


bohr2ang = qcel.constants.bohr2angstroms

geometry = (
    np.asarray(
        [
            0.0,
            0.0,
            -0.1294769411935893,
            0.0,
            -1.494187339479985,
            1.0274465079245698,
            0.0,
            1.494187339479985,
            1.0274465079245698,
        ]
    )
    / bohr2ang
)

json_input = {
    "schema_name": "qc_schema_input",
    "schema_version": 1,
    "molecule": {
        "geometry": geometry.tolist(),
        "symbols": ["O", "H", "H"],
    },
    "driver": "gradient",
    "model": {"method": "ccsd", "basis": "def2-tzvp"},
    "keywords": {"scf_type": "direct", "df_scf_guess": "false"},
}

ret = psi4.schema_wrapper.run_qcschema(json_input)

stub = "water_ccsd_gradient_psi4"
with open(f"{stub}.qcschema.out", "w") as handle:
    handle.write(ret.json())
```
validated with `qcschema.validate` produces
```
Traceback (most recent call last):
  File "./qcschema_validate.py", line 17, in <module>
    qcschema.validate(data=json.loads(p.read_text()), schema_type=args.schema_type)
  File "/home/eric/development/json/MolSSI_QC_JSON_Schema/qcschema/validate.py", line 16, in validate
    jsonschema.validate(data, schema)
  File "/home/eric/.pyenv/versions/miniconda3-4.7.12/envs/cclib_berquist_37/lib/python3.7/site-packages/jsonschema/validators.py", line 934, in validate
    raise error
jsonschema.exceptions.ValidationError: None is not of type 'object'

Failed validating 'type' in schema['properties']['wavefunction']:
...
On instance['wavefunction']:
    None
```

**Comment by berquist** [comment]
Ok, I see...`wavefunction` needs to not be present as a key, it can't be present with a value `null` or `{}`.

**Comment by loriab** [comment]
Hmm, I'm not getting that but do see

```
Traceback (most recent call last):
  File "/psi/gits/hrw-l2/objdir39b/readqcsk.py", line 19, in <module>
    qcschema.validate(data=json.loads(handle.read()), schema_type="output") #args.schema_type)
  File "/home/psilocaluser/gits/QC_JSON_Schema/qcschema/validate.py", line 16, in validate
    jsonschema.validate(data, schema)
  File "/home/psilocaluser/toolchainconda/envs/py39b/lib/python3.9/site-packages/jsonschema/validators.py", line 934, in validate
    raise error
jsonschema.exceptions.ValidationError: None is not of type 'string'

Failed validating 'type' in schema['properties']['id']:
    {'description': 'The optional ID for the computation.',
     'title': 'Id',
     'type': 'string'}

On instance['id']:
    None
```

Looks like more slight discrepancies btwn qcel `AtomicResult` and the hand-coded qcschema module. I thought I had reconciled those, but they may be waiting at https://github.com/MolSSI/QCSchema/pull/77/files .

**Comment by JonathonMisiewicz** [comment]
As somebody who isn't a Schema expert, I don't know what (if anything) developers need to do here. If either of you could provide some clarity? Otherwise, I'll be close the issue in a week.
