### ISSUE TITLE
An running error in fsapt.py

### ISSUE THREAD

**Issue by VincenzoChen** [psi4/psi4#2281]
I follow the f-sapt example in https://psicode.org/psi4manual/master/fisapt.html#i-sapt-a-representative-example.
When I run the fsapt.py, it reported such error:
Traceback (most recent call last):
  File "fsapt.py", line 1048, in <module>
    stuff = compute_fsapt(dirname, False)
  File "fsapt.py", line 888, in compute_fsapt
    order2  = extract_order2_fsapt(osapt, total_ws['A'], total_ws['B'], frags)
  File "fsapt.py", line 496, in extract_order2_fsapt
    val = np.einsum('i,ij,j', valueA, value, valueB)
  File "<__array_function__ internals>", line 6, in einsum
  File "/pubhome/zchen02/miniconda3/envs/psi4/lib/python3.7/site-packages/numpy/core/einsumfunc.py", line 1361, in einsum
    return c_einsum(*operands, **kwargs)
ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (52,)->(52,newaxis) (51,51)->(51,51) (52,)->(52) 
So I wonder is this a bug in program or somthing other?

**Comment by loriab** [comment]
https://github.com/psi4/psi4/blob/master/tests/isapt2/input.dat is the test case version of that example. It has some updates, and it runs. thanks for the notice -- we should update the example. lmk if further problems.

**Comment by VincenzoChen** [comment]
Thank you. I have seen the example. But I don't quite understand the code below. Are they a part of input file for psi4? And what is the function of these code in F-SAPT calculation?
```keys = ['Enuc', 'Eelst', 'Eexch', 'Eind', 'Edisp', 'Etot']  #TEST

Eref = {  #TEST
    'Enuc'  : 805.1177369,  #TEST
    'Eelst' :  -0.01449385168,      #TEST
    'Eexch' :  +0.01572480431,      #TEST
    'Eind'  :  -0.00445604001,      #TEST
    'Edisp' :  -0.00815025022,      #TEST
    'Etot'  :  -0.01137533761,      #TEST
    }  #TEST

Epsi = {  #TEST
    'Enuc'  : mol.nuclear_repulsion_energy(),           #TEST
    'Eelst' : variable("SAPT ELST ENERGY"),    #TEST
    'Eexch' : variable("SAPT EXCH ENERGY"),    #TEST
    'Eind'  : variable("SAPT IND ENERGY"),     #TEST
    'Edisp' : variable("SAPT DISP ENERGY"),    #TEST
    'Etot'  : variable("SAPT0 TOTAL ENERGY"),  #TEST
    }  #TEST

for key in keys:  #TEST
    compare_values(Eref[key], Epsi[key], 6, key)  #TEST```

**Comment by loriab** [comment]
Those lines are for quality control so we know that the program is consistently producing the right values as we develop the code. They're fine to include and run in this particular input file. As soon as you change the molecule or method/basis, you'll want to remove the lines since they won't be valid.

**Comment by VincenzoChen** [comment]
Sorry, I have not stated clearly. I tried the F-SAPT example in https://psicode.org/psi4manual/master/fisapt.html#f-sapt-a-representative-example. And when I use [fsapy.py](https://github.com/psi4/psi4/blob/master/psi4/share/psi4/fsapt/fsapt.py) to analyse the interaction between different fragment which was stated in fA.dat and fB.dat, it reported such error:
```Traceback (most recent call last):
File "fsapt.py", line 1048, in
stuff = compute_fsapt(dirname, False)
File "fsapt.py", line 888, in compute_fsapt
order2 = extract_order2_fsapt(osapt, total_ws['A'], total_ws['B'], frags)
File "fsapt.py", line 496, in extract_order2_fsapt
val = np.einsum('i,ij,j', valueA, value, valueB)
File "<array_function internals>", line 6, in einsum
File "/pubhome/zchen02/miniconda3/envs/psi4/lib/python3.7/site-packages/numpy/core/einsumfunc.py", line 1361, in einsum
return c_einsum(*operands, **kwargs)
ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (52,)->(52,newaxis) (51,51)->(51,51) (52,)->(52)```

**Comment by VincenzoChen** [comment]
It seems that the input file in https://github.com/psi4/psi4/blob/master/samples/fsapt1/input.dat and https://psicode.org/psi4manual/master/fisapt.html#f-sapt-a-representative-example has no differences

**Comment by loriab** [comment]
Ah, sorry, I misread that it was the analysis step that was giving trouble. When I add the fA and fB files below to the generated `fsapt/` directory, the `fsapt.py` runs cleanly and generates Total below, among others.
```
>>> cat fA.dat 
OH 1 2
>>> cat fB.dat 
OH 3 4
```

```
>>> cat Total.pdb 
HETATM    1 O    001 A   1       0.400   2.942  -0.265  1.00 -2.55           O  
HETATM    2 H    001 A   1       0.059   2.054  -0.510  1.00 -2.55           H  
HETATM    3 O    001 A   1       0.481   0.303  -0.778  1.00 -2.55           O  
HETATM    4 H    001 A   1       0.261  -0.500  -1.285  1.00 -2.55           H  
HETATM    5 C    001 A   1       2.330  -1.003   0.038  1.00  0.00           C  
HETATM    6 C    001 A   1       1.897   0.315  -0.590  1.00  0.00           C  
HETATM    7 C    001 A   1       2.282   1.507   0.297  1.00  0.00           C  
HETATM    8 C    001 A   1       1.822   2.846  -0.294  1.00  0.00           C  
HETATM    9 C    001 A   1       2.379   4.021   0.496  1.00  0.00           C  
HETATM   10 H    001 A   1       3.412  -1.030   0.198  1.00  0.00           H  
HETATM   11 H    001 A   1       2.054  -1.844  -0.607  1.00  0.00           H  
HETATM   12 H    001 A   1       1.827  -1.164   0.997  1.00  0.00           H  
HETATM   13 H    001 A   1       2.362   0.423  -1.576  1.00  0.00           H  
HETATM   14 H    001 A   1       3.370   1.514   0.438  1.00  0.00           H  
HETATM   15 H    001 A   1       1.813   1.381   1.281  1.00  0.00           H  
HETATM   16 H    001 A   1       2.143   2.930  -1.338  1.00  0.00           H  
HETATM   17 H    001 A   1       3.473   4.024   0.488  1.00  0.00           H  
HETATM   18 H    001 A   1       2.035   3.992   1.536  1.00  0.00           H  
HETATM   19 H    001 A   1       2.025   4.968   0.075  1.00  0.00           H  
```

**Comment by VincenzoChen** [comment]
I have tried the example you used and it also reported such error. Maybe it is the version of numpy that leads to this problem. Which version of numpy do you use. I use the 1.20.3.

**Comment by loriab** [comment]
> Which version of numpy do you use. I use the 1.20.3.

same.
```
conda list
# packages in environment at /home/psilocaluser/toolchainconda/envs/py39b:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
apipkg                    1.5              py39h06a4308_0  
appdirs                   1.4.4                      py_0  
argon2-cffi               20.1.0           py39h27cfd23_1  
async_generator           1.10               pyhd3eb1b0_0  
attrs                     20.3.0             pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
binutils_impl_linux-64    2.33.1               he6710b0_7  
binutils_linux-64         2.33.1              h9595d00_15  
black                     21.4b2             pyhd8ed1ab_0    conda-forge
blas                      1.0                         mkl  
bleach                    3.3.0              pyhd3eb1b0_0  
boost                     1.73.0          py39h06a4308_11  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2021.7.5             h06a4308_1  
certifi                   2021.5.30        py39h06a4308_0  
cffi                      1.14.5           py39h261ae71_0  
click                     7.1.2              pyhd3eb1b0_0  
cmake                     3.19.6               h973ab73_0  
dataclasses               0.8                pyhc8e2a94_1    conda-forge
dbus                      1.13.18              hb2f20db_0  
decorator                 4.4.2              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
dftd3                     3.2.1                h84218bc_2    psi4/label/dev
dftd4                     v3.3.0           py39h1d74c00_0    psi4/label/dev
dkh                       1.2                  h173d85e_2    psi4/label/dev
eigen                     3.3.7                hfd86e86_0  
entrypoints               0.3              py39h06a4308_0  
execnet                   1.8.0              pyhd3eb1b0_0  
expat                     2.2.10               he6710b0_2  
fontconfig                2.13.1               h6c09931_0  
freetype                  2.10.4               h5ab3b9f_0  
gau2grid                  2.0.7                hd18ef5c_0    psi4/label/dev
gcc_impl_linux-64         7.3.0                habb00fd_1  
gcc_linux-64              7.3.0               h553295d_15  
gcp                       2.0.2                he991be0_2    psi4/label/dev
gdma                      2.2.6                h0e1e685_6    psi4/label/dev
geometric                 0.9.7.2                    py_0    conda-forge
gfortran_impl_linux-64    7.3.0                hdf63c60_1  
gfortran_linux-64         7.3.0               h553295d_15  
glib                      2.68.2               h36276a3_0  
gmp                       6.2.1                h2531618_2  
gst-plugins-base          1.14.0               h8213a91_2  
gstreamer                 1.14.0               h28cd5cc_2  
gxx_impl_linux-64         7.3.0                hdf63c60_1  
gxx_linux-64              7.3.0               h553295d_15  
hdf5                      1.10.6               hb1b8bf9_0  
icu                       58.2                 he6710b0_3  
importlib-metadata        3.7.3            py39h06a4308_1  
importlib_metadata        3.7.3                hd3eb1b0_1  
importlib_resources       5.1.2            py39h06a4308_1  
iniconfig                 1.1.1              pyhd3eb1b0_0  
intel-openmp              2021.3.0          h06a4308_3350  
ipykernel                 5.3.4            py39hb070fc8_0  
ipython                   7.22.0           py39hb070fc8_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                7.6.3              pyhd3eb1b0_1  
isort                     5.8.0              pyhd3eb1b0_0  
jedi                      0.17.2           py39h06a4308_1  
jinja2                    3.0.0              pyhd3eb1b0_0  
jpeg                      9b                   h024ee3a_2  
jsonschema                3.2.0                      py_2  
jupyter                   1.0.0            py39h06a4308_7  
jupyter_client            6.1.12             pyhd3eb1b0_0  
jupyter_console           6.4.0              pyhd3eb1b0_0  
jupyter_core              4.7.1            py39h06a4308_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1  
krb5                      1.18.2               h173b8e3_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libblas                   3.9.0           1_h6e990d7_netlib    conda-forge
libboost                  1.73.0              h3ff78a5_11  
libcurl                   7.71.1               h20c2e04_1  
libedit                   3.1.20210216         h27cfd23_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.5.0               ha8ba4b0_17  
libgfortran4              7.5.0               ha8ba4b0_17  
libgomp                   9.3.0               h5101ec6_17  
libint2                   2.6.0                hc9558a2_9    psi4/label/dev
liblapack                 3.9.0           3_h893e4fe_netlib    conda-forge
libpng                    1.6.37               hbc83047_0  
libsodium                 1.0.18               h7b6447c_0  
libssh2                   1.9.0                h1ba5d50_1  
libstdcxx-ng              9.1.0                hdf63c60_0  
libuuid                   1.0.3                h1bed415_2  
libuv                     1.40.0               h7b6447c_0  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.10               hb55368b_3  
llvm-openmp               11.1.0               h4bd325d_1    conda-forge
lz4-c                     1.9.3                h2531618_0  
markupsafe                2.0.1            py39h27cfd23_0  
mistune                   0.8.4           py39h27cfd23_1000  
mkl                       2021.3.0           h06a4308_520  
mkl-include               2019.4                      243  
mkl-service               2.4.0            py39h7f8727e_0  
mkl_fft                   1.3.0            py39h42c9631_2  
mkl_random                1.2.2            py39h51133e4_0  
more-itertools            8.7.0              pyhd3eb1b0_0  
mp2d                      1.1.0                hfd86e86_0    psi4/label/dev
mpfr                      4.0.2                hb69a4c5_1  
msgpack-python            1.0.2            py39hff7bd54_1  
mypy_extensions           0.4.3            py39hf3d152e_3    conda-forge
nbclient                  0.5.3              pyhd3eb1b0_0  
nbconvert                 6.0.7            py39h06a4308_0  
nbformat                  5.1.3              pyhd3eb1b0_0  
ncurses                   6.2                  he6710b0_1  
nest-asyncio              1.5.1              pyhd3eb1b0_0  
networkx                  2.5                        py_0  
nglview                   3.0.3              pyh8a188c0_0    conda-forge
ninja                     1.10.2           py39hff7bd54_0  
notebook                  6.4.0            py39h06a4308_0  
numpy                     1.20.3           py39hf144106_0  
numpy-base                1.20.3           py39h74d4b33_0  
openssl                   1.1.1k               h27cfd23_0  
optking                   0.1.0              pyh40295ff_6    psi4/label/dev
packaging                 20.9               pyhd3eb1b0_0  
pandoc                    2.12                 h06a4308_0  
pandocfilters             1.4.3            py39h06a4308_1  
parso                     0.7.0                      py_0  
pathspec                  0.8.1              pyhd3deb0d_0    conda-forge
pcmsolver                 1.2.1.1          py39h6d17ec8_2    psi4/label/dev
pcre                      8.44                 he6710b0_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pint                      0.17               pyhd8ed1ab_0    conda-forge
pip                       21.0.1           py39h06a4308_0  
pluggy                    0.13.1           py39h06a4308_0  
prometheus_client         0.11.0             pyhd3eb1b0_0  
prompt-toolkit            3.0.17             pyh06a4308_0  
prompt_toolkit            3.0.17               hd3eb1b0_0  
psutil                    5.8.0            py39h27cfd23_1  
ptyprocess                0.7.0              pyhd3eb1b0_2  
py                        1.10.0             pyhd3eb1b0_0  
py-boost                  1.73.0          py39ha9443f7_11  
py-cpuinfo                7.0.0                      py_0  
pyberny                   0.6.3                    pypi_0    pypi
pybind11-headers          2.6.2                hfc4b9b4_0    psi4/label/dev
pycparser                 2.20                       py_2  
pydantic                  1.8.2            py39h27cfd23_0  
pygments                  2.9.0              pyhd3eb1b0_0  
pyparsing                 2.4.7              pyhd3eb1b0_0  
pyqt                      5.9.2            py39h2531618_6  
pyrsistent                0.17.3           py39h27cfd23_0  
pytest                    6.2.2            py39h06a4308_2  
pytest-forked             1.3.0              pyhd3eb1b0_0  
pytest-xdist              2.2.1              pyhd3eb1b0_0  
python                    3.9.2                hdb3f193_0  
python-dateutil           2.8.1              pyhd3eb1b0_0  
python_abi                3.9                      1_cp39    conda-forge
pyyaml                    5.4.1            py39h27cfd23_1  
pyzmq                     20.0.0           py39h2531618_1  
qcelemental               0.20.0+4.gef72ac1.dirty           dev_0    <develop>
qcengine                  0.19.0+21.g40ca605.dirty           dev_0    <develop>
qt                        5.9.7                h5867ecd_1  
qtconsole                 5.1.0              pyhd3eb1b0_0  
qtpy                      1.9.0                      py_0  
readline                  8.1                  h27cfd23_0  
regex                     2021.3.17        py39h27cfd23_0  
rhash                     1.4.1                h3c74f83_1  
send2trash                1.5.0              pyhd3eb1b0_1  
setuptools                52.0.0           py39h06a4308_0  
simint                    0.7                  h642920c_1    psi4/label/dev
sip                       4.19.13          py39h2531618_0  
six                       1.15.0           py39h06a4308_0  
sqlite                    3.35.2               hdfb4753_0  
terminado                 0.9.4            py39h06a4308_0  
testpath                  0.4.4              pyhd3eb1b0_0  
tk                        8.6.10               hbc83047_0  
toml                      0.10.2             pyhd3eb1b0_0  
tornado                   6.1              py39h27cfd23_0  
traitlets                 5.0.5              pyhd3eb1b0_0  
typed-ast                 1.4.2            py39h27cfd23_1  
typing-extensions         3.7.4.3              hd3eb1b0_0  
typing_extensions         3.7.4.3            pyh06a4308_0  
tzdata                    2020f                h52ac0ba_0  
versioneer                0.19               pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1            py39h06a4308_1  
wheel                     0.36.2             pyhd3eb1b0_0  
widgetsnbextension        3.5.1            py39h06a4308_0  
xtb                       6.3.3                h323e27b_1    conda-forge
xtb-python                20.2             py39hbd71b63_2    conda-forge
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h7b6447c_0  
zeromq                    4.3.4                h2531618_0  
zipp                      3.4.1              pyhd3eb1b0_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.5                h9ceee32_0  
```

> It seems that the input file in https://github.com/psi4/psi4/blob/master/samples/fsapt1/input.dat and https://psicode.org/psi4manual/master/fisapt.html#f-sapt-a-representative-example has no differences

The manual example has unphysical singlets (`0 1`) for the OH fragments. The correct tests/ and samples/isapt2 has doublets (`0 2`). Could isapt2 vs fsapt2 be the confusion?

**Comment by VincenzoChen** [comment]
> Could isapt2 vs fsapt2 be the confusion?
I think it is not because of this reason. I check the input file for isapt and faspt,respectively. The calculation I want to do is F-SAPT. But it reported error. But the example you test is I-SAPT. So I also tested the I-SAPT example but also got such error.

**Comment by loriab** [comment]
It seems unlikely a numpy interface would change.

You might try running one of the tests that runs `fsapt.py`  internally like `fsapt-terms`. You'll have to move the fsapt.py file to the launch directory or hardwire its path in the test. If your numpy error shows up there, I'd believe numpy or env problem.

**Comment by VincenzoChen** [comment]
I have tried these two ways you said before and it didn't work.

**Comment by VincenzoChen** [comment]
[test.tar.gz](https://github.com/psi4/psi4/files/7019263/test.tar.gz)
Here I uploaded my input and result for I-SAPT example. Maybe you can help to test them to see wheter there is any error in my environment.

**Comment by loriab** [comment]
Your input runs cleanly for me. I notice you're running psi v1.3, so you might try using fsapt.py from master https://github.com/psi4/psi4/blob/master/psi4/share/psi4/fsapt/fsapt.py and/or updating psi4 itself to the nightly build or v1.4

**Comment by JonathonMisiewicz** [comment]
Using `fsapt.py` from master is more likely to be the _cause_ of the bug than the solution. The original report had matrix shapes that were off by one. That's exactly what I'd expect when using data computed with 1.3 with the `fsapt.py` file from 1.4, thanks to the way #2131 implemented electrostatic embedding.

**Comment by VincenzoChen** [comment]
>Using fsapt.py from master is more likely to be the cause of the bug than the solution. The original report had matrix shapes that were off by one. That's exactly what I'd expect when using data computed with 1.3 with the fsapt.py file from 1.4, thanks to the way #2131 implemented electrostatic embedding.

Thanks. I have solve the problem.
