### ISSUE TITLE
`detci` ex_level keyword KeyError

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#2282]
The following input file crashes
```
molecule {
F
F 1 1.4613
}

set freeze_core true
set basis cc-pvdz
set detci ex_level 5 

energy('ci')
```

Traceback:
```
Traceback (most recent call last):
  File "/opt/psi/4/master/bin/psi4", line 331, in <module>
    exec(content)
  File "<string>", line 28, in <module>
  File "/opt/psi/4/master/lib/psi4/driver/driver.py", line 570, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/opt/psi/4/master/lib/psi4/driver/procrouting/proc.py", line 3600, in run_detci
    level = kwargs['level']

KeyError: 'level'
```

If this isn't intended usage, we need to update docs.

**Comment by loriab** [comment]
did you happen to try something like below? iirc, `"detci"` is intended to trigger the specify-everything-by-detci-keyword mode that makes detci behave like psi3.

```
set detci ex_level 5

energy("detci")
```

**Comment by JonathonMisiewicz** [comment]
That computation runs, thanks.

Is there a reason that `detci` and `ci` mean different things? I'm not sure if this is a docs issue or an API issue.

**Comment by loriab** [comment]
The ccenergy & detci shortcuts are basically there for the small subset of users (maybe 2) who know psi3 better than psi4 and for debugging. They were faintly documented here https://github.com/psi4/psi4/blob/master/psi4/driver/procrouting/proc_table.py#L103-L117 (first and last lines) but not advertised since it didn't match the psi4 philosophy of specific method.

The `ex_level` wasn't intended to be used directly. Is it `energy("ci5")` that you're after? detci can do so many arbitrary orders (inefficiently) that we didn't want to clutter up the procedures dict (this was pre-dft days).

**Comment by JonathonMisiewicz** [comment]
Yes, `ci5` was what I was after.

This sounds more and more like a documentation issue. I had no idea `ci5` existed, and short of reading the source code, I can't know how I was _supposed_ to know. I can't find this mentioned anywhere in docs. I still don't know which keywords are supposed to work with `ci` mode and which in `detci` mode.
