### ISSUE TITLE
How to run fsapt on system that contains iodine?

### ISSUE THREAD

**Issue by VincenzoChen** [psi4/psi4#2291]
As the title stated, I want to perform fsapt calculation on a system that contains iodine atoms. At the begining I used the aug-cc-tzvp but it didn't contain the parameter for iodine.So I use the basis set def2-tzvp which contains the parameter for iodine. But when I run the calculation, it sent out such error message:
```
Traceback (most recent call last):
  File "/pubhome/zchen02/miniconda3/envs/psi4/bin/psi4", line 287, in <module>
    exec(content)
  File "<string>", line 141, in <module>
  File "/pubhome/zchen02/miniconda3/envs/psi4/lib//python3.7/site-packages/psi4/driver/driver.py", line 556, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/pubhome/zchen02/miniconda3/envs/psi4/lib//python3.7/site-packages/psi4/driver/procrouting/proc.py", line 3631, in run_fisapt
    core.get_global_option("MINAO_BASIS"))
  File "/pubhome/zchen02/miniconda3/envs/psi4/lib//python3.7/site-packages/psi4/driver/p4util/python_helpers.py", line 80, in _pybuild_basis
    mol.to_dict(), key, resolved_target, fitrole, other, return_dict=True, return_atomlist=return_atomlist)
  File "/pubhome/zchen02/miniconda3/envs/psi4/lib//python3.7/site-packages/psi4/driver/qcdb/libmintsbasisset.py", line 679, in pyconstruct
    verbose=verbose)
  File "/pubhome/zchen02/miniconda3/envs/psi4/lib//python3.7/site-packages/psi4/driver/qcdb/libmintsbasisset.py", line 897, in construct
    (at + 1, key, text2))

psi4.driver.qcdb.exceptions.BasisSetNotFound: BasisSet::construct: Unable to find a basis set for atom 106 for key BASIS among:
  Shell Entries: ['I']
  Basis Sets: [('CC-PVTZ-MINAO', 'CC-PVTZ-MINAO', None)]
```
Is there any method to solve this problem?

**Comment by PeterKraus** [comment]
Please, can you provide an input file?

Anyway, I think the problem here is that in the IBO localization procedure, one uses a different basis set than for the whole calculation - and the minimal atomic orbital basis set `cc-pvtz-minao` likely doesn't have definitions for iodine. You can override the default by setting the `minao_basis` keyword to something that's defined for iodine. I would imagine that with an overall `def2-tzvp` basis set, you'd still want to use the same ECP for the localization procedure, so try with `set minao_basis def2-svp`. This makes a calculation including iodine complete without crashing on my PC, but whether the results are physical, I cannot tell.

@loriab: Note that the tutorial video mentioned [here](https://psicode.org/psi4manual/master/fisapt.html#f-i-sapt-keywords) is not accessible.

**Comment by JonathonMisiewicz** [comment]
There's not much we can do without an input file. Closing.
