### ISSUE TITLE
Packages on conda-forge

### ISSUE THREAD

**Issue by mattwthompson** [psi4/psi4#2300]
Hi Psi4 developers,

I'd like to open discussion on making Psi4 packages on `conda-forge`. We at OpenFF have some projects that make heavy use of Psi4 and that we'd like to roll out to production alongside a pretty length list of other packages. Unfortunately, one or of our other dependencies is a somewhat monolithic and tangled web of FORTRAN and legacy code that regularly produces conflicts on macOS and sometimes causes deployment issues on Linux. (Others may have more comments on other deployment issues). We've been able to [resolve this](https://github.com/psi4/psi4/issues/2024) in the past, and we've also filled up the packaging channel on Slack on more than a few occasions. However, it may be more sustainable in the long run (for us and presumably other users) if we can get conda packaging for the Psi4 stack moved over to `conda-forge` - something we'd be happy to take a role in.

* **Would this be useful for Psi4 developers and/or users?** I have personally had good experiences with migrations, both as a developer/maintainer and user. Getting everything on one channel (and using `conda-forge`'s existing automation) should help with dependency resolution/compatibility and in principle should also make build processes smoother. It would unblock some production issues with our software and be generally valuable for us - but we absolutely don't want to make life harder on for Psi4 developers/maintainers.
* **What technical blockers exist?** In the past we have gotten over some large hurdles (migrating OpenMM included contributing a recipe for CUDA toolkits) and more tedious blockers (migrating the OpenFF stack involved contributing something like 10-20 separate packages, piece by piece). `conda-forge` has [some tooling](https://conda-forge.org/docs/maintainer/knowledge_base.html#using-cmake) built around CMake, including MKL and some number of compilers. (Sorry - I'm not really an expert in packaging compiled code so I can't say much more about this - others may chime in!). But I don't know if there are insurmountable blockers to this process, or if that's been explored recently.
* **What can we do to help?** We have a significant amount of person-time available to contribute from people with experience contributing and maintaining packages on `conda-forge`. If needed, we are likely able to pull in further resources to get support from people with vastly more conda-related expertise than myself, including `conda-forge` core team members. 

I presume this has been discussed in the past, but I could not find a stub issue nor [earlier attempts](https://github.com/conda-forge/staged-recipes/pulls?q=is%3Apr+is%3Aclosed+psi4) at doing this.

cc: @SimonBoothroyd @dotsdl @j-wags @jthorton

**Comment by loriab** [comment]
This won't be a comprehensive reply, just a getting-started one.

In the beginning, there were lots o' blockers:
* no mkl
* no c++11
* no intel compiler capability for multiarch packages
* psi4 has dependencies that aren't quite vanilla upstream
* psi4 likes to provide addons from projects that aren't released cleanly
* psi4 users have grown accustomed to `-c psi4` and `-c psi4/label/dev`
* we like packages to be least restrictive so that devs can use conda like a package manager and build with their own tooling

That said, many of those blockers have receded, and Windows psi4 is, in fact, c-f -based.
* mkl is in for several years
* c-f gcc is plenty ahead of where psi needs it
* intel is becoming more integral and _maybe_ we could still user multiarch instead of the uniform c-f flag set
* gau2grid and libxc dependencies are now good wrt upstream and are packaged on c-f for L/M/W. (for gau2grid, the c-f Linux package had to have an optimization turned off, weirdly.) (for libxc, I think the only Linux downgrade was the multiarch, but I don't remember exactly)
* a lot of the psi4 addons aren't fast-moving anymore, so they can be pressed into minting a stable version. or we can patch in the recipe.
* users can adapt to -c c-f for releases and -c psi4 for nightly builds and dev helpers

Moving psi4 releases to c-f has been a low-simmering goal of mine for a while, so you'll only get technical objections from me :-)

That said, there's a lot of work involved. About 24 of these recipes are active, https://github.com/psi4/psi4meta/tree/master/conda-recipes . They're not all required to get a minimal psi4 package, but most would be needed to complete the migration.

But that's just work :-)
The big, multidimensional technical hurdle is libint2, a required dependency.
* I adapted their buildsys for cmake, then the developer adapted that further, but then I was busy and haven't re-reconciled it with psi4. There has never been a release or even a commit on master that works with psi4.
* There is already a libint2 package on c-f, but it has only plain integrals, not derivative ints, and is built with autotools.
* Psi uses a different integral ordering than every other open-source QC package, and this is a *compile-time* option, not a run-time option https://github.com/evaleev/libint/issues/190 That is, no single build of libint2 could work for all the downstreams on c-f that want to use it. (It could be worse -- in integral package land, there's also commonly source-generation-time options :-)
* the production-level Linux libint2 package has 26k source files, takes way more than 6h to build running on 12 cores, and needs `ulimit` reset on the building computer to complete
* Windows libint2 package has only ever been built on @andysim 's laptop. I worry that between the careful choice of compiler he had to make and the clang-cl details that something would conflict with c-f's locked-down build tooling. Of course we get away with this now because libint2 gets pulled along with psi from `-c psi4`.

I've read some of those threads that it took to get OpenMM GPU code working at production grade on c-f, and I judge that a bigger hurdle than libint2. But libint2 is formidable nonetheless.

Glad to talk further, though I don't think I have blocks of time to actually work on this this year. Thanks for using psi4 enough to want cleaner environments!

**Comment by mattwthompson** [comment]
Thanks for the detailed reply! It looks like this is a tall task but not impossible. I'll let this stew for a few days so others can assess both the existing recipes and the libint2 issues.

A small detail on our end that I should have mentioned from the gate is that we don't prioritize packaging on Windows, though it seems like Psi4 has some Windows users.

**Comment by jturney** [comment]
There are not many places internal to Psi4 that need to really know the ordering of our orbitals. So perhaps us changing to match default libint2 wouldn't be too big a hurdle. Do any of our up or downstream packages need to know the ordering?

**Comment by loriab** [comment]
> There are not many places internal to Psi4 that need to really know the ordering of our orbitals. So perhaps us changing to match default libint2 wouldn't be too big a hurdle. Do any of our up or downstream packages need to know the ordering?

* fwiw, none of our ecosystem packages use libint directly
* gau2grid is aware of ordering, but it's runtime setable
* reading Andy's comment into the record https://github.com/evaleev/libint/issues/190#issuecomment-691482710

**Comment by loriab** [comment]
I had put this together as I was building v1.4, so may as well share here.

### `psi4`

project | req'd | linux | osx | win | noarch | lang
-----|-----|-----|-----|-----|-----|-----
libint2 | yes | psi4 | psi4 | psi4 | | C++
libxc | yes | psi4 | psi4 | c-f | | C
gau2grid | yes | psi4 | psi4 | c-f | | C
qcelemental | yes | | | | psi4 copied from c-f | Py
qcengine | yes | | | | psi4 copied from c-f | Py
ambit | no | psi4 | psi4 | --- | | C++
chemps2 | no | psi4 | psi4 | --- | | C++
dftd3 | no | psi4 | psi4 | psi4 | | Fortran
dkh | no | psi4 | psi4 | --- | | Fortran
gcp | no | psi4 | psi4 | psi4 | | Fortran
gdma | no | psi4 | psi4 | --- | | Fortran
pcmsolver | no | psi4 | psi4 | --- | | C++, Fortran
simint | no | psi4 | psi4 | --- | | C++

* not req'd means present in Linux conda package but not required for a minimal conda package
* gcp should switch to mctc-gcp already on c-f for L but needs a MKL build
* gdma is a little behind in releases b/c psi actually uses a home-adapted library instead of the executable
* pcmsolver latest (v1.3, I think) can't work with psi4 after core-developer of both gave a medium-effort try. But there's a slight problem with previous release v1.2, too, so psi4 uses an unpublished v1.2.1.1 (or something like that). a patch in the conda-recipe from v1.2.1 upstream is probably the better sol'n
* simint is peculiar in that you need to choose a target instruction set at compile time. usual psi default may not be general enough for c-f

### `psi4-rt`

project | req'd | linux | osx | win | noarch | lang
-----|-----|-----|-----|-----|-----|-----
libtensorlight | no | psi4 copied from adcc | psi4 copied from adcc | --- | | C++
 adcc | no | psi4 copied from adcc | psi4 copied from adcc |  --- | | C++
fockci | no | | | | psi4 | Py
mp2d | no | psi4 | psi4 | --- | | C++
openfermion | no | | | | psi4 | Py
openfermionpsi4 | no | | | | psi4 | Py
pycppe | no | psi4 | psi4 | --- | | C++
pylibefp | no | psi4 | psi4 | --- | | C++
libefp | no | psi4 | psi4 | --- | | C
resp | no | | | | psi4 | Py
snsmp2 | no | | | | psi4 | Py
v2rdm_casscf | no | psi4 | psi4 | --- | | C++, Fortran

* openfermion is better housed on c-f anyways. devs are willing (I have an open issue on this with them). only issue is that they have several optional dependencies, and their test suite fails rather than skipping the tests that need these.
* pycppe also on c-f already
* pylibefp and libefp built together
* v2rdm_casscf is a psi4 plugin and has no meaningful pinning to psi4 itself as it often needs rebuilding when psi4 innards change

**Comment by mattwthompson** [comment]
So as to not ping everybody in this thread every time I've done some little thing, I'm tracking my current progress on porting upstreams here: https://github.com/mattwthompson/mattwthompson/projects/1

**Comment by JonathonMisiewicz** [comment]
It's worth mentioning that we are hoping to [switch the DFTD3 version](https://github.com/psi4/psi4/issues/2360) we use to one that, incidentally, is already on conda-forge.

**Comment by awvwgk** [comment]
I started rebuilding our stack (`gcp`, `dftd4`, `s-dftd3`, ...) for Windows on conda-forge (just recently rebuild the whole thing for OSX/Arm64). Let's see how far I can get, `gcp` went through smooth already, not sure how easy the Python extension modules will be.

If anyone can give me some pointers on https://github.com/MolSSI/QCEngine/issues/341 I can also make the first step to resolve https://github.com/psi4/psi4/issues/2360.

**Comment by mattwthompson** [comment]
I'm no longer able to take this on myself - however I'm happy to contribute if somebody would like to accept the torch.

**Comment by loriab** [comment]
I've been starting to work on this now that we have a Libint2 strategy. Tracker here: https://github.com/orgs/psi4/projects/2/views/1

**Comment by loriab** [comment]
Packages are ticking along steadily (follow graphs/views/labels at tracker above). If anyone wants to try out very early versions of the psi4 package, you can download artifacts from a commit that works at https://github.com/conda-forge/staged-recipes/pull/22328

**Comment by hadim** [comment]
Thanks. That's great news!

Are you planning to support linux, osx and windows?

I am happy to test the package on my side. Do you know how I can download the conda forge artifacts from your PR on staged-recipes?

**Comment by mattwthompson** [comment]
The artifacts are available on Azure if you click through the status checks

**Comment by loriab** [comment]
* Yes, eventually will support `linux-64`, `osx-64`, `osx-arm64`, `win-64` arch. staged-recipes won't have osx-arm64, though.
* Still TBD if Windows psi4 packages will include Fortran addons like dkh, gdma, pcmsolver.
* All arch will be explicitly linked to MKL (that is, `libblas=*=*mkl`). dependencies that themselves need blas/lapack are getting linked generically so runtime selection is an option, but psi4 itself is getting fixed to MKL. I'm open to someday linking psi4 generically, but I think other distributions need to be tested and any performance and oversubscription issues addressed first.
* yes, as Matt says, you have to dig around on Azure, find "artifacts", download, and then can install locally (or upload to a separate anaconda.org acct).

**Comment by hadim** [comment]
I tested the psi4 package on `lenux-64` using the staged-recipes artifacts and it works perfectly. The tests were performed on an in-house QM package and I only did a single point gradient computation on a single and simple molecule.

Two things maybe:

- I add to use the `conda-forge/label/libint_dev` channel for libint.
- Upon importing `psi4` I noticed a bunch of prints that wasnt here before:

```
psi4_module_loc='/home/hadim/conda_envs/lib/python3.9/site-packages/psi4'
pymod='/python3.9/site-packages/lib/psi4'
pymod_dir_step='../../../..'
data_dir='/home/hadim/conda_envs/lib/python3.9/site-packages/psi4/../../../../share/psi4'
executable='/home/hadim/conda_envs/bin/psi4'
executable='/home/hadim/conda_envs/bin/psi4'
data_dir='/home/hadim/conda_envs/lib/python3.9/site-packages/psi4/../../../../share/psi4'
data_dir='/home/hadim/conda_envs/share/psi4'
```

Is it coming from package development, and you'll remove it moving forward?

**Comment by loriab** [comment]
> I add to use the conda-forge/label/libint_dev channel for libint.

Yes, that's going to be the case for the foreseeable future until https://github.com/evaleev/libint/pull/259 gets reviewed and merged and released, as I can't in good conscience replace a released version with a PR version outside the psi4 channel.

> Upon importing psi4 I noticed a bunch of prints that wasn't here before:

You guessed correctly -- I'm trying to debug some infernal Windows relative path behavior.

> I tested the psi4 package on linux-64 using the staged-recipes artifacts and it works perfectly. 

Great, good to hear!

------

Note to anyone reading this thread seeking Mac packages: most of the iterations I skip Mac, so look for a CI run that took a long time.

**Comment by hadim** [comment]
> Yes, that's going to be the case for the foreseeable future until https://github.com/evaleev/libint/pull/259 gets reviewed and merged and released, as I can't in good conscience replace a released version with a PR version outside the psi4 channel.

Ok no problem and I understand your point. Would that prevent you from merging psi4 in staged-recipes before that?

**Comment by loriab** [comment]
>> Yes, that's going to be the case for the foreseeable future until https://github.com/evaleev/libint/pull/259 gets reviewed and merged and released, as I can't in good conscience replace a released version with a PR version outside the psi4 channel.

> Ok no problem and I understand your point. Would that prevent you from merging psi4 in staged-recipes before that?

I don't think it should be a problem; there's no software barrier to merging, and I think I have good arguments if there's reviewer concerns. Possibly I'll try to arrange to merge psi4 from staged-recipes into a `conda-forge/label/psi4_dev` channel so there isn't a funny psi4 `v1.8a1.dev80` around.

**Comment by loriab** [comment]
Ok, we're up on c-f at https://anaconda.org/conda-forge/psi4/files . For now, you'll need `conda install psi4 -c conda-forge -c conda-forge/label/libint_dev -c conda-forge/label/psi4_dev`. After the v1.8 release, you can drop the `psi4_dev` but not the `libint_dev`.

It'll be changing often as I need to add osx_arm64 and py311. And there's stuff in master it doesn't have, and stuff in it that master doesn't have. But all the main functionality should be fine.

### Please report *any* problems or oddities.

None of the docs reflect new build/install procedures yet. I'll be making a list of where folks go awry. First one (that's bitten me and Jonathon):
* To start an environment with conda compilers from c-f, don't use `conda create -n mydev gxx_linux-64 ... -c conda-forge` as the c-f analog to the usual procedure. That will work to form the env, but if you look in `conda list`, there's some deep pieces like the sysroot still present from `defaults`. When you start compiling, it will give you obscure C++ errors outside your code. Instead, use `conda create -n mydev cxx-compiler ... -c conda-forge` (same for all platforms) which will give a cohesive compiler stack.

**Comment by hadim** [comment]
@loriab I tested the new c-f packages and the conda dep solving just works out of the box (even in a complex and large conda env). So far all my test suite (single point energy) works perfectly. Thanks again for the effort!

On my side, I think that issue can be closed.

**Comment by loriab** [comment]
Thanks, @hadim, great to hear, and thanks for testing!

General update:
* I've downloaded one of the Linux packages and run full tests, and they all passed. Not much ecosystem activated, though.
* py311 packages are ready, but `osx_arm64` are not.

**Comment by loriab** [comment]
There's a rebuild of all the psi4 packages up (build `_2`) including `osx_arm64`.

* **Please test `osx_arm64`**. These are build by cross-compile and in a direction that can't be emulated, so they have _never been run_. 
* You can run the full test suite through pytest. Point it at `pytest $CONDA_PREFIX/lib/python*/site-packages/psi4/tests/`. Especially test threaded (but be aware of #2941 expected failures (also cc44, but that's behaving correctly to fail)).
* Be aware that c-f encourages packages to be built against a generic blas/lapack, so the user can select the blas implementation at runtime. (directions at https://conda-forge.org/docs/maintainer/knowledge_base.html#switching-blas-implementation)
* Usual archs `linux-64`, `osx-64`, `win-64` _don't_ do as encouraged above and instead link directly to MKL since we didn't want to switch expectations and performance that drastically. But Intel MKL isn't available for `osx-arm64` (quelle suprise). So I did the generic blas/lapack setup for this arch. You can choose `libblas=*=*openblas` or `libblas=*=*accelerate` for this arch. I'd be curious to hear about both. You'll get openblas if you don't specify.
* I've tested openblas on linux-64, and as long as you choose the openmp openblas variant, not the pthreads one, it works correctly (only the openmp variant is available for `osx-arm64`, so all's well). Timings were ~5% slower over MKL, so operable and perfectly respectable. I didn't test the SAPT jobs that iirc were the trouble with openblas before.

**Comment by hadim** [comment]
I haven't tested locally but `-c conda-forge/label/psi4_dev` does not seem to be mandatory because 1.8 is now in `main` at https://github.com/conda-forge/psi4-feedstock/tree/main.

But `-c conda-forge/label/libint_dev` still seems to be required.

Do you confirm @loriab?

**Comment by loriab** [comment]
Exactly so, @hadim. psi4 has a c-f-compatible release, so that's on the `main` feedstock branch and accessible with `-c conda-forge`. _But_ psi4 still needs a unreleased libint branch, so that's packaged from the `dev` feedstock branch, so altogether, it's `conda install psi4 -c conda-forge/label/libint_dev -c conda-forge`.

The long-term reference for the current channel path is https://psicode.org/installs/latest/ with selections (any os)-conda-(any py)-stable.

**Comment by GregorySchwing** [comment]
This whole thread was very useful.  I was able to create a conda environment with the latest psi4, openff-toolkit, and openff-recharge using this yml

The only thing not really mentioned in this thread, or the psicode latest installation is pinning pydantic version 1.x.  I was getting this error 
```
`
__pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__) TypeError: Array.validate_type() takes 2 positional arguments but 3 were given`
```

from this line of code in my example ( i believe it, recharge may need to pin pydantic 1.x)

```
    from openff.recharge.esp.storage import MoleculeESPRecord
    qc_data_record = MoleculeESPRecord.from_molecule(
        openff_mol_3D, conformer=conformer, grid_coordinates=grid, esp=esp, electric_field=None, esp_settings=qc_data_settings
    )
```

```

name: psi4
channels:
  - conda-forge
  - conda-forge/label/libint_dev
dependencies:
  - conda-forge::psi4>=1.8.2
  - conda-forge::openff-toolkit
  - conda-forge::openff-recharge
  - conda-forge::pydantic<2

```

**Comment by loriab** [comment]
Thanks for the report, @GregorySchwing. Is there any chance you've got qcportal or qcfractal installed? I ask because psi4 itself should be pydantic v2-tolerant (that is, psi4 imports the v1 API from v2), while qcfractal won't be until the v0.52 release. But that's in theory. In practice, I haven't tested lately with v2, and pydantic is moving quickly and is widely used, so it might be safer to pin it.

**Comment by GregorySchwing** [comment]
It's an openff-recharge requirement, but since openff/psi4 compatability was what caused Matt to initiate this thread, I thought I'd mention it along with a working yml.

```
Traceback (most recent call last):
  File "/home/greg/RIZZ/test2.py", line 95, in <module>
    qc_data_record = MoleculeESPRecord.from_molecule(
  File "/home/greg/conda/envs/psi4_2/lib/python3.10/site-packages/openff/recharge/esp/storage/_storage.py", line 141, in from_molecule
    return MoleculeESPRecord(
  File "/home/greg/conda/envs/psi4_2/lib/python3.10/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
TypeError: Array.validate_type() takes 2 positional arguments but 3 were given
```
Here is the problem code, requiring pydantic 1.x.

```

    @classmethod
    def from_molecule(
        cls,
        molecule: "Molecule",
        conformer: unit.Quantity,
        grid_coordinates: unit.Quantity,
        esp: unit.Quantity,
        electric_field: Optional[unit.Quantity],
        esp_settings: ESPSettings,
    ) -> "MoleculeESPRecord":
        """Creates a new ``MoleculeESPRecord`` from an existing molecule
        object, taking care of creating the InChI and SMARTS representations.

        Parameters
        ----------
        molecule
            The molecule to store in the record.
        conformer
            The coordinates [Angstrom] of this conformer with shape=(n_atoms, 3).
        grid_coordinates
            The grid coordinates [Angstrom] which the ESP was calculated on
            with shape=(n_grid_points, 3).
        esp
            The value of the ESP [Hartree / e] at each of the grid coordinates
            with shape=(n_grid_points, 1).
        electric_field
            The value of the electric field [Hartree / (e . a0)] at each of
            the grid coordinates with shape=(n_grid_points, 3).
        esp_settings
            The settings used to generate the ESP stored in this record.

        Returns
        -------
            The created record.
        """

        tagged_smiles = molecule.to_smiles(
            isomeric=True, explicit_hydrogens=True, mapped=True
        )

        return MoleculeESPRecord(
            tagged_smiles=tagged_smiles,
            conformer=conformer,
            grid_coordinates=grid_coordinates,
            esp=esp,
            electric_field=electric_field,
            esp_settings=esp_settings,
        )

```

**Comment by mattwthompson** [comment]
That looks like a problem in OpenFF Recharge (unlike most of our other packages, that one is used a little bit less externally so it hasn't been updated for the Pydantic v1/v2 import guards). I'll fix it there
