### ISSUE TITLE
MRCC interface broken with MRCC 2022 release

### ISSUE THREAD

**Issue by TiborGY** [psi4/psi4#2497]
MRCC-related CTests pass with an older version (2019 with some unknown patches) of MRCC, but the 2022 release broke the interface (again?).
For what its worth, it also no longer works with Molpro 2015.

```
(p4dev) gytibor@CRD-MILAN-3:~/psi4/objdir$ ctest -L mrcc -j`getconf _NPROCESSORS_ONLN` --rerun-failed --output-on-failure
Test project /home/gytibor/psi4/objdir
    Start 499: mrcc-ccsdt
    Start 500: mrcc-ccsd_t_
    Start 501: mrcc-ccsdt_q_
    Start 502: mrcc-rohf_ccsdt_q_
    Start 503: mrcc-optfreq
1/5 Test #499: mrcc-ccsdt .......................***Failed    0.62 sec
forrtl: No such file or directory
forrtl: severe (29): file not found, unit 75, file /tmp/mrcc_67625/KEYWD
Image              PC                Routine            Line        Source
dmrcc              0000000001284F08  Unknown               Unknown  Unknown
dmrcc              00000000012A12A2  Unknown               Unknown  Unknown
dmrcc              00000000004AE4BD  Unknown               Unknown  Unknown
dmrcc              0000000000507E55  Unknown               Unknown  Unknown
dmrcc              000000000040D9DD  Unknown               Unknown  Unknown
dmrcc              00000000004021AA  Unknown               Unknown  Unknown
dmrcc              0000000000400DF2  Unknown               Unknown  Unknown
dmrcc              00000000013571F9  Unknown               Unknown  Unknown
dmrcc              0000000000400CCA  Unknown               Unknown  Unknown
Traceback (most recent call last):
  File "/home/gytibor/psi4/objdir/stage/bin/psi4", line 333, in <module>
    exec(content)
  File "<string>", line 27, in <module>
  File "/home/gytibor/psi4/objdir/stage/lib/psi4/driver/driver.py", line 599, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/gytibor/psi4/objdir/stage/lib/psi4/driver/procrouting/proc.py", line 4732, in run_mrcc
    for line in open('iface'):

FileNotFoundError: [Errno 2] No such file or directory: 'iface'

Printing out the relevant lines from the Psithon --> Python processed input file:
        h 1 1.0 2 104.5
    ""","h2o")
    core.IO.set_default_namespace("h2o")
    core.set_global_option("BASIS", "cc-pvdz")
    core.set_global_option("FREEZE_CORE", "true")
--> energy('mrccsdt')
    compare_values(  8.801465529972, variable("NUCLEAR REPULSION ENERGY"), 6, 'NRE')
    compare_values(-76.021418445155, variable("SCF TOTAL ENERGY"), 6, 'SCF')
    compare_values( -0.204692406830, variable("MP2 CORRELATION ENERGY") , 6, 'MP2 correlation')
    compare_values( -0.217715210258, variable("CCSDT CORRELATION ENERGY"), 6, 'CCSDT correlation')
    compare_values(-76.239133655413, variable("CURRENT ENERGY"), 6, 'CCSDT')


!-----------------------------------------------!
!                                               !
!  [Errno 2] No such file or directory: 'iface' !
!                                               !
!-----------------------------------------------!
```

**Comment by hokru** [comment]
oh no, not again. Yes, one had to download patched files for the previous version from their homepage.

**Comment by TiborGY** [comment]
My hunch is that the interface is not "actually buggy", but that it was silently changed MRCC-side.

**Comment by JonathonMisiewicz** [comment]
> oh no, not again. Yes, one had to download patched files for the previous version from their homepage.

See [the issue about the 2020 release](https://github.com/psi4/psi4/issues/1866) for additional information on "the previous version" and Psi.

**Comment by TiborGY** [comment]
The issue has been reported to the MRCC forum. It is broken even with Molpro 2022.
Perhaps it would be more maintainable to teach QCEngine how to run standalone MRCC calculations, rather than trying to pass SCF wavefunctions via a fragile interface that keeps being broken?

**Comment by hokru** [comment]
QCEngine support would be great for a general interface and access to all the LNO and F12 goodies!

The PSI4 (and I suspect also ORCA and Molpro) interface is a bit different in the sense that those programs compute the integrals and hand them over to MRCC for arbitrary order CC(n) type of calculations. Dates back to when MRCC was essentially only doing that. 

Not sure how much use the (broken) 'classic' interface has.

**Comment by TiborGY** [comment]
The issue may have [just been fixed](https://www.mrcc.hu/index.php/forum/running-mrcc/287-molpro-w-mrcc-keywd-errror#1222) on the MRCC side.

**Comment by TiborGY** [comment]
Confirmed fixed with the latest patch files for MRCC.
