### ISSUE TITLE
Single cpu job fails in `qcengine/config.py` with `KeyError`

### ISSUE THREAD

**Issue by leifjacobson** [psi4/psi4#2548]
I'm running an wB97X-D3/def2-TZVP job which is failing with the following traceback:

```
Traceback (most recent call last):
  File "/home/jacobson/bin/psi4_wb97xd3_def2tzvp.py", line 73, in <module>
    main(sys.argv)
  File "/home/jacobson/bin/psi4_wb97xd3_def2tzvp.py", line 69, in main
    run_fxyz(args[1])
  File "/home/jacobson/bin/psi4_wb97xd3_def2tzvp.py", line 49, in run_fxyz
    grad = psi4.gradient(theory) 
  File "/home/jacobson/software/psi4conda/lib/python3.8/site-packages/psi4/driver/driver.py", line 675, in gradient
    return driver_cbs._cbs_gufunc(gradient, name, ptype='gradient', **kwargs)
  File "/home/jacobson/software/psi4conda/lib/python3.8/site-packages/psi4/driver/driver_cbs.py", line 1960, in _cbs_gufunc
    ptype_value, wfn = func(method_name, return_wfn=True, molecule=molecule, **kwargs)
  File "/home/jacobson/software/psi4conda/lib/python3.8/site-packages/psi4/driver/driver.py", line 716, in gradient
    wfn = procedures['gradient'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/jacobson/software/psi4conda/lib/python3.8/site-packages/psi4/driver/procrouting/proc.py", line 2420, in run_scf_gradient
    ref_wfn = run_scf(name, **kwargs)
  File "/home/jacobson/software/psi4conda/lib/python3.8/site-packages/psi4/driver/procrouting/proc.py", line 2325, in run_scf
    scf_wfn = scf_helper(name, post_scf=False, **kwargs)
  File "/home/jacobson/software/psi4conda/lib/python3.8/site-packages/psi4/driver/procrouting/proc.py", line 1543, in scf_helper
    disp_energy = scf_wfn._disp_functor.compute_energy(scf_wfn.molecule(), scf_wfn)
  File "/home/jacobson/software/psi4conda/lib/python3.8/site-packages/psi4/driver/procrouting/empirical_dispersion.py", line 210, in compute_energy
    jobrec = qcng.compute(
  File "/home/jacobson/software/psi4conda/lib/python3.8/site-packages/qcengine/compute.py", line 83, in compute
    config = get_config(local_options=local_options)
  File "/home/jacobson/software/psi4conda/lib/python3.8/site-packages/qcengine/config.py", line 308, in get_config
    raise KeyError("Number of jobs per node exceeds the number of available cores.")
KeyError: 'Number of jobs per node exceeds the number of available cores.'

```

This job is submitted on a SLURM cluster with the following script:
```
#!/bin/bash

#SBATCH --partition=compute-16core-64gb-preemptible
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --output=C2c_I2T_ACETAC_1_57_selected_nbody_1_clusters.slurm.out
#SBATCH --job-name=test-C2c_I2T_ACETAC_1_57_selected_nbody_1_clusters

source /home/jacobson/software/setup.psi4
export PSI_SCRATCH=/scratch/jacobson/
export OMP_NUM_THREADS=1
export MPI_NUM_THREADS=1
echo psi4 scratch set to $PSI_SCRATCH
fname=C2c_I2T_ACETAC_1_57_selected_nbody_1_clusters
python /home/jacobson/bin/psi4_wb97xd3_def2tzvp.py $fname".xyz" > $fname".log"
```

one cpu is available for the job.  I tracked the issue to qcengine/config.py which seems not to recognize my host and then set a default of 2 for jobs_per_node.  Then ncores / jobs_per_node is zero and a KeyError is raised.

**Comment by loriab** [comment]
Does `/home/jacobson/bin/psi4_wb97xd3_def2tzvp.py` contain a `qcng.compute()` call? May I see that file?

I don't run much through queues, so I don't have a feel for what qcng/config.py can/should pick up from the environment or host setup.

**Comment by leifjacobson** [comment]
Sure, here is the script:

```
import time
import sys
import os
import json

import psi4

def run_fxyz(fxyz, theory='wB97X-D3/def2-TZVP'):
    '''
    fxyz: absolute path to an xyz file
    '''
    elements, xyz = [], []
    with open(fxyz) as f:
        line = next(f)
        numb_atoms = int(line.split()[0])
        line = next(f)
        charge, multiplicity = map(int, line.split())
        for i in range(numb_atoms):
            line = next(f)
            elmnt, x, y, z = line.split() 
            elements.append(elmnt)
            xyz.append((float(x), float(y), float(z)))

    fxyz = os.path.basename(fxyz)
    base, ext = os.path.splitext(fxyz)

    name = base + '_wB97XD3_def2-TZVP'

    geom_string = '\n'.join(['%s %f %f %f' % (e, x, y, z) for e, (x, y, z) in zip(elements, xyz)])
    geom_string = str(charge) + ' ' + str(multiplicity) + '\n' + geom_string
    print("geom_string", geom_string)

    outfile = name + '.psi4'
    psi4.core.set_output_file(outfile, False)
    geom = psi4.geometry(geom_string)
    settings = {
        'scf_type': 'DF',
        'dft_basis_tolerance': 1e-10,
        'ints_tolerance': 1e-10,
        'dft_pruning_scheme':'robust',
        'S_ORTHOGONALIZATION': 'PARTIALCHOLESKY',
        'S_CHOLESKY_TOLERANCE': 1e-6,
        'wcombine': False,
    }
    psi4.set_options(settings)
    start_time = time.time()
    grad = psi4.gradient(theory) 
    psi4.core.print_variables()
    energy = psi4.variable("SCF TOTAL ENERGY")
    psi4.core.clean()
    jobtime = time.time() - start
    results = {
        "time": float(jobtime),
        "energy": energy,
        "gradient": grad
    }

    with open(name + ".json", "w") as fout:
        json.dump(results, fout, indent=4)

    print("Job %s completed in %.2f seconds with energy %.10f" % (base, jobtime, energy))

def main(args):
    assert args[1].endswith(".xyz")
    psi4.set_num_threads(1)
    run_fxyz(args[1])

if __name__ == '__main__':
    main(sys.argv)
```

**Comment by loriab** [comment]
## XYZ Files

Just as an aside, here's two easier ways to deal with molecules when you have the coordinates. chg/mult from the xyz are possible https://github.com/MolSSI/QCElemental/blob/master/qcelemental/molparse/from_string.py#L117-L136

tu1.py
```
import psi4

psi4.set_memory("600 mb")

### <<< Either 
#with open("h2o.xyz") as fp:
#    fh2o = fp.read()
#
#psi4.geometry(fh2o)

### --- Or

h2o = psi4.core.Molecule.from_arrays(elem=["O", "H", "H"], units="Angstrom", geom=[
          0.000000000000,     0.000000000000,    -0.065775570538, 
          0.000000000000,    -0.759061990794,     0.521953018295, 
          0.000000000000,     0.759061990794,     0.521953018295]) 
psi4.activate(h2o)

### >>> End

psi4.set_options({
    "basis": "cc-pVDZ",
})
psi4.energy('scf')

psi4.compare_values(-76.0266327341067125, psi4.variable('SCF TOTAL ENERGY'), 6, 'SCF energy')  #TEST
```

h2o.xyz
```
3
sdlkfs
O          0.000000000000     0.000000000000    -0.065775570538 
H          0.000000000000    -0.759061990794     0.521953018295 
H          0.000000000000     0.759061990794     0.521953018295 

```
## Single Core

To actually address your problem, can you try the following edits? If you edit the installed copy, no recompile needed.

Hopefully this solves it -- thanks for the report!
```
diff --git a/psi4/driver/procrouting/empirical_dispersion.py b/psi4/driver/procrouting/empirical_dispersion.py
index d23f016..ea4f79d 100644
--- a/psi4/driver/procrouting/empirical_dispersion.py
+++ b/psi4/driver/procrouting/empirical_dispersion.py
@@ -213,7 +213,7 @@ class EmpiricalDispersion(object):
                 resi,
                 self.engine,
                 raise_error=True,
-                local_options={"scratch_directory": core.IOManager.shared_object().get_default_path()})
+                local_options={"scratch_directory": core.IOManager.shared_object().get_default_path(), "ncores": core.get_num_threads()})
 
             dashd_part = float(jobrec.extras['qcvars']['DISPERSION CORRECTION ENERGY'])
             if wfn is not None:
@@ -231,7 +231,7 @@ class EmpiricalDispersion(object):
                     resi,
                     "gcp",
                     raise_error=True,
-                    local_options={"scratch_directory": core.IOManager.shared_object().get_default_path()})
+                    local_options={"scratch_directory": core.IOManager.shared_object().get_default_path(), "ncores": core.get_num_threads()})
                 gcp_part = jobrec.return_result
                 dashd_part += gcp_part
 
@@ -283,7 +283,7 @@ class EmpiricalDispersion(object):
                 resi,
                 self.engine,
                 raise_error=True,
-                local_options={"scratch_directory": core.IOManager.shared_object().get_default_path()})
+                local_options={"scratch_directory": core.IOManager.shared_object().get_default_path(), "ncores": core.get_num_threads()})
 
             dashd_part = core.Matrix.from_array(jobrec.extras['qcvars']['DISPERSION CORRECTION GRADIENT'])
             if wfn is not None:
@@ -296,7 +296,7 @@ class EmpiricalDispersion(object):
                     resi,
                     "gcp",
                     raise_error=True,
-                    local_options={"scratch_directory": core.IOManager.shared_object().get_default_path()})
+                    local_options={"scratch_directory": core.IOManager.shared_object().get_default_path(), "ncores": core.get_num_threads()})
                 gcp_part = core.Matrix.from_array(jobrec.return_result)
                 dashd_part.add(gcp_part)
 
```

your script needed a couple tweaks, so here's a working version:
```
import time
import sys
import os
import json

import psi4

def run_fxyz(fxyz, theory='wB97X-D3/def2-TZVP'):
    '''
    fxyz: absolute path to an xyz file
    '''
    elements, xyz = [], []
    with open(fxyz) as f:
        line = next(f)
        numb_atoms = int(line.split()[0])
        line = next(f)
        charge, multiplicity = map(int, line.split())
        for i in range(numb_atoms):
            line = next(f)
            elmnt, x, y, z = line.split() 
            elements.append(elmnt)
            xyz.append((float(x), float(y), float(z)))

    fxyz = os.path.basename(fxyz)
    base, ext = os.path.splitext(fxyz)

    name = base + '_wB97XD3_def2-TZVP'

    geom_string = '\n'.join(['%s %f %f %f' % (e, x, y, z) for e, (x, y, z) in zip(elements, xyz)])
    geom_string = str(charge) + ' ' + str(multiplicity) + '\n' + geom_string
    print("geom_string", geom_string)

    outfile = name + '.psi4'
    psi4.core.set_output_file(outfile, False)
    geom = psi4.geometry(geom_string)
    settings = {
        'scf_type': 'DF',
        'dft_basis_tolerance': 1e-10,
        'ints_tolerance': 1e-10,
        'dft_pruning_scheme':'robust',
        'S_ORTHOGONALIZATION': 'PARTIALCHOLESKY',
        'S_CHOLESKY_TOLERANCE': 1e-6,
        'wcombine': False,
    }
    psi4.set_options(settings)
    start_time = time.time()
    grad = psi4.gradient(theory) 
    psi4.core.print_variables()
    energy = psi4.variable("SCF TOTAL ENERGY")
    psi4.core.clean()
    jobtime = time.time() - start_time
    results = {
        "time": float(jobtime),
        "energy": energy,
        "gradient": grad.np.tolist()
    }
    print(f"{psi4.core.get_num_threads()=}")

    with open(name + ".json", "w") as fout:
        json.dump(results, fout, indent=4)

    print("Job %s completed in %.2f seconds with energy %.10f" % (base, jobtime, energy))

def main(args):
    assert args[1].endswith(".xyz")
    psi4.set_num_threads(1)
    run_fxyz(args[1])

if __name__ == '__main__':
    main(sys.argv)
```

## Psithon vs. QCSchema

Another aside -- your input is written as a python script containing a single job and dropping the key results to json. This could also run through QCSchema with json input and json output, either API like https://github.com/psi4/psi4/blob/master/tests/pytests/test_addons.py#L792-L819 or command-line. Let me know if you'd want more details.

**Comment by leifjacobson** [comment]
Thanks!  That seems to have done the trick.  Also thanks for the extra info and fixing the little bugs I would have encountered once I got psi4 to return.

**Comment by JonathonMisiewicz** [comment]
Developer-side, the remaining action item here is to add the local options flag in EmpiricalDispersion. Lori, I'm going to take a wild guess and say this will be part of DDD.

**Comment by loriab** [comment]
> Developer-side, the remaining action item here is to add the local options flag in EmpiricalDispersion. Lori, I'm going to take a wild guess and say this will be part of DDD.

I did get the idea from a different part of DDD, but the above diff is eligible for master. I'll include it in a PR soon.
