### ISSUE TITLE
issue restarting SCF from wavefunction file

### ISSUE THREAD

**Issue by ajs99778** [psi4/psi4#2571]
I'm trying to use the orbitals from one SCF as the guess for computations on similar structures. I'm trying to follow this procedure: [https://psicode.org/psi4manual/master/scf.html#restarting-the-scf](https://psicode.org/psi4manual/master/scf.html#restarting-the-scf)

I'm using Psi4 1.5 e9f4d6d on windows subsystem linux

The input file for the initial energy is:
```py
set_num_threads(8)
basis {
    assign    def2-SVP
}

molecule {
     0 1
     C        1.13408       -0.39513        0.82671
     C        0.24384       -0.10727        1.77918
     C        1.25947        0.48184       -0.37564
     C       -1.70320       -0.60897       -0.07371
     C       -1.08313        0.35853       -0.75350
     O        0.15798        0.21455       -1.28105
     H        1.61155       -1.37871        0.79725
     H       -0.00411       -0.81057        2.57479
     H       -0.26633        0.85763        1.80344
     H        2.16195        0.28247       -0.96305
     H        1.24281        1.54792       -0.09693
     H       -1.24645       -1.58985        0.04960
     H       -2.69979       -0.44218        0.33707
     H       -1.53347        1.35513       -0.87676
}

nrg, wfn = energy('M06-2X', return_wfn=True)
wfn.to_file("test_restart")
```

This creates a "test_restart.npy" file. I then try to compute the energy for the same molecule using this test_restart.npy file and a different input file:

```py
set_num_threads(8)
basis {
    assign    def2-SVP
}

molecule {
     0 1
     C        1.13408       -0.39513        0.82671
     C        0.24384       -0.10727        1.77918
     C        1.25947        0.48184       -0.37564
     C       -1.70320       -0.60897       -0.07371
     C       -1.08313        0.35853       -0.75350
     O        0.15798        0.21455       -1.28105
     H        1.61155       -1.37871        0.79725
     H       -0.00411       -0.81057        2.57479
     H       -0.26633        0.85763        1.80344
     H        2.16195        0.28247       -0.96305
     H        1.24281        1.54792       -0.09693
     H       -1.24645       -1.58985        0.04960
     H       -2.69979       -0.44218        0.33707
     H       -1.53347        1.35513       -0.87676
}

nrg, wfn = energy('M06-2X', return_wfn=True, restart_file="test_restart")
```

However, I get the following error :

```
Traceback (most recent call last):
  File "/home/tony/psi4conda/bin/psi4", line 333, in <module>
    exec(content)
  File "<string>", line 44, in <module>
  File "/home/tony/psi4conda/lib//python3.8/site-packages/psi4/driver/driver.py", line 599, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/tony/psi4conda/lib//python3.8/site-packages/psi4/driver/procrouting/proc.py", line 2390, in run_scf
    scf_wfn = scf_helper(name, post_scf=False, **kwargs)
  File "/home/tony/psi4conda/lib//python3.8/site-packages/psi4/driver/procrouting/proc.py", line 1520, in scf_helper
    old_wfn = core.Wavefunction.from_file(read_filename)
  File "/home/tony/psi4conda/lib//python3.8/site-packages/psi4/driver/p4util/python_helpers.py", line 196, in _core_wavefunction_from_file
    basisset = core.BasisSet.build(molecule, 'ORBITAL', basis_name, puream=basis_puream)
  File "/home/tony/psi4conda/lib//python3.8/site-packages/psi4/driver/p4util/python_helpers.py", line 84, in _pybuild_basis
    bs, basisdict = qcdb.BasisSet.pyconstruct(mol.to_dict(),
  File "/home/tony/psi4conda/lib//python3.8/site-packages/psi4/driver/qcdb/libmintsbasisset.py", line 696, in pyconstruct
    bs, msg, ecp = BasisSet.construct(parser, mol,
  File "/home/tony/psi4conda/lib//python3.8/site-packages/psi4/driver/qcdb/libmintsbasisset.py", line 918, in construct
    raise BasisSetNotFound('BasisSet::construct: Unable to find a basis set for atom %d for key %s among:\n%s' % \

psi4.driver.qcdb.exceptions.BasisSetNotFound: BasisSet::construct: Unable to find a basis set for atom 1 for key BASIS among:
  Shell Entries: ['C']
  Basis Sets: [('ANONYMOUS5AA41DFC', 'ANONYMOUS5AA41DFC', None)]
  File Path: /home/tony/test_psi4_jobs/test_restart, /home/tony/test_psi4_jobs/test_restart, /home/tony/psi4conda/share/psi4/basis
  Input Blocks:



Printing out the relevant lines from the Psithon --> Python processed input file:
         H       -1.24645       -1.58985        0.04960
         H       -2.69979       -0.44218        0.33707
         H       -1.53347        1.35513       -0.87676
    """)
    core.IO.set_default_namespace("")
--> nrg, wfn = energy('M06-2X', return_wfn=True, restart_file="test_restart")

!----------------------------------------------------------------------------------!
!                                                                                  !
!  BasisSet::construct: Unable to find a basis set for atom 1 for key BASIS among: !
!   Shell Entries: ['C']                                                           !
!   Basis Sets: [('ANONYMOUS5AA41DFC', 'ANONYMOUS5AA41DFC', None)]                 !
!   File Path: /home/tony/test_psi4_jobs/test_restart,                             !
!     /home/tony/test_psi4_jobs/test_restart,                                      !
!     /home/tony/psi4conda/share/psi4/basis                                        !
!   Input Blocks:                                                                  !
!                                                                                  !
!----------------------------------------------------------------------------------!
```

The documentation indicates that this should work. I've tried it with "scf" instead of M06-2X, and I get the same error.

**Comment by zachglick** [comment]
Hi,

I suspect that this problem is related to the definition of your basis set. The `basis` block in your input file is part of psi4's special syntax to define [custom, mixed basis sets](https://psicode.org/psi4manual/1.5.0/basissets.html#mixing-basis-sets):
```
basis {
    assign    def2-SVP
}
```

I can run your inputs successfully if I swap out that `basis` block for the standard basis syntax:
```
set {
    basis   def2-SVP
}
```

Here's the SCF output from the second input, which starts the SCF from the serialized orbitals:
```
  ==> Iterations <== 

                           Total Energy        Delta E     RMS |[F,P]|

   @DF-RKS iter   0:  -270.15381570481316   -2.70154e+02   1.44676e-07 
   @DF-RKS iter   1:  -270.15381570483822   -2.50679e-11   1.66794e-07 DIIS
  Energy and wave function converged.
```

This fix should be sufficient if all of your calculations require standard, pre-defined basis sets. If you do need to use custom, mixed basis sets, we'll need to investigate this error further.

**Comment by ajs99778** [comment]
Thanks! It looks like naming the basis (`basis this_basis { ... }`) and then using `set basis this_basis` also works.

That being said, I don't I understand why this would be an issue. The way I have requested the basis set is not unusual. Although I'm using the syntax for a mixed/custom basis set, it's the first example presented on that page of the documentation. It's also a valid way to request a basis set - the first job worked after all. The documentation says that `basis { assign ... }` statements can be used to request a basis set and replace `set basis X`. It looks like mixed basis sets also work... as long as you use `basis this_basis { ... }` and `set basis this_basis`. I've used that syntax to apply def2-SVP to C and O, and STO-3G to H, and then restarted the SCF successfully. 

Is there another syntax for reading an SCF guess that is more flexible? For the application I have in mind, I'd be using it for gradients rather than single-point energies.

**Comment by zachglick** [comment]
Thanks for looking into this! I now have a better understanding of the original error. 

First, a note about the SCF restart technology: when you use the `wfn.to_file()` function in the first file, psi4 saves (1) the name of the basis set and (2) the matrix of orbital coefficients. The numbers contained in the orbital matrix aren't useful without knowing which basis they correspond to. In the second file, psi4 reconstructs the basis set using both the saved name and orbital coefficients.

When a `basis` object is defined without a name, psi4 gives that object a [randomly generated name](https://github.com/psi4/psi4/blob/master/psi4/driver/inputparser.py#L273). This is a problem when you want to use the same `basis` object in a new file, since the same object defined in different files will receive different, random names. In the error you posted, the bit about `ANONYMOUS5AA41DFC` refers to the randomly generated name of the basis. Psi4 has no way of knowing what this basis set is.

Your solution of using `basis this_basis { ... }` and `set basis this_basis` certainly works, but you actually don't even need the second line; all you need is `basis this_basis { ... }`.

You asked about a more flexible syntax for reading SCF guesses. What about the current syntax is limiting?
