### ISSUE TITLE
DF-OCC/DIIS extrapolation fails with very large amplitude arrays

### ISSUE THREAD

**Issue by behnle** [psi4/psi4#2591]
The current DIIS code used in DF-OCC code fails if the size of the extrapolated quantity exceeds HUGE(int32)  (sorry for the fortran syntax...). An example output including additional debug printout is
```
 ============================================================================== 
 ================ Performing DF-OREMP iterations... =========================== 
 ============================================================================== 
                    Minimizing DF-REMP-L Functional 
                    ------------------------------ 
 Iter       E_total           DE           RMS MO Grad      MAX MO Grad      RMS T2    
 ----    ---------------    ----------     -----------      -----------     ---------- 
   1     -2211.6030242185     -2.21e+03       1.77e-04         4.91e-03        2.60e-06 
   2     -2211.6180646887     -1.50e-02       9.31e-05         3.61e-03        1.12e-06 
Matrix::vector_dot: Size of vector 1: 124357188 
Matrix::vector_dot: Size of vector 2: 4419324484 

Traceback (most recent call last):
  File "/home/tu/tu_tu/tu_ctibc01/prog/PSI4/1.5_devel/bin/psi4", line 338, in <module>
    exec(content)
  File "<string>", line 81, in <module>
  File "/home/tu/tu_tu/tu_ctibc01/prog/PSI4/1.5_devel/lib/psi4/driver/driver.py", line 548, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/tu/tu_tu/tu_ctibc01/prog/PSI4/1.5_devel/lib/psi4/driver/procrouting/proc.py", line 685, in select_lccd
    return func(name, **kwargs)
  File "/home/tu/tu_tu/tu_ctibc01/prog/PSI4/1.5_devel/lib/psi4/driver/procrouting/proc.py", line 2095, in run_dfocc
    dfocc_wfn = core.dfocc(ref_wfn)
  File "/home/tu/tu_tu/tu_ctibc01/prog/PSI4/1.5_devel/lib/psi4/driver/procrouting/diis.py", line 375, in extrapolate
    coeffs = self.diis_coefficients()
  File "/home/tu/tu_tu/tu_ctibc01/prog/PSI4/1.5_devel/lib/psi4/driver/procrouting/diis.py", line 254, in diis_coefficients
    B[i, j] = self.get_dot_product(i, j)
  File "/home/tu/tu_tu/tu_ctibc01/prog/PSI4/1.5_devel/lib/psi4/driver/procrouting/diis.py", line 198, in get_dot_product
    dot_product += Rix.vector_dot(Rjx)

RuntimeError: 
Fatal Error: Matrix::vector_dot: Dimensions do not match!

Error occurred in file: /home/tu/tu_tu/tu_ctibc01/prog/psi4/psi4/psi4/src/psi4/libmints/matrix.cc on line: 1703
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)
psi::Matrix::vector_dot(psi::Matrix const*)



Printing out the relevant lines from the Psithon --> Python processed input file:
    energy('scf',write_orbitals='scf_mos')
    Avals=[0.00, 0.05, 0.10, 0.12, 0.15, 0.20, 0.21, 0.22, 0.23, 0.24, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50, 0.55, 0.60, 0.65, 0.70, 0.75, 0.80, 0.85, 0.90, 0.95, 1.00]
    for A in Avals:
         psi4.core.print_out("running step %5.2f" % A)
         core.set_global_option("REMP_A", A)
-->      energy('oremp',restart_file='scf_mos')
         core.set_global_option("MO_READ", "true")
         psi4.core.print_out("")

!----------------------------------------------------------------------------------!
!                                                                                  !
! Fatal Error: Matrix::vector_dot: Dimensions do not match!                        !
! Error occurred in file:                                                          !
!     /home/tu/tu_tu/tu_ctibc01/prog/psi4/psi4/psi4/src/psi4/libmints/matrix.cc on !
!     line: 1703                                                                   !
! The most recent 5 function calls were:                                           !
! psi::PsiException::PsiException(std::__cxx11::basic_string<char,                 !
!     std::char_traits<char>, std::allocator<char> >, char const*, int)            !
! psi::Matrix::vector_dot(psi::Matrix const*)                                      !
!                                                                                  !
!----------------------------------------------------------------------------------!
```
(the example uses a custom method but the problem should be reproducible with DF-OMP2).
The molecule in question has 86 occupied and 773 virtual correlated orbitals, giving rise to (depending on the storage scheme) ~2.2E9 amplitudes.

The root cause of the issue seems to be missing type casts to size_t in libmints/matrix.cc. Inserting debug printout shows that the size calculation of the second vector in vector_dot (line 1699)  and axpy(line 1443) overflows, while the size calculations of the first vector have "enough" type casts. The following proposed fix seems to resolve the problem, at least now the calculation passes the point where it crashed before:
```
diff --git a/psi4/src/psi4/libmints/matrix.cc b/psi4/src/psi4/libmints/matrix.cc
index ad5ffb5a0..69521972e 100644
--- a/psi4/src/psi4/libmints/matrix.cc
+++ b/psi4/src/psi4/libmints/matrix.cc
@@ -1439,8 +1439,8 @@ void Matrix::axpy(double a, SharedMatrix X) {
         throw PSIEXCEPTION("Matrix::axpy: Matrices do not have the same nirreps");
     }
     for (int h = 0; h < nirrep_; h++) {
-        size_t size = colspi_[h ^ symmetry()] * (size_t)rowspi_[h];
-        if (size != (X->rowspi()[h] * X->colspi()[h ^ X->symmetry()])) {
+        size_t size = (size_t)colspi_[h ^ symmetry()] * (size_t)rowspi_[h];
+        if (size != ((size_t)X->rowspi()[h] * (size_t)X->colspi()[h ^ X->symmetry()])) {
             throw PSIEXCEPTION("Matrix::axpy: Matrices sizes do not match.");
         }
         if (size) {
@@ -1694,10 +1694,14 @@ double Matrix::vector_dot(const Matrix *const rhs) {
     size_t size;
 
     for (int h = 0; h < nirrep_; ++h) {
-        size = rowspi_[h] * colspi_[h ^ symmetry_];
+        size = (size_t)rowspi_[h] * (size_t)colspi_[h ^ symmetry_];
         // Check the size of the other
-        if (size != rhs->rowdim(h) * (size_t)rhs->coldim(h ^ symmetry_))
+        if (size != (size_t)rhs->rowdim(h) * (size_t)rhs->coldim(h ^ symmetry_)) {
+            outfile->Printf("Matrix::vector_dot: Size of vector 1: %zu \n", size);
+            outfile->Printf("Matrix::vector_dot: Size of vector 2: %zu \n", rhs->rowdim(h) * (size_t)rhs->coldim(h ^ symmetry_));
+ 
             throw PSIEXCEPTION("Matrix::vector_dot: Dimensions do not match!\n");
+        }
 
         if (size) sum += C_DDOT(size, (&matrix_[h][0][0]), 1, &(rhs->matrix_[h][0][0]), 1);
     }
```
(of course without the debug printout)

Best regards
Stefan

**Comment by behnle** [comment]
Ouch, the problem cannot be reproduced with the current 1.5 release as the release version will die even much earlier with ``MemoryError: std::bad_array_new_length``. When calculating array lengths for ampiitudes, residua and density fitting b factors, simple int32 arithmethic is used, which overflows at some point. `new` is then called with a negative size. i fixed this already in my development branch... Input for reproducing the problem:
```
memory 160 GB
molecule PR20 {
0 1
Ir   -0.0036453   -0.0067418    0.0546240
P     2.3412316    0.2633260   -0.0827666
C     2.8322725    1.6499560   -1.1514034
C     3.1508965    0.5810022    1.5225953
H     2.7397226    1.4975243    1.9544020
H     3.0796627   -2.0414912   -0.0970847
H     4.2325349    0.6920499    1.3971415
H     2.8126116   -1.4065392   -1.7435421
H     3.9236645    1.7279364   -1.1921940
H     2.9451701   -0.2527656    2.1998134
C     3.2265215   -1.1827248   -0.7571267
H     2.4227823    1.4722103   -2.1484758
H     4.2962318   -0.9681045   -0.8457994
H     2.3889675    2.5675955   -0.7590075
P    -2.3731653   -0.0356822   -0.0699620
C    -3.1396700    1.0016926    1.2209589
C    -3.0094090    0.6380218   -1.6352816
H    -2.9455753   -2.3068093   -0.7136733
H    -4.2946110   -1.5213106    0.1442505
H    -2.8800339   -2.1267692    1.0512420
C    -3.2080716   -1.6536880    0.1215551
H    -4.1029305    0.6851097   -1.6068349
H    -2.5824278    1.6361161   -1.7615996
H    -4.2216153    1.0653282    1.0682275
H    -2.6891213    1.9959193    1.1600952
H    -2.6744520    0.0098950   -2.4628143
H    -2.9377790    0.5752071    2.2074361
C    -0.0445914    0.2683835    1.8872601
O    -0.0651117    0.4624335    3.0248963
Cl   -0.3329573    2.5059651   -0.2539036
C     0.2355846   -2.0382203    0.3696479
O     0.5870862   -2.4771706    1.4540805
Cl    0.1349587   -0.2718086   -2.3358022
C     0.0008664   -3.0153971   -0.7782268
H    -0.1231146   -4.0205893   -0.3660997
H     0.8774694   -2.9930708   -1.4340628
H    -0.8449842   -2.7261204   -1.4026378
}

set reference rhf
set basis def2-TZVPP
set{
  freeze_core false
  cc_type df
  mp2_type df
}  

set{
  e_convergence 1.0E-9
  r_convergence 1.0E-8
  max_mograd_convergence 1.0E-7
  rms_mograd_convergence 1.0E-8
  TPDM_ABCD_TYPE direct
  mo_maxiter 200
}

energy('scf',write_orbitals='scf_mos')
energy('omp2',restart_file='scf_mos')

```

**Comment by JonathonMisiewicz** [comment]
Thanks for the report. I'm intending to talk about the state of `dfocc` at the upcoming Psi conf. call, which I'm imagining is tomorrow. We need to get things re-synced before we address this.
