### ISSUE TITLE
can psi4 deal with cyclic compounds?

### ISSUE THREAD

**Issue by hima111997** [psi4/psi4#2599]
i was trying to parameterize a compound with FFParam and i wanted to do a dihedral scan for one of the dihedrals in my molecule, however, an error was produced saying that the atoms should not be in a ring. 

is there a way to overcome this error?

**Comment by loriab** [comment]
Psi4 is fine with cyclic mols, but the optimizer could benefit from a @psi-rking consult. We're in the middle of switching out optimizer implementations, btw. Are you able to post your input file?

**Comment by hima111997** [comment]
actually i cant even produce the input file for psi4 using FFParam-GUI i have this error:

`WARNING:root:Support for bonded parameter scan with Psi4 is experimental at best. Proceed with caution.
INFO:root:Using default names for the outputs.
[09:59:35] Molecule does not have explicit Hs. Consider calling AddHs()
ERROR:root:Uncaught Exception
Traceback (most recent call last):
  File "/home/ibrahim/miniconda3/envs/ffpenv/lib/python3.8/site-packages/ffparam-1.0.0-py3.8.egg/ffparam/FFPMainWindow.py", line 1297, in execute_56
    file2disp = self.chk.CreateQM("dihe",filein=coor,work_dir=self.qm_dir,recenter=False,qmeng=qmengi,qmtop=qmtop,char=chari,mult=multi,dihatomnam=dihl,dihrange=dihr)
  File "/home/ibrahim/miniconda3/envs/ffpenv/lib/python3.8/site-packages/ffparam-1.0.0-py3.8.egg/ffparam/Windowsaction.py", line 165, in CreateQM
    fileout=piwclass.run('bondedscan',outpath=work_dir,bonded=[bonded],coor=self.coords,fixed=False)
  File "/home/ibrahim/miniconda3/envs/ffpenv/lib/python3.8/site-packages/ffparam-1.0.0-py3.8.egg/ffparam/script_core/Psi4InputWriter.py", line 307, in run
    writtenfile=func(data,Psi4header)
  File "/home/ibrahim/miniconda3/envs/ffpenv/lib/python3.8/site-packages/ffparam-1.0.0-py3.8.egg/ffparam/script_core/Psi4InputWriter.py", line 564, in writebondedscan
    rdcrds=ffrd.MolTransform(rdmol.mol,self.resn,self.reschrg,coor,self.atomnames,self.atomnrmap,self.topo['bondnames'],\
  File "/home/ibrahim/miniconda3/envs/ffpenv/lib/python3.8/site-packages/ffparam-1.0.0-py3.8.egg/ffparam/script_core/ffp_rdkit.py", line 182, in __init__
    self.__transform()
  File "/home/ibrahim/miniconda3/envs/ffpenv/lib/python3.8/site-packages/ffparam-1.0.0-py3.8.egg/ffparam/script_core/ffp_rdkit.py", line 288, in __transform
    newcoor=self.__transformcore(mol,self.coor,self.changetype,self.scanatomnr,values[val])
  File "/home/ibrahim/miniconda3/envs/ffpenv/lib/python3.8/site-packages/ffparam-1.0.0-py3.8.egg/ffparam/script_core/ffp_rdkit.py", line 259, in __transformcore
    funcs[changetype](conf,*atomlist,value)
ValueError: bond (j,k) must not belong to a ring
`

**Comment by loriab** [comment]
It looks like the intermediate program FFParam is firm on its procedures not being suitable for cyclic molecules. Also, the no-hydrogens warning looks alarming. Quantum chemistry inputs must have coordinates for all atoms.

**Comment by hima111997** [comment]
i have all hydrogens added to the compound in the file i am using

**Comment by loriab** [comment]
Glad the hydrogens aren't an issue.

Since the exception is coming from FFParam before it hits Psi4, it's better to wait for one of your [recent](https://groups.google.com/g/ffparam-issues/c/bbDbfZGzQac) [queries](https://groups.google.com/g/ffparam-issues/c/odl-f6eWfWE) to the FFParam group, so I'm closing for now. If there is reason to believe this is an issue on Psi's end, please open a new issue.
