### ISSUE TITLE
ADIIS minimization failed for wB97M-V energy computation with modified VV10 parameters

### ISSUE THREAD

**Issue by averyparr** [psi4/psi4#2641]
I am running some psi4 jobs which involve modifying the parameters DFT_VV10_B and DFT_VV10_C for various benzene dimer configurations. For several dimer configurations and several values of (b,c), I get an error telling me that ADIIS minimization failed, and asking me to file a bug report. I've prepared an example and put my input and output files below. Any help I could get would be wonderful—and please let me know if I can provide any more information that would be helpful! 

Input file:
```
set num_frozen_docc 12
set {
    dft_vv10_b 0.06022547162926983
    dft_vv10_c 0.7450476605857299
}
set {
basis def2-tzvppd
guess sad
dft_nuclear_scheme SBECKE
dft_radial_scheme EM
dft_radial_points 99
dft_spherical_points 590
dft_vv10_radial_points 50
dft_vv10_spherical_points 194
dft_pruning_scheme robust
}
set {
wcombine False
}
molecule mol {
0 1
C -0.260781259973    -0.714012941782     1.022641061033
C  0.448798235138    -0.584866555587     1.116392879147
C  0.671191593804     0.158609920222     1.104026912627
C  0.177969561551     0.681404978559     1.093307893756
C -0.560580808895     0.542719215332     1.056079456761
C -0.776583606603    -0.133446136243     1.103859872549
H -0.442720873003    -1.244238976392     0.982141695030
H  0.874512929539    -0.960390442589     1.119149924166
H  1.217460053606     0.336381670040     1.046181387539
H  0.335297687566     1.281777775821     0.982193856028
H -0.948519039798     0.925731991759     1.117846063269
H -1.420111450991    -0.227880344246     1.099752848840
C -0.431336419082    -0.578608087844    -1.006105897774
C -0.616450380987     0.164556718463    -1.058443190817
C -0.158086394624     0.730699386222    -0.889727187104
C  0.484942144607     0.574229834356    -0.649010141458
C  0.688355917017    -0.142302467208    -0.581381981865
C  0.242793965654    -0.737031769438    -0.731596272801
H -0.732074019279    -1.008555512000    -1.147218404188
H -1.164258386631     0.206232540657    -1.161273694869
H -0.258581893650     1.331482152944    -0.817970826130
H  0.882404676284     0.994103603000    -0.554927857467
H  1.180331932734    -0.274347490367    -0.372481393212
H  0.518565778818    -1.191478177535    -0.672179821662
units angstrom
no_reorient
no_com
symmetry c1
}
mol.update_geometry()
e, wf = energy('wb97m-v',return_wfn=True,)
```

Output File:
```

    -----------------------------------------------------------------------
          Psi4: An Open-Source Ab Initio Electronic Structure Package
                               Psi4 1.6.0

                         


    D. G. A. Smith, L. A. Burns, A. C. Simmonett, R. M. Parrish,
    M. C. Schieber, R. Galvelis, P. Kraus, H. Kruse, R. Di Remigio,
    A. Alenaizan, A. M. James, S. Lehtola, J. P. Misiewicz, M. Scheurer,
    R. A. Shaw, J. B. Schriber, Y. Xie, Z. L. Glick, D. A. Sirianni,
    J. S. O'Brien, J. M. Waldrop, A. Kumar, E. G. Hohenstein,
    B. P. Pritchard, B. R. Brooks, H. F. Schaefer III, A. Yu. Sokolov,
    K. Patkowski, A. E. DePrince III, U. Bozkaya, R. A. King,
    F. A. Evangelista, J. M. Turney, T. D. Crawford, C. D. Sherrill,
    J. Chem. Phys. 152(18) 184108 (2020). https://doi.org/10.1063/5.0006002

                            Additional Code Authors
    E. T. Seidl, C. L. Janssen, E. F. Valeev, M. L. Leininger,
    J. F. Gonthier, R. M. Richard, H. R. McAlexander, M. Saitow, X. Wang,
    P. Verma, M. H. Lechner, and A. Jiang

             Previous Authors, Complete List of Code Contributors,
                       and Citations for Specific Modules
    https://github.com/psi4/psi4/blob/master/codemeta.json
    https://github.com/psi4/psi4/graphs/contributors
    http://psicode.org/psi4manual/master/introduction.html#citing-psifour

    -----------------------------------------------------------------------


    Psi4 started on: Friday, 22 July 2022 01:16PM

    Process ID: 7409
    Host:       [REMOVED]
    PSIDATADIR: [REMOVED]
    Memory:     500.0 MiB
    Threads:    14
    
  ==> Input File <==

--------------------------------------------------------------------------
print_out('\nSETUP_PHASE\n')
set_num_threads(14)
set num_frozen_docc 12
set {
    dft_vv10_b 0.06022547162926983
    dft_vv10_c 0.7450476605857299
}
set {
basis def2-tzvppd
guess sad
dft_nuclear_scheme SBECKE
dft_radial_scheme EM
dft_radial_points 99
dft_spherical_points 590
dft_vv10_radial_points 50
dft_vv10_spherical_points 194
dft_pruning_scheme robust
}
set {
wcombine False
}
molecule mol {
0 1
C -0.260781259973    -0.714012941782     1.022641061033
C  0.448798235138    -0.584866555587     1.116392879147
C  0.671191593804     0.158609920222     1.104026912627
C  0.177969561551     0.681404978559     1.093307893756
C -0.560580808895     0.542719215332     1.056079456761
C -0.776583606603    -0.133446136243     1.103859872549
H -0.442720873003    -1.244238976392     0.982141695030
H  0.874512929539    -0.960390442589     1.119149924166
H  1.217460053606     0.336381670040     1.046181387539
H  0.335297687566     1.281777775821     0.982193856028
H -0.948519039798     0.925731991759     1.117846063269
H -1.420111450991    -0.227880344246     1.099752848840
C -0.431336419082    -0.578608087844    -1.006105897774
C -0.616450380987     0.164556718463    -1.058443190817
C -0.158086394624     0.730699386222    -0.889727187104
C  0.484942144607     0.574229834356    -0.649010141458
C  0.688355917017    -0.142302467208    -0.581381981865
C  0.242793965654    -0.737031769438    -0.731596272801
H -0.732074019279    -1.008555512000    -1.147218404188
H -1.164258386631     0.206232540657    -1.161273694869
H -0.258581893650     1.331482152944    -0.817970826130
H  0.882404676284     0.994103603000    -0.554927857467
H  1.180331932734    -0.274347490367    -0.372481393212
H  0.518565778818    -1.191478177535    -0.672179821662
units angstrom
no_reorient
no_com
symmetry c1
}
mol.update_geometry()
e, wf = energy('wb97m-v',return_wfn=True,)--------------------------------------------------------------------------

SETUP_PHASE
  Threads set to 14 by Python driver.

Scratch directory: [REMOVED]

*** tstart() called on [REMOVED]
*** at Fri Jul 22 13:16:33 2022

   => Loading Basis Set <=

    Name: DEF2-TZVPPD
    Role: ORBITAL
    Keyword: BASIS
    atoms 1-6, 13-18  entry C          line   144 file [REMOVED BASE DIRECTORY]/psi4/basis/def2-tzvppd.gbs 
    atoms 7-12, 19-24 entry H          line    14 file [REMOVED BASE DIRECTORY]/psi4/basis/def2-tzvppd.gbs 


         ---------------------------------------------------------
                                   SCF
               by Justin Turney, Rob Parrish, Andy Simmonett
                          and Daniel G. A. Smith
                              RKS Reference
                       14 Threads,    500 MiB Core
         ---------------------------------------------------------

  ==> Geometry <==

    Molecular point group: c1
    Full point group: C1

    Geometry (in Angstrom), charge = 0, multiplicity = 1:

       Center              X                  Y                   Z               Mass       
    ------------   -----------------  -----------------  -----------------  -----------------
         C           -0.260781259973    -0.714012941782     1.022641061033    12.000000000000
         C            0.448798235138    -0.584866555587     1.116392879147    12.000000000000
         C            0.671191593804     0.158609920222     1.104026912627    12.000000000000
         C            0.177969561551     0.681404978559     1.093307893756    12.000000000000
         C           -0.560580808895     0.542719215332     1.056079456761    12.000000000000
         C           -0.776583606603    -0.133446136243     1.103859872549    12.000000000000
         H           -0.442720873003    -1.244238976392     0.982141695030     1.007825032230
         H            0.874512929539    -0.960390442589     1.119149924166     1.007825032230
         H            1.217460053606     0.336381670040     1.046181387539     1.007825032230
         H            0.335297687566     1.281777775821     0.982193856028     1.007825032230
         H           -0.948519039798     0.925731991759     1.117846063269     1.007825032230
         H           -1.420111450991    -0.227880344246     1.099752848840     1.007825032230
         C           -0.431336419082    -0.578608087844    -1.006105897774    12.000000000000
         C           -0.616450380987     0.164556718463    -1.058443190817    12.000000000000
         C           -0.158086394624     0.730699386222    -0.889727187104    12.000000000000
         C            0.484942144607     0.574229834356    -0.649010141458    12.000000000000
         C            0.688355917017    -0.142302467208    -0.581381981865    12.000000000000
         C            0.242793965654    -0.737031769438    -0.731596272801    12.000000000000
         H           -0.732074019279    -1.008555512000    -1.147218404188     1.007825032230
         H           -1.164258386631     0.206232540657    -1.161273694869     1.007825032230
         H           -0.258581893650     1.331482152944    -0.817970826130     1.007825032230
         H            0.882404676284     0.994103603000    -0.554927857467     1.007825032230
         H            1.180331932734    -0.274347490367    -0.372481393212     1.007825032230
         H            0.518565778818    -1.191478177535    -0.672179821662     1.007825032230

  Running in c1 symmetry.

  Rotational constants: A =      0.17182  B =      0.08760  C =      0.08513 [cm^-1]
  Rotational constants: A =   5151.08371  B =   2626.15995  C =   2552.12610 [MHz]
  Nuclear repulsion = 1190.670750997537880

  Charge       = 0
  Multiplicity = 1
  Electrons    = 84
  Nalpha       = 42
  Nbeta        = 42

  ==> Algorithm <==

  SCF Algorithm Type is DF.
  DIIS enabled.
  MOM disabled.
  Fractional occupation disabled.
  Guess Type is SAD.
  Energy threshold   = 1.00e-06
  Density threshold  = 1.00e-06
  Integral threshold = 1.00e-12

  ==> Primary Basis <==

  Basis Set: DEF2-TZVPPD
    Blend: DEF2-TZVPPD
    Number of shells: 240
    Number of basis functions: 648
    Number of Cartesian functions: 732
    Spherical Harmonics?: true
    Max angular momentum: 3

  ==> DFT Potential <==

   => LibXC <=

    Version 5.1.6
    S. Lehtola, C. Steigemann, M. J. Oliveira, and M. A. Marques, SoftwareX 7, 1 (2018) (10.1016/j.softx.2017.11.002)

   => Composite Functional: WB97M-V <= 

    wB97M-V Hyb-GGA Exchange-Correlation Functional

    N. Mardirossian and M. Head-Gordon, J. Chem. Phys. 144, 214110 (2016) (10.1063/1.4952647)

    Deriv               =              1
    GGA                 =           TRUE
    Meta                =           TRUE

    Exchange Hybrid     =           TRUE
    MP2 Hybrid          =          FALSE

   => Exchange-Correlation Functionals <=

    1.0000   wB97M-V exchange-correlation functional

   => Exact (HF) Exchange <=

    0.8500            HF,LR [omega = 0.3000]
    0.1500               HF 

   => LibXC Density Thresholds  <==

    XC_HYB_MGGA_XC_WB97M_V:  1.00E-13 

   => VV10 Non-Local Parameters <=

    VV10 B              =     6.0225E-02
    VV10 C              =     7.4505E-01

   => Molecular Quadrature <=

    Radial Scheme          =             EM
    Pruning Scheme         =         ROBUST
    Pruning Type           =         REGION
    Nuclear Scheme         =         SBECKE

    Blocking Scheme        =         OCTREE
    BS radius alpha        =              1
    Pruning alpha          =              1
    Radial Points          =             99
    Spherical Points       =            590
    Total Points           =         912458
    Total Blocks           =           6145
    Max Points             =            256
    Max Functions          =            640
    Weights Tolerance      =       1.00E-15

   => Loading Basis Set <=

    Name: (DEF2-TZVPPD AUX)
    Role: JKFIT
    Keyword: DF_BASIS_SCF
    atoms 1-6, 13-18  entry C          line   198 file [REMOVED BASE DIRECTORY]/psi4/basis/def2-universal-jkfit.gbs 
    atoms 7-12, 19-24 entry H          line    18 file [REMOVED BASE DIRECTORY]/psi4/basis/def2-universal-jkfit.gbs 

  ==> Integral Setup <==

  ==> DiskDFJK: Density-Fitted J/K Matrices <==

    J tasked:                  Yes
    K tasked:                  Yes
    wK tasked:                 Yes
    Omega:               3.000E-01
    OpenMP threads:             14
    Integrals threads:          14
    Memory [MiB]:              337
    Algorithm:                Disk
    Integral Cache:           NONE
    Schwarz Cutoff:          1E-12
    Fitting Condition:       1E-10

   => Auxiliary Basis Set <=

  Basis Set: (DEF2-TZVPPD AUX)
    Blend: DEF2-UNIVERSAL-JKFIT
    Number of shells: 372
    Number of basis functions: 1116
    Number of Cartesian functions: 1308
    Spherical Harmonics?: true
    Max angular momentum: 4

  Cached 0.1% of DFT collocation blocks in 0.036 [GiB].

  Minimum eigenvalue in the overlap matrix is 7.2890634209E-11.
  Reciprocal condition number of the overlap matrix is 1.8442944048E-12.
    Using canonical orthogonalization.
  Overall, 27 of 648 possible MOs eliminated.


  ==> Pre-Iterations <==

  SCF Guess: Superposition of Atomic Densities via on-the-fly atomic UHF (no occupation information).

   -------------------------
    Irrep   Nso     Nmo    
   -------------------------
     A        648     621 
   -------------------------
    Total     648     621
   -------------------------

  ==> Iterations <==

                           Total Energy        Delta E     RMS |[F,P]|

   @DF-RKS iter SAD:  -212.57868470845432   -2.12579e+02   0.00000e+00 
   @DF-RKS iter   1:   -74.64880419187541    1.37930e+02   2.89342e-02 DIIS/ADIIS
   @DF-RKS iter   2:  -104.73618075758787   -3.00874e+01   2.89040e-02 DIIS/ADIIS

Traceback (most recent call last):
  File "[REMOVED BASE DIRECTORY]/bin/psi4", line 347, in <module>
    exec(content)
  File "<string>", line 66, in <module>
  File "[REMOVED BASE DIRECTORY]/lib/psi4/driver/driver.py", line 501, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File [REMOVED BASE DIRECTORY]/lib/psi4/driver/procrouting/proc.py", line 2455, in run_scf
    scf_wfn = scf_helper(name, post_scf=False, **kwargs)
  File "[REMOVED BASE DIRECTORY]/lib/psi4/driver/procrouting/proc.py", line 1670, in scf_helper
    e_scf = scf_wfn.compute_energy()
  File "[REMOVED BASE DIRECTORY]/lib/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 86, in scf_compute_energy
    self.iterations()
  File "[REMOVED BASE DIRECTORY]/lib/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 412, in scf_iterate
    for engine_used in self.diis(Dnorm):
  File "[REMOVED BASE DIRECTORY]/lib/psi4/driver/procrouting/scf_proc/subclass_methods.py", line 111, in _RHF_diis
    return self.diis_manager_.extrapolate(self.Fa(), Dnorm=Dnorm)
  File "[REMOVED BASE DIRECTORY]/lib/psi4/driver/procrouting/diis.py", line 407, in extrapolate
    coeffs = m * initial_coefficient_function() + (1 - m) * self.diis_coefficients()
  File "[REMOVED BASE DIRECTORY]/lib/psi4/driver/procrouting/diis.py", line 288, in adiis_coefficients
    raise Exception("ADIIS minimization failed. File a bug, and include your entire input and output files.")

Exception: ADIIS minimization failed. File a bug, and include your entire input and output files.


Printing out the relevant lines from the Psithon --> Python processed input file:
    no_com
    symmetry c1
    ""","mol")
    core.IO.set_default_namespace("mol")
    mol.update_geometry()
--> e, wf = energy('wb97m-v',return_wfn=True,)

!----------------------------------------------------------------------------------!
!                                                                                  !
!  ADIIS minimization failed. File a bug, and include your entire input and output !
!     files.                                                                       !
!                                                                                  !
!----------------------------------------------------------------------------------!

    Psi4 stopped on: Friday, 22 July 2022 01:19PM
    Psi4 wall time for execution: 0:02:55.44

*** Psi4 encountered an error. Buy a developer more coffee!
*** Resources and help at github.com/psi4/psi4.
```

**Comment by JonathonMisiewicz** [comment]
Thanks for the report. I've been able to reproduce the crash. (I observe a fifth decimal place disagreement in DF-RKS SAD energy and a third decimal place disagreement in all iteration energies.) There are two things that worry me here:

1. The crash itself. I struggle to imagine why the ADIIS optimization problem is so difficult to solve here.
2. The abhorrent SCF energies. The energy jumps 138 hartrees after the guess! If I remember correctly, the SAD energy isn't the energy corresponding to a particular set of orbitals, but this is still astounding. @susilehtola may have some insight on this.

I can poke on this, but the first step will be to try and reproduce this with a smaller system. I don't have access to 14 threads, so I'll have trouble running this repeatedly.

**Comment by hokru** [comment]
Only on phone. The S eigenvalue looks suspicious. Is the geometry alright?

**Comment by JonathonMisiewicz** [comment]
Good call. The geometry is about a factor of 2 too compressed. (Treating the geometry as bohr rather than angstroms makes things _worse_.)

@averyparr Where did this geometry come from?

**Comment by susilehtola** [comment]
@JonathonMisiewicz SAD energies deviate appreciably from molecular energies when the orbitals have a lot of overlap... as in this case.

**Comment by susilehtola** [comment]
I did three investigations into the geometry with PBE/def2-SV(P) calculations.

1. with `units bohr` I get
```
  @DF-RKS iter SAD:   -81.53594697549568   -8.15359e+01   0.00000e+00 
   @DF-RKS iter   1:    29.39042484087514    1.10926e+02   1.00086e-01 DIIS
```
which is obviously senseless.

2. with `units angstrom` I get
```
   @DF-RKS iter SAD:  -196.06720280860412   -1.96067e+02   0.00000e+00 
   @DF-RKS iter   1:  -107.69340900170397    8.83738e+01   9.96686e-02 DIIS
```
and this is senseless too.

3. by using `units angstrom` **and** multiplying the coordinates in the input by a factor of 2 I get
```
   @DF-RKS iter SAD:  -148.45143948103299   -1.48451e+02   0.00000e+00 
   @DF-RKS iter   1:  -167.23875395343225   -1.87873e+01   6.63537e-02 DIIS
```
which looks a bit more sane and the geometry visualized also makes sense.

My guess is that whatever produces the geometry is converting to bohr in the wrong way; dividing by ~2 instead of multiplying by ~2...

**Comment by averyparr** [comment]
It seems that the process of creating the geometry was at fault—in particular, in a production run, I created molecules with the "units angstrom" tag, and then called `molecule.set_full_geometry(xyzs)` on each of them. This seems to have had the effect of assuming that the coordinates were in bohr, then converting them to angstroms (dividing by 1.889). This, I think, produces the rough factor of 2 difference observed. I had missed that set_full_geometry assumes that the coordinates are in Bohr. I will try rerunning the fixed version in production to see if I end up with any similar errors. It takes a rather long time to converge (currently at 35 iterations; it's not converged yet), and it is quite low in energy—currently, -905 Hartree.

**Comment by averyparr** [comment]
It is still possible to create the "ADIIS minimization failed" error with the input file below (only changes to the above are correcting the coordinates' units and changing VV10 parameters), but I imagine this is because the values for (b,c) are now so extreme that it's no longer physical. 

```
set num_frozen_docc 12
set {
    dft_vv10_b 0.01
    dft_vv10_c 0.01
}
set {
basis def2-tzvppd
guess sad
dft_nuclear_scheme SBECKE
dft_radial_scheme EM
dft_radial_points 99
dft_spherical_points 590
dft_vv10_radial_points 50
dft_vv10_spherical_points 194
dft_pruning_scheme robust
}
set {
wcombine False
}
molecule mol {
0 1
C -0.49280516    -1.34928891    1.93251153
C  0.84810575    -1.10523761    2.10967679
C  1.26836829     0.29972931    2.0863085 
C  0.33631373     1.28766879    2.06605249
C -1.0593442      1.02559068    1.99570094
C -1.46753033    -0.25217665    2.08599284
H -0.8366212     -2.3512709     1.85597882
H  1.65258993    -1.81487491    2.11488685
H  2.30066607     0.63566923    1.9769963 
H  0.6336208      2.42220895    1.85607739
H -1.79244121     1.74937993    2.11242291
H -2.68362171    -0.43063144    2.07823169
C -0.8151077     -1.09341082   -1.9012646 
C -1.16492239     0.31096713   -2.00016775
C -0.29873999     1.38082172   -1.68134071
C  0.91640784     1.08513712   -1.22645142
C  1.30080416    -0.26891269   -1.09865272
C  0.4588141     -1.39278819   -1.38251659
H -1.3834194     -1.9058937    -2.16792859
H -2.20012949     0.38972302   -2.19448924
H -0.48864896     2.51613661   -1.54574084
H  1.66750317     1.87858355   -1.04866167
H  2.23050409    -0.51844162   -0.70388782
H  0.9799473     -2.25156744   -1.27023577
units angstrom
no_reorient
no_com
symmetry c1
}
mol.update_geometry()
e, wf = energy('wb97m-v',return_wfn=True,)
```

**Comment by hokru** [comment]
> t I imagine this is because the values for (b,c) are now so extreme that it's no longer physical.

Usually you only change the B parameters. Don't change C just because the program lets you.
It would make more sense to change DFT parameters (omega, x) instead of C, I think.

Btw, you can save time and at least intermittently in you fit(?) procedure apply the VV10 correction in a post-scf fashion https://psicode.org/psi4manual/master/dftnl.html#post-scf-time-savings

**Comment by JonathonMisiewicz** [comment]
To sum up the discussion so far:
* The original geometry was malformed. Not a Psi4 problem.
* We've noticed large changes in energy in the early iterations, with the malformed geometry and a SAD guess. Not a Psi4 problem. (See https://github.com/psi4/psi4/issues/2641#issuecomment-1192909620)
* There's been some discussion over how appropriate custom setting DFT VV10 c parameters is. Not a Psi4 problem.
* It's still possible to cause A/EDIIS with a sufficiently non-physical Hamiltonian, whether due to DFT VV10 parameters or a compressed geometry. **This is a Psi4 problem.**

I'll see what I can do about the last one, but I suspect that my options will be very limited.

**Comment by averyparr** [comment]
@hokru For ωB97M-V, it doesn't seem to be possible to change the ω parameter directly from the psithon interface—there's a check at https://github.com/psi4/psi4/blob/d9093c75c71c2b33fbe86f32b25d138675ac22eb/psi4/src/psi4/libfunctional/LibXCfunctional.cc#L218 that disallows it. I want to be on the safe side and not manually change it without knowing why the limitation is put in place. 

As for DFT_VV10_POSTSCF—it does make things faster by quite a bit, but when I move to nonstandard values of (b,c), it yields substantial deviations in energy calculations (e.g. using the above geometry with b = 0.5 and c unchanged, I go from -456.38 to -464.69 when I turn on DFT_VV10_POSTSCF).

**Comment by JonathonMisiewicz** [comment]
> @hokru For ωB97M-V, it doesn't seem to be possible to change the ω parameter directly from the psithon interface—there's a check at
> 
> https://github.com/psi4/psi4/blob/d9093c75c71c2b33fbe86f32b25d138675ac22eb/psi4/src/psi4/libfunctional/LibXCfunctional.cc#L218
> that disallows it. I want to be on the safe side and not manually change it without knowing why the limitation is put in place.

@susilehtola? It looks like this code was added as part of Psi adopting LIbXC in May 2017, so this may be as simple as "it's perfectly legitimate to change omega here; the code needs to be modernized already."

**Comment by susilehtola** [comment]
> > @hokru For ωB97M-V, it doesn't seem to be possible to change the ω parameter directly from the psithon interface—there's a check at
> > https://github.com/psi4/psi4/blob/d9093c75c71c2b33fbe86f32b25d138675ac22eb/psi4/src/psi4/libfunctional/LibXCfunctional.cc#L218
> > 
> > that disallows it. I want to be on the safe side and not manually change it without knowing why the limitation is put in place.
> 
> @susilehtola? It looks like this code was added as part of Psi adopting LIbXC in May 2017, so this may be as simple as "it's perfectly legitimate to change omega here; the code needs to be modernized already."

Looks like hacky code. I'll send a patch

**Comment by tallakahath** [comment]
Hey there! I've been working with @averyparr and wanted to chime in on the _specific_ issue of omega in wb97m-v. I'm don't think this is worth promoting to a bigger issue or not, but at least so if someone else is searching and finds this issue, there's some context.

In _addition_ to the patches made in #2643, there's another change that needs to happen to enable one to set `omega` in wb97m-v. Specifically, the version of libxc that psi4 pulls in is 5.1.5 (https://github.com/psi4/psi4/blob/master/external/upstream/libxc/CMakeLists.txt#L18) . This version is old enough that the C file for wb97m-v is missing a _lot_ of content compared to it's other wb97 cousins (see https://gitlab.com/libxc/libxc/-/blob/5.1.5/src/hyb_mgga_xc_wb97mv.c#L38 and compare to, e.g., https://gitlab.com/libxc/libxc/-/blob/5.1.5/src/hyb_gga_xc_wb97.c#L145)

Because `xc_func_info_get_n_ext_params` ends up returning 0 (since it's not properly set in wb97m-v), psi4 thinks there's nothing it can set (`NPAR` is 0 and the names are NULL). 

Unfortunately this isn't fixed until version 5.3 (https://gitlab.com/libxc/libxc/-/blob/release-5.3.0/src/hyb_mgga_xc_wb97mv.c), which isn't yet a stable release. It's pretty easy to monkey-patch your own libxc 5.2.3+, which _seems_ to work just fine with psi4, but I haven't run any tests besides the basic ones that run during installation.
