### ISSUE TITLE
psi4 1.3.2 can't be imported in Fedora rawhide

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#2656]
The build of psi4 1.3.2 started failing in Fedora rawhide due to test failures.

The test failures are caused by a failed import of core. I am able to reproduce this in the terminal
```
$ python3
Python 3.11.0b5 (main, Jul 26 2022, 00:00:00) [GCC 12.1.1 20220628 (Red Hat 12.1.1-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import psi4
Traceback (most recent call last):
  File "/builddir/build/BUILD/psi4-1.3.2/redhat-linux-build/stage/lib64/python3.11/site-packages/psi4/__init__.py", line 55, in <module>
    from . import core
ImportError: cannot import name 'core' from partially initialized module 'psi4' (most likely due to a circular import) (/builddir/build/BUILD/psi4-1.3.2/redhat-linux-build/stage/lib64/python3.11/site-packages/psi4/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/builddir/build/BUILD/psi4-1.3.2/redhat-linux-build/stage/lib64/python3.11/site-packages/psi4/__init__.py", line 60, in <module>
    raise ImportError("{0}".format(err))
ImportError: cannot import name 'core' from partially initialized module 'psi4' (most likely due to a circular import) (/builddir/build/BUILD/psi4-1.3.2/redhat-linux-build/stage/lib64/python3.11/site-packages/psi4/__init__.py)
```

**Comment by loriab** [comment]
The psi4 code unchanged since May 2019 has suddenly started throwing circular import errors?

Any changes to the dependency list? Particularly, is qcengine present?

Python 3.11 only? I've never tried a 3.11 prerelease.

**Comment by susilehtola** [comment]
Yup. And no changes to dependency lists either; no qcengine.

And yes, this is with Python 3.11 in Fedora rawhide.

**Comment by susilehtola** [comment]
Maybe it's a pybind11 issue?

**Comment by loriab** [comment]
> Maybe it's a pybind11 issue?

 Worth a try. Looks like we were at `v2.2.3` in that era: (2nd col of https://github.com/psi4/psi4meta/blob/master/conda-recipes/conda_build_config.yaml#L103-L104)

> Yup. And no changes to dependency lists either; no qcengine.

aggh

> And yes, this is with Python 3.11 in Fedora rawhide.

Can you dial Python down a bit? Psi 1.3 was only knowingly build for 3.6 and 3.7.

--------

This long life of v1.3 is all because of Libint2 issues, right? Can L2 be vendored with (internal build distributed with) Psi4? Must it be static?

**Comment by susilehtola** [comment]
Yes, this is all due to the switch to L2. L2 can't be bundled with Psi4 since it doesn't come bundled with Psi4 in the first place. All libraries are dynamic in Fedora, and everything has to be compiled from pristine sources.

**Comment by loriab** [comment]
> Yes, this is all due to the switch to L2. L2 can't be bundled with Psi4 since it doesn't come bundled with Psi4 in the first place. All libraries are dynamic in Fedora, and everything has to be compiled from pristine sources.

Caveat: my current L2 knowledge is the equivalent of on-a-tape-drive-in-a-basement-archive, so don't hold me to anything.

I think Psi4 could be built against pristine source, latest release L2 with a little cmake patching psi4-side. But producing and hosting two variants (gss/sss) isn't something you/Fedora want to get into, I expect.

**Comment by susilehtola** [comment]
I am definitely not going to ship two variants of L2.

Qiming Sun's libcint/qcint is a much more compact library and supports up to L=15...

**Comment by susilehtola** [comment]
Also, updating pybind11 didn't help; the import still fails.

**Comment by loriab** [comment]
I was thinking _downgrading_ pb11, not _updating_ it, but ok (2.10 mentions py311 compatibility anyways). I looked through the deps logs from the last good one to this one, and I don't see any red flags.

**Comment by susilehtola** [comment]
Have you tried with Python 3.11 yet?

**Comment by loriab** [comment]
> Have you tried with Python 3.11 yet?

update, I've built python 3.11 rc and numpy from source (first time ever). I did have to use the most recent v2.10.0 pb11. By turning off some diis (see below), I can get the variant on test tu1 to run through 6 SCF iterations (not to convergence) before segfaulting. major things still to investigate -- installing scipy, what lapack libraries for numpy is pip hiding from me, are the timer files closing cleanly when it throws the install-scipy-or-disable-accelerator message. and, of course, all this is on master, not the 1.3.2 of interest to you. 

```
memory 600 mb

molecule h2o {
  O 
  H 1 0.96
  H 1 0.96 2 104.5
}

set basis cc-pVDZ
set scf scf_initial_accelerator none
set diis off
energy('scf')

compare_values(-76.0266327341067125, variable('SCF TOTAL ENERGY'), 6, 'SCF energy')  #TEST
```

**Comment by loriab** [comment]
ok, I have built psi4 v1.3.2 with python v3.11 from conda-forge. I had to make one src modification to get it to compile:

```
(py311cf_L1) psilocaluser@bash:psinet:/psi/gits/hrw-v132/objdir_py311cf_L1: (1.3.x) git diff
diff --git a/psi4/src/create_new_plugin.cc b/psi4/src/create_new_plugin.cc
index 3734a7b..6f2bde2 100644
--- a/psi4/src/create_new_plugin.cc
+++ b/psi4/src/create_new_plugin.cc
@@ -32,6 +32,7 @@
 #include <regex>
 #include <sstream>
 #include <string>
+#include <iterator>
 
 #include "psi4/psi4-dec.h"

```

After that, I get the error, just like you reported: `ImportError: cannot import name 'core' from partially initialized module 'psi4' (most likely due to a circular import)`. However, the suffix for the `core<stuff>.so` library is badly formed, so it's `coreNone`. When I add a symlink to a proper name, it works just fine.

```
(py311cf_L1) psilocaluser@bash:psinet:/psi/gits/hrw-v132/objdir_py311cf_L1: (1.3.x) ll stage/lib/psi4/
total 25704
lrwxrwxrwx. 1 psilocaluser psilocaluser        8 Nov  1 15:57 core.cpython-311-x86_64-linux-gnu.so -> coreNone
-rwxr-xr-x. 1 psilocaluser psilocaluser 26286096 Nov  1 16:14 coreNone
drwxr-xr-x. 7 psilocaluser psilocaluser     4096 Nov  1 15:58 driver
-rw-r--r--. 1 psilocaluser psilocaluser     5898 Nov  1 15:08 extras.py
-rw-r--r--. 1 psilocaluser psilocaluser     2934 Nov  1 14:50 header.py
-rw-r--r--. 1 psilocaluser psilocaluser     3693 Nov  1 15:08 __init__.py
-rw-r--r--. 1 psilocaluser psilocaluser     1144 Nov  1 16:14 metadata.py
drwxrwxr-x. 2 psilocaluser psilocaluser     4096 Nov  1 16:14 __pycache__
drwxrwxr-x. 2 psilocaluser psilocaluser     4096 Nov  1 15:20 tests
```
```
(py311cf_L1) psilocaluser@bash:psinet:/psi/gits/hrw-v132/objdir_py311cf_L1: (1.3.x) stage/bin/psi4 ../tests/tu1-h2o-energy/input.dat 
	SCF energy........................................................PASSED
```

Full conda env is this:

```
(py311cf_L1) psilocaluser@bash:psinet:/psi/gits/hrw-v132/objdir_py311cf_L1: (1.3.x) conda list
# packages in environment at /psi/toolchainconda/envs/py311cf_L1:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
binutils_impl_linux-64    2.39                 h6ceecb4_0    conda-forge
binutils_linux-64         2.39                h5fc0e48_11    conda-forge
blas                      2.116                       mkl    conda-forge
blas-devel                3.9.0            16_linux64_mkl    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.9.24            ha878542_0    conda-forge
cmake                     3.24.2               h5432695_0    conda-forge
deepdiff                  6.2.1              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                h27087fc_0    conda-forge
gcc_impl_linux-64         12.2.0              hcc96c02_19    conda-forge
gcc_linux-64              12.2.0              h4798a0e_11    conda-forge
gxx_impl_linux-64         12.2.0              hcc96c02_19    conda-forge
gxx_linux-64              12.2.0              hb41e900_11    conda-forge
kernel-headers_linux-64   2.6.32              he073ed8_15    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.19.3               h08a2579_0    conda-forge
ld_impl_linux-64          2.39                 hc81fddc_0    conda-forge
libblas                   3.9.0            16_linux64_mkl    conda-forge
libcblas                  3.9.0            16_linux64_mkl    conda-forge
libcurl                   7.86.0               h2283fc2_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-devel_linux-64     12.2.0              h3b97bd3_19    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran5              12.2.0              h337968e_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libint                    1.2.1                hb4a4fd4_6    psi4
liblapack                 3.9.0            16_linux64_mkl    conda-forge
liblapacke                3.9.0            16_linux64_mkl    conda-forge
libnghttp2                1.47.0               hff17c54_1    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libsanitizer              12.2.0              h46fd767_19    conda-forge
libsqlite                 3.39.4               h753d276_0    conda-forge
libssh2                   1.10.0               hf14f497_3    conda-forge
libstdcxx-devel_linux-64  12.2.0              h3b97bd3_19    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libuv                     1.44.2               h166bdaf_0    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
llvm-openmp               14.0.4               he0ac6c6_0    conda-forge
mkl                       2022.1.0           h84fe81f_915    conda-forge
mkl-devel                 2022.1.0           ha770c72_916    conda-forge
mkl-include               2022.1.0           h84fe81f_915    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
numpy                     1.23.4                   pypi_0    pypi
openssl                   3.0.7                h166bdaf_0    conda-forge
ordered-set               4.1.0              pyhd8ed1ab_0    conda-forge
pint                      0.20.1             pyhd8ed1ab_0    conda-forge
pip                       22.3               pyhd8ed1ab_0    conda-forge
pybind11                  2.10.1                   pypi_0    pypi
pybind11-global           2.10.1                   pypi_0    pypi
pydantic                  1.10.2                   pypi_0    pypi
python                    3.11.0          ha86cf86_0_cpython    conda-forge
python_abi                3.11                    2_cp311    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
rhash                     1.4.3                h166bdaf_0    conda-forge
setuptools                65.5.0             pyhd8ed1ab_0    conda-forge
sysroot_linux-64          2.12                he073ed8_15    conda-forge
tbb                       2021.6.0             h924138e_1    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
typing-extensions         4.4.0                hd8ed1ab_0    conda-forge
typing_extensions         4.4.0              pyha770c72_0    conda-forge
tzdata                    2022f                h191b570_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zlib                      1.2.13               h166bdaf_4    conda-forge
zstd                      1.5.2                h6239696_4    conda-forge
```

Could it be this library file name issue you were hitting in Fedora?

Note that I let the environment use latest pint (v0.20.1) and internal build qcelemental (v0.4.0). In that combination, certain tests like `tu4-h2o-freq/input.dat` will give `AttributeError: module 'pint' has no attribute 'quantity'`. That's a pretty easy patch to qcel (I just minted it in v0.25.1) or you can constrain pint<0.20 . If you hit this, lmk what your constraints are, and I can suggest a combination.

**Comment by loriab** [comment]
Commenting out an extra cmake line fixes the `coreNone` to `core.so`. Basic, but works.

```
>>> (1.3.x) ll stage/lib/psi4/
total 25704
-rwxr-xr-x. 1 psilocaluser psilocaluser 26286096 Nov  1 16:43 core.so
drwxr-xr-x. 7 psilocaluser psilocaluser     4096 Nov  1 15:58 driver
-rw-r--r--. 1 psilocaluser psilocaluser     5898 Nov  1 15:08 extras.py
-rw-r--r--. 1 psilocaluser psilocaluser     2934 Nov  1 14:50 header.py
-rw-r--r--. 1 psilocaluser psilocaluser     3693 Nov  1 15:08 __init__.py
-rw-r--r--. 1 psilocaluser psilocaluser     1144 Nov  1 16:43 metadata.py
drwxrwxr-x. 2 psilocaluser psilocaluser     4096 Nov  1 16:14 __pycache__
drwxrwxr-x. 2 psilocaluser psilocaluser     4096 Nov  1 15:20 tests
```
```
>>> (1.3.x) stage/bin/psi4 ../tests/tu1-h2o-energy/input.dat 
	SCF energy........................................................PASSED
```
```
>>> (1.3.x) git diff
diff --git a/psi4/src/CMakeLists.txt b/psi4/src/CMakeLists.txt
index da11518..b287b0d 100644
--- a/psi4/src/CMakeLists.txt
+++ b/psi4/src/CMakeLists.txt
@@ -134,6 +134,6 @@ message(STATUS "Psi4 rpath: ${psi4_RPATH}")
 set_target_properties(core PROPERTIES PREFIX "${PYTHON_MODULE_PREFIX}"  # for python module
                            OUTPUT_NAME core
                            EXPORT_NAME core
-                           SUFFIX "${PYTHON_MODULE_EXTENSION}" # for python module
+                           #SUFFIX "${PYTHON_MODULE_EXTENSION}" # for python module
                            INSTALL_RPATH "${psi4_RPATH}"
                            BUILD_WITH_INSTALL_RPATH ON)
diff --git a/psi4/src/create_new_plugin.cc b/psi4/src/create_new_plugin.cc
index 3734a7b..6f2bde2 100644
--- a/psi4/src/create_new_plugin.cc
+++ b/psi4/src/create_new_plugin.cc
@@ -32,6 +32,7 @@
 #include <regex>
 #include <sstream>
 #include <string>
+#include <iterator>
 
 #include "psi4/psi4-dec.h"
```

**Comment by susilehtola** [comment]
Thank you!! That fixed it.

**Comment by mbanck** [comment]
For reference, Debian fixed this slightly differently: https://salsa.debian.org/debichem-team/psi4/-/blob/master/debian/patches/cmake_pymodulesuffix.patch

```
--- a/cmake/FindPythonLibsNew.cmake
+++ b/cmake/FindPythonLibsNew.cmake
@@ -78,7 +78,7 @@
 print(sys.prefix);
 print(s.get_python_inc(plat_specific=True));
 print(s.get_python_lib(plat_specific=True));
-print(s.get_config_var('SO'));
+print(s.get_config_var('SO') or s.get_config_var('EXT_SUFFIX'));
 print(hasattr(sys, 'gettotalrefcount')+0);
 print(struct.calcsize('@P'));
 print(s.get_config_var('LDVERSION') or s.get_config_var('VERSION'));
```
