### ISSUE TITLE
Tests fail when project is built from from the tarball

### ISSUE THREAD

**Issue by yurivict** [psi4/psi4#2687]
```
180/488 Testing: dft3
180/488 Test: dft3
Command: "/usr/local/bin/python3.9" "/disk-samsung/freebsd-ports/science/psi4/work/psi4-1.6.1/tests/runtest.py" "/disk-samsung/freebsd-ports/science/psi4/work/psi4-1.6.1/tests/dft3/input.dat" "/disk-samsung/freebsd-ports/science/psi4/work/.build/testresults.log" "/disk-samsung/freebsd-ports/science/psi4/work/psi4-1.6.1" "/disk-samsung/freebsd-ports/science/psi4/work/.build/tests/dft3/output.dat" "/disk-samsung/freebsd-ports/science/psi4/work/.build/stage/bin/psi4" "/disk-samsung/freebsd-ports/science/psi4/work/.build/stage/share/psi4" "/disk-samsung/freebsd-ports/science/psi4/work/.build/stage/lib/"
Directory: /disk-samsung/freebsd-ports/science/psi4/work/.build/tests/dft3
"dft3" start time: Aug 15 01:57 PDT
Output:
----------------------------------------------------------
Traceback (most recent call last):
  File "/disk-samsung/freebsd-ports/science/psi4/work/.build/stage/bin/psi4", line 188, in <module>
    import psi4  # isort:skip
  File "/disk-samsung/freebsd-ports/science/psi4/work/.build/stage/lib/psi4/__init__.py", line 76, in <module>
    from .driver import endorsed_plugins
  File "/disk-samsung/freebsd-ports/science/psi4/work/.build/stage/lib/psi4/driver/__init__.py", line 61, in <module>
    from psi4.driver import schema_wrapper
  File "/disk-samsung/freebsd-ports/science/psi4/work/.build/stage/lib/psi4/driver/schema_wrapper.py", line 50, in <module>
    from psi4.header import print_header
  File "/disk-samsung/freebsd-ports/science/psi4/work/.build/stage/lib/psi4/header.py", line 37, in <module>
    raise TypeError(
TypeError: Using custom build without tags. Please pull git tags with `git pull origin master --tags`. If building from source, `git fetch upstream "refs/tags/*:refs/tags/*"`.
Exit Status: overall (1)
<end of output>
Test time =   2.55 sec
----------------------------------------------------------
Test Failed.
"dft3" end time: Aug 15 01:57 PDT
"dft3" time elapsed: 00:00:02
----------------------------------------------------------

```

The port is always built from the tarball. It should be possible to run tests too.

**Comment by Tenshi65535** [comment]
Found the same problem. Have you got any solutions?

**Comment by yurivict** [comment]
No.

**Comment by TiborGY** [comment]
I have also encountered this occasionally. I do not know exactly what causes this and how, but doing a git clone can result in a folder with missing or wrong (?) git tags. I have found a workaround, but I have not invested the effort required to understand what it does:
`git fetch https://github.com/psi4/psi4.git "refs/tags/*:refs/tags/*"`

**Comment by TiborGY** [comment]
PS: you have to execute this and fetch the tags before the build, IIRC tags get "baked in" during the build

**Comment by yurivict** [comment]
Tarballs downloaded from GitHub are not git repositories. We use them in FreeBSD ports.
Nothing important should be hard-wired to Git during build/tests.

**Comment by loriab** [comment]
> Tarballs downloaded from GitHub are not git repositories. We use them in FreeBSD ports.
Nothing important should be hard-wired to Git during build/tests.

I agree broadly, though I'd sacrifice it to get fine-grain versioning for cross-project communication if needed :-)

The way psi is set up now, if the buildsys detects that it's not a git repo, it substitutes some generic most-recent-tag info and proceeds, so that one gets a working build. When I try, it works as planned:

acquire tarball
```
> curl -L  https://github.com/psi4/psi4/tarball/master -o psi4_v17.tgz
```
configure and build -- it detects "no git"
```
# configure (all req'd deps detected except optking to be build from src)
> cmake --build . -j12
...
[ 88%] Performing build step for 'psi4-core'
[  1%] Generating version info
[  1%] Building CXX object src/psi4/lib3index/CMakeFiles/3index.dir/dftensor.cc.o
...
[  2%] Building CXX object src/CMakeFiles/l2export.dir/export_mints.cc.o
Blindly (no git) accepting release version: 1.7+6ce35a5 (recorded)
1.7 {} 6ce35a5 1.7.0.0  release 1.7 <-- 1.7+6ce35a5
[  2%] Built target update_version
[  2%] Building CXX object src/psi4/libciomr/CMakeFiles/ciomr.dir/dsyev_ascending.cc.o
...
```
version computes and simple test, distributed driver tests, and dftd3 addon tests work ok
```
> stage/bin/psi4 --psiapi  # execute results
>>> stage/bin/psi4 --version
1.7
>>> ctest -R tu1
Test project /psi/gits/tarbuild/psi4-psi4-4d94910/objdir-py310
    Start 426: tu1-h2o-energy
1/1 Test #426: tu1-h2o-energy ...................   Passed    1.65 sec

100% tests passed, 0 tests failed out of 1
>>> ctest -R ddd
Test project /psi/gits/tarbuild/psi4-psi4-4d94910/objdir-py310
    Start 479: ddd-deriv
1/2 Test #479: ddd-deriv ........................   Passed   13.18 sec
    Start 481: ddd-function-kwargs
2/2 Test #481: ddd-function-kwargs ..............   Passed  170.20 sec

100% tests passed, 0 tests failed out of 2
>>> ctest -R dftd3
Test project /psi/gits/tarbuild/psi4-psi4-4d94910/objdir-py310
    Start 510: dftd3-energy
1/5 Test #510: dftd3-energy .....................   Passed   24.64 sec
    Start 511: dftd3-grad
2/5 Test #511: dftd3-grad .......................   Passed   11.33 sec
    Start 512: dftd3-psithon2
3/5 Test #512: dftd3-psithon2 ...................   Passed   13.39 sec
    Start 513: dftd3-version
4/5 Test #513: dftd3-version ....................   Passed   27.06 sec
    Start 514: dftd3-nbody-cp-gradient
5/5 Test #514: dftd3-nbody-cp-gradient ..........   Passed   33.83 sec

100% tests passed, 0 tests failed out of 5
```
version control files have stuff in src and built forms
```
> cat ../psi4/metadata.py 
__version__ = '1.7'
__version_long = '1.7+6ce35a5'
__version_upcoming_annotated_v_tag = '1.8a1'

def version_formatter(dummy):
    return '(inplace)'
> cat stage/lib/psi4/metadata.py 
__version__ = '1.7'
__version_branch_name = ''
__version_cmake = '1.7.0.0'
__version_is_clean = 'True'
__version_last_release = '1.7'
__version_long = '1.7+6ce35a5'
__version_prerelease = 'False'
__version_release = 'True'

def version_formatter(formatstring='{version}'):
    if formatstring == 'all':
        formatstring = '{version} {{{branch}}} {githash} {cmake} {clean} {release} {lastrel} <-- {versionlong}'

    release = 'release' if (__version_release == 'True') else ('prerelease' if (__version_prerelease == 'True') else '')

    ans = formatstring.format(version=__version__,
                              versionlong=__version_long,
                              githash=__version_long[len(__version__)+1:],
                              clean='' if __version_is_clean == 'True' else 'dirty',
                              branch=__version_branch_name,
                              lastrel=__version_last_release,
                              cmake=__version_cmake,
                              release=release)
    return ans

if __name__ == '__main__':
    print(version_formatter(formatstring='all'))
```

So I think tarballs are roughly still working. But I can totally believe that either I'm working in an edge case or the two of you have found one. My closest suspects:
* perhaps you're in a repo that isn't the psi repo. I bet that'd defeat https://github.com/psi4/psi4/blob/master/psi4/versioner.py#L50 that switches the version logic from git to tarball
* that version logic is tested for release tarballs only, not tarballs of random commits
* the increasing dependency on qcengine (which arose long after the versioning system design) for finite difference and dispersion depends a lot on computing the psi4 (and other) versions. Hence the "pull tags" message. I can believe there's a way that communication breaks down.

I'd suggest you compare commands and cat-ed files and see where the discrepancy arises.
