### ISSUE TITLE
Error computing atomization energy of Al atom

### ISSUE THREAD

**Issue by dspoel** [psi4/psi4#2858]
I get the following output with request to submit a bug report:
```
Threads set to 4 by Python driver.

  Memory set to  11.176 GiB by Python driver.
Traceback (most recent call last):
  File "/var/lib/slurm/slurmd/job23834122/slurm_script", line 16, in <module>
    myener = psi4.energy("WB97X/aug-cc-pvqz", molecule=geom)
  File "/home/x_davva/wd/miniconda3/envs/ACT/lib/python3.9/site-packages/psi4/driver/driver.py", line 501, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/x_davva/wd/miniconda3/envs/ACT/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 2455, in run_scf
    scf_wfn = scf_helper(name, post_scf=False, **kwargs)
  File "/home/x_davva/wd/miniconda3/envs/ACT/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 1670, in scf_helper
    e_scf = scf_wfn.compute_energy()
  File "/home/x_davva/wd/miniconda3/envs/ACT/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 86, in scf_compute_energy
    self.iterations()
  File "/home/x_davva/wd/miniconda3/envs/ACT/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 429, in scf_iterate
    self.form_C()
RuntimeError: 
Fatal Error: Count 8 alpha electrons, expected 7.
This is a bug. Please file a report.
Error occurred in file: /scratch/psilocaluser/conda-builds/psi4-multiout_1657298395608/work/psi4/src/psi4/libscf_solver/hf.cc on line: 482
```
from this input
```
#!/usr/bin/env python3
import psi4 as psi4
psi4.core.set_num_threads(4)
psi4.set_memory(12000000000)
psi4.core.set_output_file('Al.out', False)
psi4_io = psi4.core.IOManager.shared_object()
psi4_io.set_default_path('/tmp/')
geometry= """
0 2
 Al 0 0 0
"""
psi4.set_options({'reference': 'uhf'})
geom   = psi4.geometry(geometry)
myener = psi4.energy("WB97X/aug-cc-pvqz", molecule=geom)
with open('atomization_energy.dat', 'w') as aefile:
    aefile.write('Atomization energy %g\n' % myener)
```

**Comment by JonathonMisiewicz** [comment]
This job completes just fine for me on the current master, although with some entirely reasonable warning messages. What version of Psi4 are you using? My guess is that you're using 1.7, and #2619 fixed this bug.

**Comment by loriab** [comment]
> using 1.7 or earlier

1.6 or earlier, I think, if 2619 was merged Jun '22. That is, 1.7 should include that fix.
