### ISSUE TITLE
Runtime failures with numpy-1.24

### ISSUE THREAD

**Issue by mbanck** [psi4/psi4#2865]
NumPY-1.24.0 got released in late December, and Debian's psi4 (still based on 1.3 due to LibInt) now fails (most of) the testsuite like this:

```
133/143 Test #406: python-curve .....................***Failed    0.42 sec
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/tests/python/curve/input.py", line 21, in <module>
    out[d] = psi4.energy('SCF', molecule=geom)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<<PKGBUILDDIR>>/builddir/stage/lib/x86_64-linux-gnu/psi4/driver/driver.py", line 556, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<<PKGBUILDDIR>>/builddir/stage/lib/x86_64-linux-gnu/psi4/driver/procrouting/proc.py", line 2002, in run_scf
    scf_wfn = scf_helper(name, post_scf=False, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<<PKGBUILDDIR>>/builddir/stage/lib/x86_64-linux-gnu/psi4/driver/procrouting/proc.py", line 1276, in scf_helper
    base_wfn = core.Wavefunction.build(scf_molecule, core.get_global_option('BASIS'))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<<PKGBUILDDIR>>/builddir/stage/lib/x86_64-linux-gnu/psi4/driver/p4util/python_helpers.py", line 115, in _core_wavefunction_build
    basis = core.BasisSet.build(mol, "ORBITAL", basis)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<<PKGBUILDDIR>>/builddir/stage/lib/x86_64-linux-gnu/psi4/driver/p4util/python_helpers.py", line 79, in _pybuild_basis
    bs, basisdict = qcdb.BasisSet.pyconstruct(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<<PKGBUILDDIR>>/builddir/stage/lib/x86_64-linux-gnu/psi4/driver/qcdb/libmintsbasisset.py", line 635, in pyconstruct
    mol = Molecule(mol)
          ^^^^^^^^^^^^^
  File "/<<PKGBUILDDIR>>/builddir/stage/lib/x86_64-linux-gnu/psi4/driver/qcdb/molecule.py", line 143, in __init__
    self._internal_from_dict(molrec, verbose=verbose)
  File "/<<PKGBUILDDIR>>/builddir/stage/lib/x86_64-linux-gnu/psi4/driver/qcdb/molecule.py", line 1529, in _internal_from_dict
    fragment_separators = np.array(molrec['fragment_separators'], dtype=np.int)
                                                                        ^^^^^^
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'int'. Did you mean: 'inf'?
Exit Status: infile ( 1 ); autotest ( None ); sowreap ( None ); overall ( 1 )
```

The important part (I think) being `AttributeError: module 'numpy' has no attribute 'int'. Did you mean: 'inf'?`. According to the Debian bug (<https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1027216>), "This is because, numpy upstream in
1.24.0, finally decided to expire <https://numpy.org/doc/stable/release/1.24.0-notes.html#:~:text=The%20deprecation%20for%20the%20aliases> some deprecations introduced in 1.20.0 <https://numpy.org/doc/stable/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated> (released almost 2 years ago).".

It this a known problem, and possibly already fixed in master or later branches? At least the one quoted above is unchanged since 1.3 at least.

**Comment by mbanck** [comment]
Ok, the other occurances were fixed in master in #2845

**Comment by loriab** [comment]
Yes, I've been updating them as I notice them, and 2845 is the most recent. afaik, there aren't any outstanding expired types. Sorry about the poor commit message - it was part of a big docs update.

If you're still working from v1.3, https://github.com/psi4/psi4/issues/2656#issuecomment-1299120848 may be useful patches, too. Thanks for working on keeping this old version going.

On the moving-past-v1.3 front, I now have a version of Libint2 that has solid harmonic ordering runtime-switchable, so a single build could work for all open-source consumers, finally including psi. But that'll require upstream acceptance into L2 and new versions (maybe could get away with rebuild?) of the quantum chem packages. So nothing imminent, but some progress.

**Comment by loriab** [comment]
Re https://github.com/psi4/psi4/pull/2845#issuecomment-1407771245, yes, perhaps it should be `double`. All it needs is a C double, and I thought Py float was that. Another reading of https://numpy.org/doc/stable/user/basics.types.html isn't helping.

Searching again, it looks like the below are the remaining offenders that should be replaced with plain `double` or `int`.
```
psi4/driver/driver_findif.py:        return np.zeros((nat3, nat3), dtype=np.float64)
psi4/driver/ipi_broker.py:        return self._force, np.float64(self._potential)
psi4/driver/ipi_broker.py:        self._nat = np.int32(len(atoms))
psi4/driver/p4util/fchk.py:        dtype = np.float64
psi4/driver/p4util/fchk.py:        dtype = np.float64
psi4/driver/p4util/numpy_helper.py:        ret.nph[n].flat[:] = np.frombuffer(json_data["data"][n], dtype=np.double)
```

**Comment by mbanck** [comment]
I had to add some additional hunks, for the no longer existing `datastructures.py` and `scipy_hungarian.py`, not sure those are the correct fixes, but the testsuite (as far as Debian runs it, 143 test cases at least) now passes except for a numerical issue in `matrix1` (`Eigenvectors: computed value (0.0291933) does not match (-0.02919332316478252).`) and some other python problems in `pywrap-align{,-chiral`:

```
  File "/<<PKGBUILDDIR>>/builddir/stage/lib/x86_64-linux-gnu/psi4/driver/qcdb/util/gph_uno_bipartite.py", line 109, in _enumMaximumMatching
    if g.node[kk]['bipartite'] == 0:
       ^^^^^^

AttributeError: 'Graph' object has no attribute 'node'
```

For completeness, those are the additional hunks:

```
Index: psi4/psi4/driver/qcdb/datastructures.py
===================================================================
--- psi4.orig/psi4/driver/qcdb/datastructures.py
+++ psi4/psi4/driver/qcdb/datastructures.py
@@ -58,11 +58,11 @@ class QCAspect(collections.namedtuple('Q
         for d in ['doi', 'comment', 'glossary']:
             dicary.pop(d)
         if isinstance(self.data, (np.ndarray, np.number)):
-            if self.data.dtype == np.complex:
+            if self.data.dtype == complex:
                 dicary['data'] = [dicary['data'].real.tolist(), dicary['data'].imag.tolist()]
             else:
                 dicary['data'] = dicary['data'].tolist()
-        elif isinstance(self.data, (complex, np.complex)):
+        elif isinstance(self.data, (complex, complex)):
             dicary['data'] = [self.data.real, self.data.imag]
 
         return dicary
Index: psi4/psi4/driver/qcdb/util/scipy_hungarian.py
===================================================================
--- psi4.orig/psi4/driver/qcdb/util/scipy_hungarian.py
+++ psi4/psi4/driver/qcdb/util/scipy_hungarian.py
@@ -93,14 +93,14 @@ def linear_sum_assignment(cost_matrix, r
                          % (cost_matrix.shape,))
 
     if not (np.issubdtype(cost_matrix.dtype, np.number) or
-            cost_matrix.dtype == np.dtype(np.bool)):
+            cost_matrix.dtype == np.dtype(bool)):
         raise ValueError("expected a matrix containing numerical entries, got %s"
                          % (cost_matrix.dtype,))
 
     if np.any(np.isinf(cost_matrix) | np.isnan(cost_matrix)):
         raise ValueError("matrix contains invalid numeric entries")
 
-    if cost_matrix.dtype == np.dtype(np.bool):
+    if cost_matrix.dtype == np.dtype(bool):
         cost_matrix = cost_matrix.astype(np.int)
 
     # The algorithm expects more columns than rows in the cost matrix.
```

**Comment by mbanck** [comment]
> Re [#2845 (comment)](https://github.com/psi4/psi4/pull/2845#issuecomment-1407771245), yes, perhaps it should be `double`. All it needs is a C double, and I thought Py float was that. Another reading of https://numpy.org/doc/stable/user/basics.types.html isn't helping.

Sorry, I wasn't very clear - I meant that other than `np.float`, there's also some `np.double` hanging around, in particular this one:

> ```
> psi4/driver/p4util/numpy_helper.py:        ret.nph[n].flat[:] = np.frombuffer(json_data["data"][n], dtype=np.double)
> ```

**Comment by loriab** [comment]
Glad to hear it's mostly working
* https://github.com/psi4/psi4/pull/2829 might help `matrix1`
* yes, the hungarian file had that change and now resides https://github.com/MolSSI/QCElemental/blob/master/qcelemental/util/scipy_hungarian.py#L103
* the datastructures is refactored into a different class https://github.com/MolSSI/QCElemental/blob/master/qcelemental/datum.py#L45 but your changes are good
* it looks like the uno_bipartite file has had some updates, incl. node -> nodes https://github.com/MolSSI/QCElemental/blob/master/qcelemental/util/gph_uno_bipartite.py#L108
