### ISSUE TITLE
Single-Atom Optimization Not Intercepted

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#2971]
```
molecule {
He
}

optimize("scf/cc-pvdz")
```

on `1.8a1.dev57` gives

```
Traceback (most recent call last):
  File "/Users/jonathonmisiewicz/psi4/objdir/stage/bin//psi4", line 345, in <module>
    exec(content)
  File "<string>", line 22, in <module>
  File "/Users/jonathonmisiewicz/psi4/objdir/stage/lib/psi4/driver/driver.py", line 1272, in optimize
    opt_object.take_step()
  File "/Users/jonathonmisiewicz/psi4/objdir/stage/lib/optking/opt_helper.py", line 174, in take_step
    self.dq, self.step_str = self.opt_manager.take_step(self.fq, self._Hq, self.E, return_str=True)
  File "/Users/jonathonmisiewicz/psi4/objdir/stage/lib/optking/optimize.py", line 232, in take_step
    achieved_dq, returned_str = self.opt_method.take_step(fq, H, energy, return_str=True)

ValueError: not enough values to unpack (expected 2, got 0)
```

Something is wrong (or outright missing) for the single-atom case, which should be a straight "no geometry to optimize."

**Comment by loriab** [comment]
I thought this was fixed long ago, but upon testing, that must have been `gradient`, `hessian`, and `frequency`, as `optimize` is indeed faulty.

@psi-rking, I can intercept this in the psi driver, but would you prefer to intercept in optking?

**Comment by psi-rking** [comment]
@AlexHeide , do you think this calls for a `"success": True` in the json output?
I need to think a bit to rule out the possibility (given constraints, user-defined forces, etc.,) that someone might not actually want to do this.  
Meanwhile, within the context of psi4, I think the psi driver catching it is good.  @AlexHeide , do you agree with that?

**Comment by AlexHeide** [comment]
I think I would leave the `OptimizationResult` with `"success": "false"`. Adding something optking side would be better imo especially if the goal is just a comprehensible error message.

**Comment by psi-rking** [comment]
Agreed we'll catch it and print a clear message.  However, I'm thinking of a user sending a list of molecules that includes some atoms through the optimizer, and so whether this is an "error", and if "false" is going to interrupt desirable processes.

**Comment by AlexHeide** [comment]
I think in terms of trying not to interrupt a high throughput scenario that we should still return an error in the `OptimizationResult` and set `"success": "false"` to warn the user that trying to grab something from `"return_result"` won't work. If we're giving json output back, optking failing shouldn't result in an error being returned to the user. They should be able to keep going naturally. If they try to check `'return_result'` though without checking for success they'd likely get a `NoneType` error or something which could kill whatever scripts they're running. The question in my mind is whether we should actually run a simple energy calc at the requested level of theory an place the `AtomicResult` in the `"trajectory"` so that they have some results to work with.

**Comment by psi-rking** [comment]
@AlexHeide, your suggestion to compute an energy is an excellent one.  How do we do it?  I'm available to work on this, but not sure where to start putting the catch.  Feel free to cue me on Slack if that's more convenient.

**Comment by psi-rking** [comment]
@AlexHeide , I'm working on it.  I should have a pull request for optking, with at least a start up soon.

**Comment by psi-rking** [comment]
Should be resolved by
[https://github.com/psi-rking/optking/pull/84]

**Comment by JonathonMisiewicz** [comment]
Great! Once that's in and in the conda stack, let's add a test case before closing this.
