### ISSUE TITLE
Mamba installation of Psi4 1.8 on linux misconfigures PSIDATADIR

### ISSUE THREAD

**Issue by lilyminium** [psi4/psi4#2993]
Thanks for putting Psi4 on conda-forge, this is very exciting. However, I noticed that creating an environment out of the box with mamba using conda-forge Psi4 seems to set PSIDATADIR to a build directory. (I'll try with conda as well).

```shell
$ mamba create --name psi4-1.8-py39 python=3.9 psi4=1.8 -c conda-forge/label/libint_dev -c conda-forge
$ conda activate psi4-1.8-py39
$ psi4 --version
Traceback (most recent call last):
  File "/home/lilywang/miniconda3/envs/psi4-1.8-py39/bin/psi4", line 213, in <module>
    import psi4  # isort:skip
  File "/home/lilywang/miniconda3/envs/psi4-1.8-py39/lib/python3.9/site-packages/psi4/__init__.py", line 64, in <module>
    raise KeyError(f"Unable to read the Psi4 Python folder - check the PSIDATADIR environmental variable - current value is {str(data_dir)}")
KeyError: 'Unable to read the Psi4 Python folder - check the PSIDATADIR environmental variable - current value is /lila/home/conda/feedstock_root/build_artifacts/psi4_1683815705089/work/build/stage/share/psi4'
```

I tried 3.11 as well:

```shell
$ mamba create --name psi4-1.8 psi4 -c conda-forge/label/libint_dev -c conda-forge
$ conda activate psi4-1.8
$ psi4 --version
Traceback (most recent call last):
  File "/home/lilywang/miniconda3/envs/psi4-1.8/bin/psi4", line 213, in <module>
    import psi4  # isort:skip
    ^^^^^^^^^^^
  File "/home/lilywang/miniconda3/envs/psi4-1.8/lib/python3.11/site-packages/psi4/__init__.py", line 64, in <module>
    raise KeyError(f"Unable to read the Psi4 Python folder - check the PSIDATADIR environmental variable - current value is {str(data_dir)}")
KeyError: 'Unable to read the Psi4 Python folder - check the PSIDATADIR environmental variable - current value is /lila/home/conda/feedstock_root/build_artifacts/psi4_1683815712644/work/build/stage/share/psi4'
```
Manually setting PSIDATADIR seems to fix things, but the docs actively recommend against doing that:

```
$ export PSIDATADIR=~/miniconda3/envs/psi4-1.8/share/psi4
$ psi4 --version
1.8
```

https://psicode.org/psi4manual/master/build_planning.html#why-not-to-set-psidatadir

**Comment by lilyminium** [comment]
Hm, I can't reproduce this on a different computer anymore -- must be something with conda on the first one, then. Sorry for the unnecessary report.
