### ISSUE TITLE
`pytest` not found during wb97x-d calculation

### ISSUE THREAD

**Issue by q-posev** [psi4/psi4#3003]
Hello,

Somehow the `pytest` module is imported during the DFT calculation with dispersion correction and crashes Psi4 if `pytest` is missing. It can be fixed simply by installing the missing module, but I thought that it's worth reporting still in order to patch the packaging.

Psi4: v.1.8 from `conda-forge` (installed in a clean env using ` conda install psi4 python=3.10 -c conda-forge/label/libint_dev -c conda-forge `)

Code to reproduce:

```python
molecule {
0 1
O   0.0  0.5  0.0
H   0.5  0.0  0.0
H  -0.5  0.0  0.0

no_reorient
symmetry c1
}

memory 8GB
set_num_threads(2)
set freeze_core True

E, wfn = energy('wb97x-d/6-311g**',return_wfn=True)
```

Fails with the following error:

```
Traceback (most recent call last):
  File "/home/q-posev/miniconda3/envs/psi4-v18/bin/psi4", line 372, in <module>
    exec(content)
  File "<string>", line 31, in <module>
  File "/home/q-posev/miniconda3/envs/psi4-v18/lib/python3.10/site-packages/psi4/driver/driver.py", line 526, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/q-posev/miniconda3/envs/psi4-v18/lib/python3.10/site-packages/psi4/driver/procrouting/proc.py", line 2574, in run_scf
    scf_wfn = scf_helper(name, post_scf=False, **kwargs)
  File "/home/q-posev/miniconda3/envs/psi4-v18/lib/python3.10/site-packages/psi4/driver/procrouting/proc.py", line 1769, in scf_helper
    scf_wfn = scf_wavefunction_factory(name, base_wfn, core.get_option('SCF', 'REFERENCE'), **kwargs)
  File "/home/q-posev/miniconda3/envs/psi4-v18/lib/python3.10/site-packages/psi4/driver/procrouting/proc.py", line 1430, in scf_wavefunction_factory
    superfunc, _disp_functor = build_functional_and_disp(name, restricted=(reference in ["RKS", "RHF"]), **kwargs)
  File "/home/q-posev/miniconda3/envs/psi4-v18/lib/python3.10/site-packages/psi4/driver/procrouting/proc.py", line 1407, in build_functional_and_disp
    _disp_functor = empirical_dispersion.EmpiricalDispersion(name_hint=superfunc.name(),
  File "/home/q-posev/miniconda3/envs/psi4-v18/lib/python3.10/site-packages/psi4/driver/procrouting/empirical_dispersion.py", line 172, in __init__
    capable_engines_for_disp = _capable_engines_for_disp()
  File "/home/q-posev/miniconda3/envs/psi4-v18/lib/python3.10/site-packages/psi4/driver/procrouting/empirical_dispersion.py", line 61, in _capable_engines_for_disp
    from qcengine.testing import _programs as _programs_qcng
  File "/home/q-posev/miniconda3/envs/psi4-v18/lib/python3.10/site-packages/qcengine/testing.py", line 8, in <module>
    import pytest

ModuleNotFoundError: No module named 'pytest'


!--------------------------------!
!                                !
!  No module named 'pytest'      !
!                                !
!--------------------------------!
```

**Comment by loriab** [comment]
Good point. In pre-cf days, I included pytest with the psi4 package, so that hid problem until recently. I'll backport this to v1.8.1.
