### ISSUE TITLE
FindPythonLibsNew does not work in Python 3.12

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#3020]
Rebuilding Psi4 1.3.2 in Fedora rawhide fails with
```
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.12", minimum required is "3.5") 
CMake Error at cmake/FindPythonLibsNew.cmake:94 (message):
  Python config failure:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named 'distutils'
Call Stack (most recent call first):
  CMakeLists.txt:168 (find_package)
-- Configuring incomplete, errors occurred!
error: Bad exit status from /var/tmp/rpm-tmp.sQzcRh (%build)
```
The issue here is that distutils was deprecated in Python 3.10 and marked for deletion in 3.12:
https://docs.python.org/3/whatsnew/3.10.html#distutils-deprecated

The file in master has been slightly updated, but still features the use of distutils, so this issue is likely present on the master branch as well.

**Comment by loriab** [comment]
FindPythonLibsNew should be removed from the repo -- I guess we left it as a transition. Since https://github.com/psi4/psi4/pull/2048 for v1.4, it's been replaced by the cmake native detection. Is it feasible to apply that to v1.3.2 as a patch? If a fresh edit is easier, switching `find_package(3.7 PythonLibsNew)` for `find_package(Python 3.7 EXACT COMPONENTS Interpreter Development REQUIRED)` in two places (top-level CM and psi4/CM) and replacing all `PYTHON_` with `Python_` in CM files should do most of the trick.

Good news is that there's no other active distutils in master, so there should be a workaround to anything else from 1.3.2 .

**Comment by susilehtola** [comment]
There's another problem: using the standard Python search, I get the error
```
-- Found HDF5: /usr/lib64/libhdf5.so;... (found version 1.12.1)
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Found pybind11: /usr/include (found version 2.11.1)
-- Found CheMPS2: /usr/lib64/libchemps2.so.3 (found version 1.8.9)
-- Found gau2grid: /usr/lib64/libgg.so.1 (found version 1.3.1)
CMake Error at cmake/FindPythonModule.cmake:82 (if):
  if given arguments:
    "STREQUAL" "True"
  Unknown arguments specified
Call Stack (most recent call first):
  external/upstream/qcelemental/CMakeLists.txt:3 (find_python_module)
-- Configuring incomplete, errors occurred!
RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.vyDLbO (%build)
    Bad exit status from /var/tmp/rpm-tmp.vyDLbO (%build)
Child return code was: 1
```
and sure enough 
```
external/upstream/qcelemental/CMakeLists.txt:    include(FindPythonModule)
external/downstream/snsmp2/CMakeLists.txt:        include(FindPythonModule)
```

**Comment by loriab** [comment]
FindPythonModule is a home cooked file under cmake/ . I can investigate in a couple hours or you can see if there's any difference btwn it and master. That error looks like it might just need a cmake policy set.

**Comment by susilehtola** [comment]
@loriab please do

**Comment by loriab** [comment]
First, you've `s/PYTHON_EXECUTABLE/Python_EXECUTABLE/g cmake/FindPythonModule.cmake` already probably.

maybe patch it with to get more info out of the error.

```
diff --git a/cmake/FindPythonModule.cmake b/cmake/FindPythonModule.cmake
index 2b6f93172..b2061b8a6 100644
--- a/cmake/FindPythonModule.cmake
+++ b/cmake/FindPythonModule.cmake
@@ -77,8 +77,10 @@ macro(find_python_module module)
                                          print(parse_version('${${module}_VERSION}') ${_op} parse_version('${${module}_tgtver}'))"
                 RESULT_VARIABLE _${module}_verenuf_status
                 OUTPUT_VARIABLE _${module}_verenuf
-                ERROR_QUIET
+                #ERROR_QUIET
                 OUTPUT_STRIP_TRAILING_WHITESPACE)
+                message("_${module}_verenuf_status ${_${module}_verenuf_status}")
+                message("_${module}_verenuf ${_${module}_verenuf}")
                 if(NOT ${_${module}_verenuf_status})
                     if(${_${module}_verenuf} STREQUAL "True")
                         set(_${module}_requested_version_found "${Python_EXECUTABLE}")
```

and kill off the `QUIET` in external/upstream/qcelemental/CM

```
if(NOT (${CMAKE_DISABLE_FIND_PACKAGE_qcelemental}))
    include(FindPythonModule)
    find_python_module(qcelemental ATLEAST 0.24.0 QUIET)
endif()
```

But really, assuming you're detecting a qcel in path, the only part of external/upstream/qcelemental/CM that further cmake cares about is `    add_library(qcelemental_external INTERFACE)  # dummy`, so you could set that and bypass the FindPythonModule.cmake entirely.

**Comment by susilehtola** [comment]
I get
```
-- Could NOT find qcelemental (missing: _qcelemental_requested_version_found) 
```

**Comment by susilehtola** [comment]
And this is with the newest version of qcelemental.

**Comment by loriab** [comment]
I didn't find the right fedora build log yesterday, so if it's online and you want a minimal patch, I'd appreciate a link.

But, if you don't mind a heavy patch, the below for external/upstream/qcelemental/CMakeLists.txt worked fine locally for me just now. That is, psi4 (master) configured, _didn't_ build qcel, and detected it fine at runtime.

```
#if(NOT (${CMAKE_DISABLE_FIND_PACKAGE_qcelemental}))
#    include(FindPythonModule)
#    find_python_module(qcelemental ATLEAST 0.24.0 QUIET)
#endif()
#
#if(${qcelemental_FOUND})
#    message(STATUS "${Cyan}Found qcelemental${ColourReset}: ${PY_qcelemental} (found version ${qcelemental_VERSION})")
    add_library(qcelemental_external INTERFACE)  # dummy
#
#else()
#    if(${CMAKE_INSIST_FIND_PACKAGE_qcelemental})
#        message(FATAL_ERROR "Suitable qcelemental could not be externally located as user insists")
#    endif()
#
#    include(ExternalProject)
#    message(STATUS "Suitable qcelemental could not be located, ${Magenta}Building qcelemental${ColourReset} instead.")
#
#    file(TO_NATIVE_PATH "${STAGED_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}${PYMOD_INSTALL_LIBDIR}" _install_lib)
#
#    ExternalProject_Add(qcelemental_external
#        BUILD_ALWAYS 1
#        URL https://github.com/MolSSI/QCElemental/archive/v0.25.1.tar.gz
#        CONFIGURE_COMMAND ""
#        UPDATE_COMMAND ""
#        BUILD_COMMAND ${Python_EXECUTABLE} setup.py build
#        BUILD_IN_SOURCE 1
#        INSTALL_COMMAND ${Python_EXECUTABLE} setup.py install
#                                                      --record=record.txt
#                                                      --single-version-externally-managed
#                                                      --install-lib=${_install_lib})
#endif()
```

**Comment by susilehtola** [comment]
So, next error
```
CMake Warning (dev) at cmake/FindPythonLibsNew.cmake:59 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.
Call Stack (most recent call first):
  CMakeLists.txt:168 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.12", minimum required is "3.5") 
CMake Error at cmake/FindPythonLibsNew.cmake:94 (message):
  Python config failure:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named 'distutils'
Call Stack (most recent call first):
  CMakeLists.txt:168 (find_package)
-- Configuring incomplete, errors occurred!
```

**Comment by loriab** [comment]
FindPythonInterp/FindPythonLibs/FindPythonLibsNew should never be called after the switch in https://github.com/psi4/psi4/issues/3020#issuecomment-1667105438 to `find_package(Python`. Can you determine what's still calling the old detection? One guess is that not just top-level/CM but top-level/psi4/CM needs the adjustment and the call has to come before pb11 detection https://github.com/psi4/psi4/blob/b0e621fc287b60010275fbe22f7e9337e855e1df/psi4/CMakeLists.txt#L60 .

**Comment by susilehtola** [comment]
```
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE) (Required is at
  least version "3.6")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindPythonInterp.cmake:182 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /usr/share/cmake/pybind11/FindPythonLibsNew.cmake:98 (find_package)
  /usr/share/cmake/pybind11/pybind11Tools.cmake:50 (find_package)
  /usr/share/cmake/pybind11/pybind11Common.cmake:188 (include)
  /usr/share/cmake/pybind11/pybind11Config.cmake:250 (include)
  CMakeLists.txt:60 (find_package)
```
Looks like the error originates from `psi4/CMakeLists.txt`
```
find_package(pybind11 2.2.2 CONFIG REQUIRED)
```

**Comment by loriab** [comment]
Likely the snag is that "Classic" Python detection where pb11 calls PythonLibsNew is getting triggered instead of "New FindPython" mode. https://pybind11.readthedocs.io/en/stable/cmake/index.html#new-findpython-mode Maybe in addition to `find_package(Python)` to `find_package(pybind11)`, you can set `PYBIND11_FINDPYTHON` to `ON`.

**Comment by susilehtola** [comment]
That helped. Now
```
gmake[5]: *** [CMakeFiles/update_version.dir/build.make:71: CMakeFiles/update_version] Error 127
gmake[4]: *** [CMakeFiles/Makefile2:977: CMakeFiles/update_version.dir/all] Error 2
gmake[4]: *** Waiting for unfinished jobs....
```

**Comment by susilehtola** [comment]
Oh that might be because of `$(PYTHON_EXECUTABLE)` vs `$(Python_EXECUTABLE)`

**Comment by susilehtola** [comment]
Now I get
```
+ ctest -L smoketests
Test project /builddir/build/BUILD/psi4-1.3.2/redhat-linux-build/tests
      Start   7: casscf-sp
Could not find executable 
Looked in the following places:
Release/
Release/
Debug/
Debug/
MinSizeRel/
MinSizeRel/
RelWithDebInfo/
RelWithDebInfo/
Deployment/
Deployment/
Development/
Development/
 1/12 Test   #7: casscf-sp ........................***Not Run   0.00 sec
```
It did seem to install the executable, though.
https://koji.fedoraproject.org/koji/watchlogs?taskID=104800455

**Comment by loriab** [comment]
https://github.com/psi4/psi4/blob/master/cmake/TestingMacros.cmake#L45 might also need PYTHON_EXE -> Python_EXE

**Comment by susilehtola** [comment]
Yeah did that. Now got
```
+ ctest -L smoketests
Test project /builddir/build/BUILD/psi4-1.3.2/redhat-linux-build/tests
      Start   7: casscf-sp
 1/12 Test   #7: casscf-sp ........................***Failed    0.21 sec
      Start  22: cc1
 2/12 Test  #22: cc1 ..............................***Failed    0.06 sec
      Start 132: dfmp2-1
 3/12 Test #132: dfmp2-1 ..........................***Failed    0.06 sec
      Start 196: fcidump
 4/12 Test #196: fcidump ..........................***Failed    0.06 sec
      Start 330: sapt1
 5/12 Test #330: sapt1 ............................***Failed    0.06 sec
      Start 357: scf-property
 6/12 Test #357: scf-property .....................***Failed    0.06 sec
      Start 372: tu1-h2o-energy
 7/12 Test #372: tu1-h2o-energy ...................***Failed    0.05 sec
      Start 402: psi4numpy-rhf
 8/12 Test #402: psi4numpy-rhf ....................   Passed    4.50 sec
      Start 404: psi4numpy-rhf-hessian
 9/12 Test #404: psi4numpy-rhf-hessian ............   Passed    5.47 sec
      Start 409: python-energy
10/12 Test #409: python-energy ....................   Passed    1.99 sec
      Start 422: json-schema-1-gradient
11/12 Test #422: json-schema-1-gradient ...........   Passed    4.46 sec
      Start 424: chemps2-scf-n2
12/12 Test #424: chemps2-scf-n2 ...................***Failed    0.06 sec

33% tests passed, 8 tests failed out of 12

Label Time Summary:
addon         =   0.06 sec*proc (1 test)
cart          =   0.17 sec*proc (3 tests)
casscf        =   0.21 sec*proc (1 test)
cc            =   0.06 sec*proc (1 test)
chemps2       =   0.06 sec*proc (1 test)
df            =   0.06 sec*proc (1 test)
dfmp2         =   0.06 sec*proc (1 test)
fcidump       =   0.06 sec*proc (1 test)
json          =   4.46 sec*proc (1 test)
properties    =   0.06 sec*proc (1 test)
psi           =  17.03 sec*proc (12 tests)
psi4numpy     =   9.97 sec*proc (2 tests)
python        =   1.99 sec*proc (1 test)
quicktests    =  17.03 sec*proc (12 tests)
sapt          =   0.06 sec*proc (1 test)
scf           =   0.06 sec*proc (1 test)
smoketests    =  17.03 sec*proc (12 tests)
tutorial      =   0.05 sec*proc (1 test)

Total Test time (real) =  17.19 sec

The following tests FAILED:
	  7 - casscf-sp (Failed)
	 22 - cc1 (Failed)
	132 - dfmp2-1 (Failed)
	196 - fcidump (Failed)
	330 - sapt1 (Failed)
	357 - scf-property (Failed)
	372 - tu1-h2o-energy (Failed)
	424 - chemps2-scf-n2 (Failed)
Errors while running CTest
```
The casscf-sp error is
```
7/428 Test: casscf-sp
Command: "/usr/bin/python3.12" "/builddir/build/BUILD/psi4-1.3.2/tests/runtest.py" "/builddir/build/BUILD/psi4-1.3.2/tests/casscf-sp/input.dat" "/builddir/build/BUILD/psi4-1.3.2/redhat-linux
-build/testresults.log" "false" "/builddir/build/BUILD/psi4-1.3.2" "false" "/builddir/build/BUILD/psi4-1.3.2/redhat-linux-build/tests/casscf-sp/output.dat" "/builddir/build/BUILD/psi4-1.3.2/
redhat-linux-build/stage/bin/psi4" "/builddir/build/BUILD/psi4-1.3.2/redhat-linux-build/stage/share/psi4" "/builddir/build/BUILD/psi4-1.3.2/redhat-linux-build/stage/lib64/python3.12/site-pac
kages"
Directory: /builddir/build/BUILD/psi4-1.3.2/redhat-linux-build/tests/casscf-sp
"casscf-sp" start time: Aug 14 00:32 UTC
Output:
----------------------------------------------------------
Command ['/builddir/build/BUILD/psi4-1.3.2/redhat-linux-build/stage/bin/psi4', '/builddir/build/BUILD/psi4-1.3.2/tests/casscf-sp/input.dat', '/builddir/build/BUILD/psi4-1.3.2/redhat-linux-bu
ild/tests/casscf-sp/output.dat', '-l', '/builddir/build/BUILD/psi4-1.3.2/redhat-linux-build/stage/share/psi4'] execution failed: Exec format error
<end of output>
Test time =   0.21 sec
```

**Comment by loriab** [comment]
That's an odd pattern. The 4 that _are_ passing are those running with command `python`. The rest that _aren't_ passing are those running with command `psi4`, and those get their python from https://github.com/psi4/psi4/blob/master/psi4/run_psi4.py#L1

More commonly, the pass/fail pattern is reversed. If you haven't subbed that shebang, it's a great suspect.

**Comment by susilehtola** [comment]
Thanks! IT BUILDS!

**Comment by loriab** [comment]
Hooray! Thanks for keeping ol' v1.3.2 afloat and for pre-screening py312 for us.
