### ISSUE TITLE
Psi4 does not start on Mac

### ISSUE THREAD

**Issue by peastman** [psi4/psi4#3062]
I installed psi4 1.8.2 from conda-forge on macOS.  Here is the package information:

```
psi4                      1.8.2            py39h9c1326d_0    conda-forge
```

When I try to launch it, it immediately fails with an exception.

```
$ psi4
Traceback (most recent call last):
  File "/Users/peastman/miniconda3/envs/qcportal/bin/psi4", line 213, in <module>
    import psi4  # isort:skip
  File "/Users/peastman/miniconda3/envs/qcportal/lib/python3.9/site-packages/psi4/__init__.py", line 90, in <module>
    from .driver import endorsed_plugins
  File "/Users/peastman/miniconda3/envs/qcportal/lib/python3.9/site-packages/psi4/driver/__init__.py", line 56, in <module>
    from psi4.driver import gaussian_n
  File "/Users/peastman/miniconda3/envs/qcportal/lib/python3.9/site-packages/psi4/driver/gaussian_n.py", line 31, in <module>
    from psi4.driver import driver
  File "/Users/peastman/miniconda3/envs/qcportal/lib/python3.9/site-packages/psi4/driver/driver.py", line 49, in <module>
    from psi4.driver import driver_nbody
  File "/Users/peastman/miniconda3/envs/qcportal/lib/python3.9/site-packages/psi4/driver/driver_nbody.py", line 830, in <module>
    class ManyBodyComputer(BaseComputer):
  File "pydantic/main.py", line 204, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 488, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 419, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 534, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 728, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 778, in pydantic.fields.ModelField._create_sub_type
  File "pydantic/fields.py", line 419, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 534, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 728, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 778, in pydantic.fields.ModelField._create_sub_type
  File "pydantic/fields.py", line 419, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 534, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 633, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 778, in pydantic.fields.ModelField._create_sub_type
  File "pydantic/fields.py", line 419, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 534, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 638, in pydantic.fields.ModelField._type_analysis
  File "/Users/peastman/miniconda3/envs/qcportal/lib/python3.9/typing.py", line 851, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
```

**Comment by JonathonMisiewicz** [comment]
What's the output of `conda list`? We especially need to see the line that mentions `pydantic`.

**Comment by loriab** [comment]
I have a vague memory that it might be a `typing_extensions` version issue.

**Comment by loriab** [comment]
Yes, please aim for typing_extensions=4.5 https://github.com/pydantic/pydantic/issues/5821 . Or update pydantic; iirc they did an extra v1 release to resolve this.

**Comment by peastman** [comment]
```
# Name                    Version                   Build  Channel
abseil-cpp                20220623.0           he4e09e4_6    conda-forge
aiohttp                   3.8.5            py39h0f82c59_0    conda-forge
aiosignal                 1.3.1              pyhd8ed1ab_0    conda-forge
alembic                   1.12.0             pyhd8ed1ab_0    conda-forge
ambertools                23.3             py39hdb62838_1    conda-forge
amberutils                21.0                     pypi_0    pypi
appnope                   0.1.2            py39h2804cbe_2    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py39h5161555_1    conda-forge
arpack                    3.7.0                h58ebc17_2    conda-forge
arrow-cpp                 11.0.0           hce30654_5_cpu    conda-forge
asttokens                 2.0.5              pyhd8ed1ab_0    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.3              pyhd8ed1ab_0    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
aws-c-auth                0.6.24               he8f13b4_5    conda-forge
aws-c-cal                 0.5.20               h9571af1_6    conda-forge
aws-c-common              0.8.11               h1a8c8d9_0    conda-forge
aws-c-compression         0.2.16               h7334ab6_3    conda-forge
aws-c-event-stream        0.2.18               ha663d55_6    conda-forge
aws-c-http                0.7.4                h49dec38_2    conda-forge
aws-c-io                  0.13.17              h323b671_2    conda-forge
aws-c-mqtt                0.8.6                hdc0f556_6    conda-forge
aws-c-s3                  0.2.4                hbb4c6b3_3    conda-forge
aws-c-sdkutils            0.1.7                h7334ab6_3    conda-forge
aws-checksums             0.1.14               h7334ab6_3    conda-forge
aws-crt-cpp               0.19.7               h6f6c549_7    conda-forge
aws-sdk-cpp               1.10.57              hbe10753_4    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bcrypt                    4.0.1            py39haff01fd_1    conda-forge
black                     22.1.0             pyhd8ed1ab_0    conda-forge
bleach                    4.1.0              pyhd8ed1ab_0    conda-forge
blosc                     1.21.4               hc338f07_0    conda-forge
boost                     1.78.0           py39h99de9ae_4    conda-forge
boost-cpp                 1.78.0               h9ed8d21_3    conda-forge
brotli                    1.0.9                h3422bc3_6    conda-forge
brotli-bin                1.0.9                h3422bc3_6    conda-forge
brotlipy                  0.7.0           py39h5161555_1003    conda-forge
bson                      0.5.9                      py_0    conda-forge
bzip2                     1.0.8                h3422bc3_4    conda-forge
c-ares                    1.18.1               h3422bc3_0    conda-forge
c-blosc2                  2.10.0               h068da5f_0    conda-forge
ca-certificates           2023.7.22            hf0a4a13_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cachetools                5.3.0              pyhd8ed1ab_0    conda-forge
cairo                     1.16.0            h1e71087_1016    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.15.0           py39h52b1de0_0    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
click                     8.0.4            py39h2804cbe_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cryptography              39.0.2           py39he2a39a8_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cython                    0.29.36          py39hb198ff7_0    conda-forge
dataclasses               0.8                pyhc8e2a94_3    conda-forge
debugpy                   1.5.1            py39hfb83b0d_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
dftd4                     3.5.0                h4f5cce7_0    conda-forge
dill                      0.3.7              pyhd8ed1ab_0    conda-forge
dkh                       1.2                  h587b571_0    conda-forge
edgembar                  0.2                      pypi_0    pypi
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
executing                 0.8.3              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                hb7217d7_1    conda-forge
fftw                      3.3.10          nompi_h2e33b67_103    conda-forge
flask                     2.1.3              pyhd8ed1ab_0    conda-forge
flask-jwt-extended        4.5.2              pyhd8ed1ab_0    conda-forge
flit-core                 3.7.1              pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               h82840c6_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.33.3           py39h9eb174b_0    conda-forge
freetype                  2.12.1               hd633e50_1    conda-forge
frozenlist                1.4.0            py39h0f82c59_1    conda-forge
gau2grid                  2.0.7                h1a8c8d9_2    conda-forge
geoip2                    4.7.0              pyhd8ed1ab_0    conda-forge
geometric                 1.0                pyhd8ed1ab_1    conda-forge
gettext                   0.21.1               h0186832_0    conda-forge
gflags                    2.2.2             hc88da5d_1004    conda-forge
giflib                    5.2.1                h27ca646_2    conda-forge
globus-sdk                3.28.0             pyhd8ed1ab_0    conda-forge
glog                      0.6.0                h6da1cb0_0    conda-forge
greenlet                  1.1.2            py39h0ef5a74_2    conda-forge
grpc-cpp                  1.51.1               h44b9a77_1    conda-forge
gtest                     1.14.0               h1995070_1    conda-forge
gunicorn                  21.2.0           py39h2804cbe_0    conda-forge
h5py                      3.9.0           nompi_py39he9c2634_101    conda-forge
hdf4                      4.2.15               h1a38d6a_5    conda-forge
hdf5                      1.14.1          nompi_h3aba7b3_100    conda-forge
icu                       72.1                 he12128b_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.2           py39h2804cbe_0    conda-forge
importlib_metadata        4.11.2               hd8ed1ab_0    conda-forge
importlib_resources       5.4.0              pyhd8ed1ab_0    conda-forge
ipykernel                 6.9.1            py39h32adebf_0    conda-forge
ipython                   8.0.1            py39h2804cbe_2    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.6.5              pyhd8ed1ab_0    conda-forge
itsdangerous              2.1.2              pyhd8ed1ab_0    conda-forge
jedi                      0.18.1           py39h2804cbe_0    conda-forge
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
joblib                    1.3.0              pyhd8ed1ab_1    conda-forge
jpeg                      9e                   h1c322ee_1    conda-forge
jsonschema                4.4.0              pyhd8ed1ab_0    conda-forge
jupyter_client            7.1.2              pyhd8ed1ab_0    conda-forge
jupyter_core              4.9.2            py39h2804cbe_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_widgets        1.0.2              pyhd8ed1ab_0    conda-forge
khronos-opencl-icd-loader 2022.09.30           h1a8c8d9_2    conda-forge
kiwisolver                1.4.2            py39h2c803a9_1    conda-forge
krb5                      1.21.2               h92f50d5_0    conda-forge
lcms2                     2.12                 had6a04f_0    conda-forge
lerc                      3.0                  hbdafb3b_0    conda-forge
libabseil                 20220623.0      cxx17_h28b99d4_6    conda-forge
libaec                    1.0.6                hb7217d7_1    conda-forge
libarrow                  11.0.0           h0b9b5d1_5_cpu    conda-forge
libblas                   3.9.0           13_osxarm64_openblas    conda-forge
libbrotlicommon           1.0.9                h3422bc3_6    conda-forge
libbrotlidec              1.0.9                h3422bc3_6    conda-forge
libbrotlienc              1.0.9                h3422bc3_6    conda-forge
libcblas                  3.9.0           13_osxarm64_openblas    conda-forge
libcrc32c                 1.1.2                hbdafb3b_0    conda-forge
libcurl                   8.3.0                hc52a3a8_0    conda-forge
libcxx                    15.0.7               h75e25f2_0    conda-forge
libdeflate                1.10                 h3422bc3_0    conda-forge
libecpint                 1.0.7                habece42_9    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h642e427_1    conda-forge
libevent                  2.1.10               h7673551_4    conda-forge
libexpat                  2.5.0                hb7217d7_1    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0           12_2_0_hd922786_31    conda-forge
libgfortran5              12.2.0              h0eea778_31    conda-forge
libglib                   2.76.3               h24e9cb9_0    conda-forge
libgoogle-cloud           2.7.0                hcf11473_1    conda-forge
libgrpc                   1.51.1               hb15be72_1    conda-forge
libiconv                  1.17                 he4db4b2_0    conda-forge
libint                    2.7.3dev1            h8694fdf_0    conda-forge/label/libint_dev
liblapack                 3.9.0           13_osxarm64_openblas    conda-forge
libnetcdf                 4.9.2           nompi_hf3c790a_107    conda-forge
libnghttp2                1.52.0               hae82a92_0    conda-forge
libopenblas               0.3.18          openmp_h5dd58f0_0    conda-forge
libpcm                    1.2.3                hb19c430_4    conda-forge
libpng                    1.6.39               h76d750c_0    conda-forge
libpq                     15.4                 hcea71ed_0    conda-forge
libprotobuf               3.21.12              hb5ab8b9_0    conda-forge
libsodium                 1.0.18               h27ca646_1    conda-forge
libssh2                   1.11.0               h7a5bd25_0    conda-forge
libthrift                 0.18.0               h6635e49_0    conda-forge
libtiff                   4.3.0                h2810ee2_4    conda-forge
libutf8proc               2.8.0                h1a8c8d9_0    conda-forge
libwebp                   1.2.2                h0d20362_0    conda-forge
libwebp-base              1.2.2                h3422bc3_1    conda-forge
libxc-c                   6.2.2            cpu_h427b8d4_0    conda-forge
libxcb                    1.15                 hf346824_0    conda-forge
libxml2                   2.11.5               he3bdae6_0    conda-forge
libxslt                   1.1.37               h1728932_1    conda-forge
libzip                    1.9.2                h76ab92c_1    conda-forge
libzlib                   1.2.13               h03a7124_4    conda-forge
llvm-openmp               16.0.6               h1c12783_0    conda-forge
lxml                      4.9.3            py39hb67b4e4_0    conda-forge
lz4-c                     1.9.3                hbdafb3b_1    conda-forge
mako                      1.2.4              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.0            py39hb18efdd_0    conda-forge
matplotlib-base           3.5.2            py39h4ee150f_0    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
maxminddb                 2.4.0              pyhd8ed1ab_0    conda-forge
mctc-lib                  0.3.1                h1b58363_0    conda-forge
mdtraj                    1.9.7            py39h9d592f4_1    conda-forge
mistune                   0.8.4           py39h5161555_1005    conda-forge
mmpbsa-py                 16.0                     pypi_0    pypi
msgpack-python            1.0.3            py39h4d2d688_0    conda-forge
multidict                 6.0.4            py39h02fc5c5_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mypy_extensions           0.4.3            py39h2804cbe_4    conda-forge
nbclient                  0.5.11             pyhd8ed1ab_0    conda-forge
nbconvert                 5.6.1              pyhd8ed1ab_2    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  hc470f4d_0    conda-forge
nest-asyncio              1.5.4              pyhd8ed1ab_0    conda-forge
netcdf-fortran            4.6.1           nompi_hb96c8d4_101    conda-forge
networkx                  3.1                pyhd8ed1ab_0    conda-forge
nglview                   3.0.3              pyh8a188c0_0    conda-forge
notebook                  6.4.8              pyha770c72_0    conda-forge
numexpr                   2.8.3            py39hd2dba81_0    conda-forge
numpy                     1.22.2           py39h61a45d2_0    conda-forge
ocl_icd_wrapper_apple     1.0.0                h27ca646_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openbabel                 3.1.1            py39hcdff8ce_7    conda-forge
openff-amber-ff-ports     0.0.3              pyh6c4a22f_0    conda-forge
openff-forcefields        2023.05.1          pyh1a96a4e_1    conda-forge
openff-interchange        0.3.4              pyhd8ed1ab_1    conda-forge
openff-interchange-base   0.3.4              pyhd8ed1ab_1    conda-forge
openff-models             0.0.5              pyh1a96a4e_0    conda-forge
openff-toolkit            0.14.0             pyhd8ed1ab_2    conda-forge
openff-toolkit-base       0.14.0             pyhd8ed1ab_2    conda-forge
openff-units              0.2.0              pyh1a96a4e_1    conda-forge
openff-utilities          0.1.8              pyh1a96a4e_0    conda-forge
openjpeg                  2.4.0                h062765e_1    conda-forge
openmm                    8.0.0           py39h2180d36_0_khronos    conda-forge
openmmforcefields         0.1.0+494.gd78f2b8.dirty           dev_0    <develop>
openssl                   3.1.3                h53f4e23_0    conda-forge
optking                   0.2.1              pyhd8ed1ab_0    conda-forge
orc                       1.8.2                hef0d403_2    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
packmol                   20.2.2               h9318095_1    conda-forge
packmol-memgen            2023.2.24                pypi_0    pypi
pandas                    1.4.1            py39h7f752ed_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
panedr                    0.7.1              pyhd8ed1ab_0    conda-forge
paramiko                  3.3.1              pyhd8ed1ab_0    conda-forge
parmed                    4.1.0            py39h23fbdae_0    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
parsl                     2023.9.11          pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pathspec                  0.9.0              pyhd8ed1ab_0    conda-forge
pbr                       5.11.1             pyhd8ed1ab_0    conda-forge
pcmsolver                 1.2.3                      py_4    conda-forge
pcre                      8.45                 hbdafb3b_0    conda-forge
pcre2                     10.40                hb34f9b4_0    conda-forge
pdb4amber                 22.0                     pypi_0    pypi
pdbfixer                  1.9                pyh1a96a4e_0    conda-forge
perl                      5.32.1          3_hf2054a2_perl5    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.4.0            py39ha74c66e_0    conda-forge
pint                      0.20.1             pyhd8ed1ab_0    conda-forge
pip                       22.0.3             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h27ca646_0    conda-forge
platformdirs              2.5.1              pyhd8ed1ab_0    conda-forge
plotly                    5.6.0              pyhd8ed1ab_0    conda-forge
postgresql                15.4                 h00cd704_0    conda-forge
prometheus_client         0.13.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.27             pyha770c72_0    conda-forge
psi4                      1.8.2            py39h9c1326d_0    conda-forge
psutil                    5.9.5            py39h0f82c59_1    conda-forge
psycopg2                  2.9.6            py39heac0328_0    conda-forge
pthread-stubs             0.4               h27ca646_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pugixml                   1.13                 h13dd4ca_1    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
py-cpuinfo                9.0.0              pyhd8ed1ab_0    conda-forge
pyarrow                   11.0.0          py39hfdcab31_5_cpu    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycairo                   1.21.0           py39h9e65f43_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydantic                  1.9.0            py39h5161555_0    conda-forge
pyedr                     0.7.1              pyhd8ed1ab_0    conda-forge
pygments                  2.11.2             pyhd8ed1ab_0    conda-forge
pyjwt                     2.8.0              pyhd8ed1ab_0    conda-forge
pymsmt                    22.0                     pypi_0    pypi
pynacl                    1.5.0            py39h02fc5c5_2    conda-forge
pyopenssl                 23.2.0             pyhd8ed1ab_1    conda-forge
pyparsing                 3.0.7              pyhd8ed1ab_0    conda-forge
pyrsistent                0.18.1           py39h5161555_0    conda-forge
pysocks                   1.7.1            py39h2804cbe_4    conda-forge
pytables                  3.8.0            py39h0da393b_2    conda-forge
python                    3.9.10          h38ef502_2_cpython    conda-forge
python-constraint         1.4.0                      py_0    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytraj                    2.0.6                    pypi_0    pypi
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py39h5161555_3    conda-forge
pyzmq                     22.3.0           py39h02c6a76_1    conda-forge
qcelemental               0.26.0             pyhd8ed1ab_0    conda-forge
qcengine                  0.28.1             pyhd8ed1ab_0    conda-forge
qcfractal                 0.50               pyh707e725_0    conda-forge
qcfractalcompute          0.50               pyhd8ed1ab_0    conda-forge
qcportal                  0.50               pyh7448d05_0    conda-forge
rdkit                     2023.03.1        py39hcba3512_0    conda-forge
re2                       2023.02.01           hb7217d7_0    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
reportlab                 3.5.68           py39h3fc2f6e_1    conda-forge
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
sander                    22.0                     pypi_0    pypi
scipy                     1.9.0            py39h14896cb_0    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setproctitle              1.3.2            py39h02fc5c5_1    conda-forge
setuptools                60.9.3           py39h2804cbe_0    conda-forge
simple-dftd3              0.7.0                h702fe85_2    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
smirnoff99frosst          1.1.0              pyh44b312d_0    conda-forge
snappy                    1.1.10               h17c5cce_0    conda-forge
sqlalchemy                2.0.21           py39h0f82c59_0    conda-forge
sqlite                    3.37.0               h72a2b83_0    conda-forge
stack_data                0.2.0              pyhd8ed1ab_0    conda-forge
tabulate                  0.9.0              pyhd8ed1ab_1    conda-forge
tblib                     2.0.0              pyhd8ed1ab_0    conda-forge
tblite                    0.3.0                h4f5cce7_0    conda-forge
tenacity                  8.0.1              pyhd8ed1ab_0    conda-forge
terminado                 0.13.1           py39h2804cbe_0    conda-forge
testpath                  0.6.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               he1e0b03_0    conda-forge
toml-f                    0.3.1                he18974e_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tornado                   6.1              py39h5161555_2    conda-forge
torsiondrive              1.1.0              pyhd8ed1ab_0    conda-forge
tqdm                      4.63.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge
typed-ast                 1.5.2            py39h5161555_0    conda-forge
typeguard                 2.13.3             pyhd8ed1ab_0    conda-forge
typing-extensions         4.8.0                hd8ed1ab_0    conda-forge
typing_extensions         4.8.0              pyha770c72_0    conda-forge
tzcode                    2023c                h1a8c8d9_0    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
unicodedata2              14.0.0           py39hb18efdd_1    conda-forge
urllib3                   1.26.8             pyhd8ed1ab_1    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  2.1.2              pyhd8ed1ab_1    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
widgetsnbextension        3.5.2            py39h2804cbe_1    conda-forge
xmltodict                 0.13.0             pyhd8ed1ab_0    conda-forge
xorg-kbproto              1.0.7             h27ca646_1002    conda-forge
xorg-libice               1.0.10               h27ca646_0    conda-forge
xorg-libsm                1.2.3             h27ca646_1000    conda-forge
xorg-libx11               1.8.6                hfd9643e_0    conda-forge
xorg-libxau               1.0.9                h27ca646_0    conda-forge
xorg-libxdmcp             1.1.3                h27ca646_0    conda-forge
xorg-libxext              1.3.4                h1a8c8d9_2    conda-forge
xorg-libxt                1.3.0                hb547adb_0    conda-forge
xorg-xextproto            7.3.0             h1a8c8d9_1003    conda-forge
xorg-xproto               7.0.31            h27ca646_1007    conda-forge
xtb                       6.5.1                h4884bc7_1    conda-forge
xtb-python                22.1             py39h02fc5c5_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
yaml                      0.2.5                h3422bc3_2    conda-forge
yarl                      1.9.2            py39h0f82c59_0    conda-forge
zeromq                    4.3.4                hbdafb3b_1    conda-forge
zipp                      3.7.0              pyhd8ed1ab_1    conda-forge
zlib                      1.2.13               h03a7124_4    conda-forge
zlib-ng                   2.0.7                h1a8c8d9_0    conda-forge
zstandard                 0.21.0           py39haf70649_1    conda-forge
zstd                      1.5.5                h4f39d0f_0    conda-forge
```

`typing_extensions` is 4.8.  That's what conda picked.

**Comment by loriab** [comment]
I'd try updating pydantic to v1.10 or downgrading typing_extensions to 4.5.

**Comment by JonathonMisiewicz** [comment]
@loriab Is there any reason we shouldn't just update the conda install instructions to have `pydantic >= 1.10` and then close issue?

**Comment by loriab** [comment]
It's going to be uncommon to hit b/c fresh env are going to pull latest packages for pydantic and typing_extensions, which will be fine together. (And qcfractal would be present to pin to pydantic<2.) It's only going to be existing env that could get into this state, and those folks probably aren't running off the instructions anyways. I think I'd better
 add the min pydantic to the psi4 recipe and rebuild the packages, probably next week.

**Comment by loriab** [comment]
I started pinning to pydantic>=1.10 in last Friday's c-f builds.
