### ISSUE TITLE
error in wfn.tofile while calculating hessian

### ISSUE THREAD

**Issue by wszs** [psi4/psi4#3068]
H, wfn2 = psi4.hessian('b3lyp', return_wfn=True)
wfn2.to_file()

Traceback (most recent call last):
  File "/root/.pycharm_helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "/opt/anaconda3/envs/py310/lib/python3.10/site-packages/psi4/driver/p4util/python_helpers.py", line 360, in _core_wavefunction_to_file
    'Ca':       wfn.Ca().to_array()       if wfn.Ca()       else None,
RuntimeError: 
Fatal Error: Wavefunction::Ca: Unable to obtain MO coefficients.
Error occurred in file: /scratch/psilocaluser/conda-builds/psi4-multiout_1683589981287/work/psi4/src/psi4/libmints/wavefunction.cc on line: 804
The most recent 5 function calls were:
psi::Wavefunction::Ca() const

this error doesn't happen when calculating energy

**Comment by loriab** [comment]
We should use a more informative/tailored error message.

But the reason it can't drop a wfn file is because non-Hartree--Fock Hessians are computed by finite difference, so there's at most a dummy wfn with mol, basis, qcvariables, etc. No goodies like MO coefficients or occupations. What piece of data were you seeking?

**Comment by wszs** [comment]
> We should use a more informative/tailored error message.
> 
> But the reason it can't drop a wfn file is because non-Hartree--Fock Hessians are computed by finite difference, so there's at most a dummy wfn with mol, basis, qcvariables, etc. No goodies like MO coefficients or occupations. What piece of data were you seeking?


Ach so, I just found a method to calculate without this wfn,thanks!
  btw,I'm looking forward to calculate analytical hessian with DFT for long time, having any plan?

**Comment by loriab** [comment]
Well, you can for LSDA DFT (see rhf/uhf conv/df Hess in https://psicode.org/psi4manual/master/dft.html#id15), but I concede that's not the most useful DFT rung. No immediate plans, sorry.

**Comment by JonathonMisiewicz** [comment]
I'd love to have this RKS GGA hessians for the 1.10 release next May (and I'd probably be the one who codes it). I'm currently tracking down some errors in integrals, which is higher priority.
