### ISSUE TITLE
PSIO_ERROR:

### ISSUE THREAD

**Issue by luisakaermer** [psi4/psi4#3069]
Hi,
I try to do a bunch of DFT single point energy calculations of small fragments on the university HPC cluster with a custom basis set.
After the first 20 or so calculations ran smoothly, every subsequent one failed with:
```

PSIO_ERROR: unit = 35, errval = 5
PSIO_ERROR: 5 (file not open or open call failed)
PSIO_ERROR:
PSIO_ERROR: Check the location of your scratch directory which can be
PSIO_ERROR: specified via the $PSI_SCRATCH environment variable or in
PSIO_ERROR: the $HOME/.psi4rc file.
PSIO_ERROR:
PSIO_ERROR: Please note that the scratch directory must exist and be
PSIO_ERROR: writable by Psi4
```
Thats one example input:
```
molecule {
  0 1
  N  -1.4457680611716  -1.1047188295845  0.49148092386593
  C  -0.19168175766337  -0.75584211512691  0.20898275954952
  S  1.16737932640644  -1.82766284403922  0.14616844519932
  C  2.16597045357598  -0.42448441793899  -0.26698146976982
  N  1.54724741904672  0.67798068286713  -0.34204940942266
  C  0.21550144939676  0.55519535899526  -0.0839857520715
  C  -0.70195776564886  1.65045791061703  -0.10441352532731
  O  -1.89802765802088  1.54782198311403  0.1259571991072
  H  -2.11563998092643  -0.33690782979021  0.4823163098176
  H  -1.71164622110861  -2.0497008550553  0.69762302601465
  H  3.21537348272138  -0.55453850454389  -0.43220307841028
  H  -0.24675068660743  2.6223994604856  -0.34875937387462

  no_reorient
  no_com
}

# Set the basis set
set {
  basis sdzhf
}

# Compute the energy and return the wavefunction
E, wfn = energy('WB97X-D', return_wfn=True)

# Save the wavefunction to a file
wfn.to_file("mol.wfn")
```
and thats the last portion of the out:
```
==> Integral Setup <==


Traceback (most recent call last):
  File "/software/all/PSI4/1.3.2-foss-2020b/bin/psi4", line 287, in <module>
    exec(content)
  File "<string>", line 38, in <module>
  File "/software/all/PSI4/1.3.2-foss-2020b/lib//python3.8/site-packages/psi4/driver/driver.py", line 556, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/software/all/PSI4/1.3.2-foss-2020b/lib//python3.8/site-packages/psi4/driver/procrouting/proc.py", line 2002, in run_scf
    scf_wfn = scf_helper(name, post_scf=False, **kwargs)
  File "/software/all/PSI4/1.3.2-foss-2020b/lib//python3.8/site-packages/psi4/driver/procrouting/proc.py", line 1363, in scf_helper
    e_scf = scf_wfn.compute_energy()
  File "/software/all/PSI4/1.3.2-foss-2020b/lib//python3.8/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 84, in scf_compute_energy
    self.initialize()
  File "/software/all/PSI4/1.3.2-foss-2020b/lib//python3.8/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 197, in scf_initialize
    mints.one_electron_integrals()

RuntimeError: 
Fatal Error: PSIO Error
Error occurred in file: /lscratch/software_build/easybuild/build/PSI4/1.3.2/foss-2020b/psi4-1.3.2/psi4/src/psi4/libpsio/error.cc on line: 128
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)
psi::PSIO::open(unsigned long, int)
psi::Matrix::save(psi::PSIO*, unsigned long, psi::Matrix::SaveType)
psi::MintsHelper::one_electron_integrals()



Printing out the relevant lines from the Psithon --> Python processed input file:
      no_reorient
      no_com
    """)
    core.IO.set_default_namespace("")
    core.set_global_option("BASIS", "sdzhf")
--> E, wfn = energy('WB97X-D', return_wfn=True)
    wfn.to_file("mol.wfn")

    Psi4 stopped on: Tuesday, 31 October 2023 05:02PM
    Psi4 wall time for execution: 0:01:45.79
```
Can anyone explain in more detail what is happening here and how i can solve this?

**Comment by loriab** [comment]
I'd check that you're setting scratch through envvar PSI_SCRATCH or arg `-s` to wherever the cluster wants so that it's not filling up `/tmp`. And also check that any scratch or /tmp directories aren't full.
