### ISSUE TITLE
Plugin example broken

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#3093]
Trying out the SCF plugin with the current master branch I get the error
```
$ psi4 h2o.in
Traceback (most recent call last):
  File "/home/work/psi4/install/bin/psi4", line 387, in <module>
    exec(content)
  File "<string>", line 26, in <module>
  File "/home/work/psi4/install/lib/psi4/driver/driver.py", line 519, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/work/openorbital/openorbital/psi4/scf/myplugin/pymodule.py", line 60, in run_myplugin
    psi4.set_scalar_variable('CURRENT ENERGY', myplugin_wfn.energy())

AttributeError: module 'psi4' has no attribute 'set_scalar_variable'

Printing out the relevant lines from the Psithon --> Python processed input file:
    H     0.866811766153153   0.601435735686679   0.000000000000000
    H    -0.866811766153153   0.601435735686679   0.000000000000000
    """)
    core.IO.set_default_namespace("")
    core.set_global_option("BASIS", "pcseg-1")
--> energy('myplugin')


!-------------------------------------------------------!
!                                                       !
!  module 'psi4' has no attribute 'set_scalar_variable' !
!                                                       !
!-------------------------------------------------------!

Segmentation fault (core dumped)
```

**Comment by susilehtola** [comment]
Sorry, generated the template with an old version by mistake.
