### ISSUE TITLE
CASSCF calculation on hydrogen molecule fails

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#3096]
The input
```
molecule {
H
H 1 0.60
}

set basis cc-pVDZ
set docc [ 1, 0, 0, 0, 0, 0, 0, 0 ]
# STO-3G active space
set active [1, 0, 0, 0, 0, 1, 0, 0 ]
energy('casscf')
```
fails with the up-to-date master branch with the error message
```
Traceback (most recent call last):
  File "/home/work/psi4/install/bin/psi4", line 387, in <module>
    exec(content)
  File "<string>", line 26, in <module>
  File "/home/work/psi4/install/lib/psi4/driver/driver.py", line 519, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/work/psi4/install/lib/psi4/driver/procrouting/proc.py", line 5483, in run_detcas
    ciwfn = mcscf.mcscf_solver(ref_wfn)
  File "/home/work/psi4/install/lib/psi4/driver/procrouting/mcscf/mcscf_solver.py", line 153, in mcscf_solver
    nci_iter = ciwfn.diag_h(abs(ediff) * 1.e-2, orb_grad_rms * 1.e-3)

RuntimeError: 
Fatal Error: DSYEV diagonalizer failed in DETCI SEM!
Error occurred in file: /home/work/psi4/psi4/src/psi4/detci/sem.cc on line: 561
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)


Printing out the relevant lines from the Psithon --> Python processed input file:
    """)
    core.IO.set_default_namespace("")
    core.set_global_option("BASIS", "cc-pVDZ")
    core.set_global_option("DOCC", [ 1, 0, 0, 0, 0, 0, 0, 0 ])
    core.set_global_option("ACTIVE", [1, 0, 0, 0, 0, 1, 0, 0 ])
--> energy('casscf')


!----------------------------------------------------------------------------------!
!                                                                                  !
! Fatal Error: DSYEV diagonalizer failed in DETCI SEM!                             !
! Error occurred in file: /home/work/psi4/psi4/src/psi4/detci/sem.cc on line: 561  !
! The most recent 5 function calls were:                                           !
! psi::PsiException::PsiException(std::__cxx11::basic_string<char,                 !
!     std::char_traits<char>, std::allocator<char> >, char const*, int)            !
!                                                                                  !
!----------------------------------------------------------------------------------!

```

**Comment by TiborGY** [comment]
No idea what is causing DSYEV to fail, but before I implemented the new wrapper this would have gone undetected, so if anyone tried to bisect it crash/no crash would not be a good indicator. The old wrapper ignored the info value from LAPACK and let execution continue despite the diagonalization failure.
