### ISSUE TITLE
MRCC interface is not working

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#3159]
Hi,

I just got an MRCC license and started toying around with the Psi4 interface. Unfortunately, it is not working for me. 
```
molecule {
0 1
O
H 1 1.0
H 1 1.0 2 110.0
}

set qc_module mrcc
optimize('ccsdt/cc-pvdz')
freq('ccsdt/cc-pvdz')
```
Using the mrcc.2023-08-28.binary.tar.gz binary release, I just get a big bunch of file not found errors
```
$ psi4 -n6 h2o.in 
forrtl: No such file or directory
forrtl: severe (29): file not found, unit 75, file /home/work/scratch/mrcc_168425/KEYWD
Image              PC                Routine            Line        Source             
dmrcc              000000000131B3EC  Unknown               Unknown  Unknown
dmrcc              00000000004DA346  Unknown               Unknown  Unknown
dmrcc              00000000005432D5  Unknown               Unknown  Unknown
dmrcc              0000000000543C32  Unknown               Unknown  Unknown
dmrcc              000000000054274C  Unknown               Unknown  Unknown
dmrcc              000000000040D9CF  Unknown               Unknown  Unknown
dmrcc              0000000000402F57  Unknown               Unknown  Unknown
dmrcc              0000000000401B3D  Unknown               Unknown  Unknown
dmrcc              00000000013AAE59  Unknown               Unknown  Unknown
dmrcc              0000000000401A2A  Unknown               Unknown  Unknown
forrtl: No such file or directory
forrtl: severe (29): file not found, unit 75, file /home/work/scratch/mrcc_168425/KEYWD
Image              PC                Routine            Line        Source             
dmrcc              000000000131B3EC  Unknown               Unknown  Unknown
dmrcc              00000000004DA346  Unknown               Unknown  Unknown
dmrcc              00000000005432D5  Unknown               Unknown  Unknown
dmrcc              0000000000543C32  Unknown               Unknown  Unknown
dmrcc              000000000054274C  Unknown               Unknown  Unknown
dmrcc              000000000040D9CF  Unknown               Unknown  Unknown
dmrcc              0000000000402F57  Unknown               Unknown  Unknown
dmrcc              0000000000401B3D  Unknown               Unknown  Unknown
dmrcc              00000000013AAE59  Unknown               Unknown  Unknown
dmrcc              0000000000401A2A  Unknown               Unknown  Unknown
forrtl: No such file or directory
forrtl: severe (29): file not found, unit 75, file /home/work/scratch/mrcc_168425/KEYWD
Image              PC                Routine            Line        Source             
dmrcc              000000000131B3EC  Unknown               Unknown  Unknown
dmrcc              00000000004DA346  Unknown               Unknown  Unknown
dmrcc              00000000005432D5  Unknown               Unknown  Unknown
dmrcc              0000000000543C32  Unknown               Unknown  Unknown
dmrcc              000000000054274C  Unknown               Unknown  Unknown
dmrcc              000000000040D9CF  Unknown               Unknown  Unknown
dmrcc              0000000000402F57  Unknown               Unknown  Unknown
dmrcc              0000000000401B3D  Unknown               Unknown  Unknown
dmrcc              00000000013AAE59  Unknown               Unknown  Unknown
dmrcc              0000000000401A2A  Unknown               Unknown  Unknown
forrtl: No such file or directory
forrtl: severe (29): file not found, unit 75, file /home/work/scratch/mrcc_168425/KEYWD
Image              PC                Routine            Line        Source             
dmrcc              000000000131B3EC  Unknown               Unknown  Unknown
dmrcc              00000000004DA346  Unknown               Unknown  Unknown
dmrcc              00000000005432D5  Unknown               Unknown  Unknown
dmrcc              0000000000543C32  Unknown               Unknown  Unknown
dmrcc              000000000054274C  Unknown               Unknown  Unknown
dmrcc              000000000040D9CF  Unknown               Unknown  Unknown
dmrcc              0000000000402F57  Unknown               Unknown  Unknown
dmrcc              0000000000401B3D  Unknown               Unknown  Unknown
dmrcc              00000000013AAE59  Unknown               Unknown  Unknown
dmrcc              0000000000401A2A  Unknown               Unknown  Unknown
forrtl: No such file or directory
forrtl: severe (29): file not found, unit 75, file /home/work/scratch/mrcc_168425/KEYWD
Image              PC                Routine            Line        Source             
dmrcc              000000000131B3EC  Unknown               Unknown  Unknown
dmrcc              00000000004DA346  Unknown               Unknown  Unknown
dmrcc              00000000005432D5  Unknown               Unknown  Unknown
dmrcc              0000000000543C32  Unknown               Unknown  Unknown
dmrcc              000000000054274C  Unknown               Unknown  Unknown
dmrcc              000000000040D9CF  Unknown               Unknown  Unknown
dmrcc              0000000000402F57  Unknown               Unknown  Unknown
dmrcc              0000000000401B3D  Unknown               Unknown  Unknown
dmrcc              00000000013AAE59  Unknown               Unknown  Unknown
dmrcc              0000000000401A2A  Unknown               Unknown  Unknown
invalid value encountered in scalar divide
invalid value encountered in divide
Optimizer: Optimization complete!
forrtl: No such file or directory
forrtl: severe (29): file not found, unit 75, file /home/work/scratch/mrcc_168425/KEYWD
Image              PC                Routine            Line        Source             
dmrcc              000000000131B3EC  Unknown               Unknown  Unknown
dmrcc              00000000004DA346  Unknown               Unknown  Unknown
dmrcc              00000000005432D5  Unknown               Unknown  Unknown
dmrcc              0000000000543C32  Unknown               Unknown  Unknown
dmrcc              000000000054274C  Unknown               Unknown  Unknown
dmrcc              000000000040D9CF  Unknown               Unknown  Unknown
dmrcc              0000000000402F57  Unknown               Unknown  Unknown
dmrcc              0000000000401B3D  Unknown               Unknown  Unknown
dmrcc              00000000013AAE59  Unknown               Unknown  Unknown
dmrcc              0000000000401A2A  Unknown               Unknown  Unknown
forrtl: No such file or directory
forrtl: severe (29): file not found, unit 75, file /home/work/scratch/mrcc_168425/KEYWD
Image              PC                Routine            Line        Source             
dmrcc              000000000131B3EC  Unknown               Unknown  Unknown
dmrcc              00000000004DA346  Unknown               Unknown  Unknown
dmrcc              00000000005432D5  Unknown               Unknown  Unknown
dmrcc              0000000000543C32  Unknown               Unknown  Unknown
dmrcc              000000000054274C  Unknown               Unknown  Unknown
dmrcc              000000000040D9CF  Unknown               Unknown  Unknown
dmrcc              0000000000402F57  Unknown               Unknown  Unknown
dmrcc              0000000000401B3D  Unknown               Unknown  Unknown
dmrcc              00000000013AAE59  Unknown               Unknown  Unknown
dmrcc              0000000000401A2A  Unknown               Unknown  Unknown
forrtl: No such file or directory
forrtl: severe (29): file not found, unit 75, file /home/work/scratch/mrcc_168425/KEYWD
Image              PC                Routine            Line        Source             
dmrcc              000000000131B3EC  Unknown               Unknown  Unknown
dmrcc              00000000004DA346  Unknown               Unknown  Unknown
dmrcc              00000000005432D5  Unknown               Unknown  Unknown
dmrcc              0000000000543C32  Unknown               Unknown  Unknown
dmrcc              000000000054274C  Unknown               Unknown  Unknown
dmrcc              000000000040D9CF  Unknown               Unknown  Unknown
dmrcc              0000000000402F57  Unknown               Unknown  Unknown
dmrcc              0000000000401B3D  Unknown               Unknown  Unknown
dmrcc              00000000013AAE59  Unknown               Unknown  Unknown
dmrcc              0000000000401A2A  Unknown               Unknown  Unknown
forrtl: No such file or directory
forrtl: severe (29): file not found, unit 75, file /home/work/scratch/mrcc_168425/KEYWD
Image              PC                Routine            Line        Source             
dmrcc              000000000131B3EC  Unknown               Unknown  Unknown
dmrcc              00000000004DA346  Unknown               Unknown  Unknown
dmrcc              00000000005432D5  Unknown               Unknown  Unknown
dmrcc              0000000000543C32  Unknown               Unknown  Unknown
dmrcc              000000000054274C  Unknown               Unknown  Unknown
dmrcc              000000000040D9CF  Unknown               Unknown  Unknown
dmrcc              0000000000402F57  Unknown               Unknown  Unknown
dmrcc              0000000000401B3D  Unknown               Unknown  Unknown
dmrcc              00000000013AAE59  Unknown               Unknown  Unknown
dmrcc              0000000000401A2A  Unknown               Unknown  Unknown
forrtl: No such file or directory
forrtl: severe (29): file not found, unit 75, file /home/work/scratch/mrcc_168425/KEYWD
Image              PC                Routine            Line        Source             
dmrcc              000000000131B3EC  Unknown               Unknown  Unknown
dmrcc              00000000004DA346  Unknown               Unknown  Unknown
dmrcc              00000000005432D5  Unknown               Unknown  Unknown
dmrcc              0000000000543C32  Unknown               Unknown  Unknown
dmrcc              000000000054274C  Unknown               Unknown  Unknown
dmrcc              000000000040D9CF  Unknown               Unknown  Unknown
dmrcc              0000000000402F57  Unknown               Unknown  Unknown
dmrcc              0000000000401B3D  Unknown               Unknown  Unknown
dmrcc              00000000013AAE59  Unknown               Unknown  Unknown
dmrcc              0000000000401A2A  Unknown               Unknown  Unknown
forrtl: No such file or directory
forrtl: severe (29): file not found, unit 75, file /home/work/scratch/mrcc_168425/KEYWD
Image              PC                Routine            Line        Source             
dmrcc              000000000131B3EC  Unknown               Unknown  Unknown
dmrcc              00000000004DA346  Unknown               Unknown  Unknown
dmrcc              00000000005432D5  Unknown               Unknown  Unknown
dmrcc              0000000000543C32  Unknown               Unknown  Unknown
dmrcc              000000000054274C  Unknown               Unknown  Unknown
dmrcc              000000000040D9CF  Unknown               Unknown  Unknown
dmrcc              0000000000402F57  Unknown               Unknown  Unknown
dmrcc              0000000000401B3D  Unknown               Unknown  Unknown
dmrcc              00000000013AAE59  Unknown               Unknown  Unknown
dmrcc              0000000000401A2A  Unknown               Unknown  Unknown
forrtl: No such file or directory
forrtl: severe (29): file not found, unit 75, file /home/work/scratch/mrcc_168425/KEYWD
Image              PC                Routine            Line        Source             
dmrcc              000000000131B3EC  Unknown               Unknown  Unknown
dmrcc              00000000004DA346  Unknown               Unknown  Unknown
dmrcc              00000000005432D5  Unknown               Unknown  Unknown
dmrcc              0000000000543C32  Unknown               Unknown  Unknown
dmrcc              000000000054274C  Unknown               Unknown  Unknown
dmrcc              000000000040D9CF  Unknown               Unknown  Unknown
dmrcc              0000000000402F57  Unknown               Unknown  Unknown
dmrcc              0000000000401B3D  Unknown               Unknown  Unknown
dmrcc              00000000013AAE59  Unknown               Unknown  Unknown
dmrcc              0000000000401A2A  Unknown               Unknown  Unknown
^CTraceback (most recent call last):
  File "/home/work/psi4/install/bin/psi4", line 387, in <module>
    exec(content)
  File "<string>", line 22, in <module>
  File "/home/work/psi4/install/lib/psi4/driver/driver.py", line 1594, in frequency
    H, wfn = hessian(name, return_wfn=True, molecule=molecule, **kwargs)
  File "/home/work/psi4/install/lib/psi4/driver/driver.py", line 1431, in hessian
    plan.compute()
  File "/home/work/psi4/install/lib/psi4/driver/driver_findif.py", line 1314, in compute
    t.compute(client=client)
  File "/home/work/psi4/install/lib/psi4/driver/task_base.py", line 179, in compute
    self.result = qcng.compute(
  File "/home/susi/.conda/envs/p4env/lib/python3.10/site-packages/qcengine/compute.py", line 108, in compute
    output_data = executor.compute(input_data, config)
  File "/home/susi/.conda/envs/p4env/lib/python3.10/site-packages/qcengine/programs/psi4.py", line 233, in compute
    output_data = psi4.schema_wrapper.run_qcschema(input_model, postclean=False).dict()
  File "/home/work/psi4/install/lib/psi4/driver/schema_wrapper.py", line 460, in run_qcschema
    ret_data = run_json_qcschema(input_model.dict(), clean, False, keep_wfn=keep_wfn)
  File "/home/work/psi4/install/lib/psi4/driver/schema_wrapper.py", line 626, in run_json_qcschema
    val, wfn = methods_dict_[json_data["driver"]](method, **kwargs)
  File "/home/work/psi4/install/lib/psi4/driver/driver.py", line 525, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/work/psi4/install/lib/psi4/driver/procrouting/proc.py", line 1386, in select_mrcc
    return func(name, **kwargs)
  File "/home/work/psi4/install/lib/psi4/driver/procrouting/proc.py", line 4935, in run_mrcc
    ref_wfn = scf_helper(name, **kwargs)
  File "/home/work/psi4/install/lib/psi4/driver/procrouting/proc.py", line 1887, in scf_helper
    e_scf = scf_wfn.compute_energy()
  File "/home/work/psi4/install/lib/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 82, in scf_compute_energy
    self.initialize()
  File "/home/work/psi4/install/lib/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 223, in scf_initialize
    self.guess()
KeyboardInterrupt
```

**Comment by TiborGY** [comment]
Do you have all the patches installed?

**Comment by TiborGY** [comment]
> > Do you have all the patches installed?
> 
> Define patches

Sorry, should have clarified.
https://www.mrcc.hu/index.php/download-mrcc/mrcc-binary-2/category/5-mrcc-patches

**Comment by loriab** [comment]
I've tested the mrcc interface within about a year. _But_ I only have the old mrcc (c. 2014) before it learned how to do SCF itself.

**Comment by TiborGY** [comment]
> I've tested the mrcc interface within about a year. _But_ I only have the old mrcc (c. 2014) before it learned how to do SCF itself.

I fuzzily remember being able to successfully run the tests with a version from a couple years ago, so 2020-22 era MRCC was OK I think, but I remember having to install the patches, otherwise neither Psi4 or Molpro would work with MRCC.

**Comment by susilehtola** [comment]
> > > Do you have all the patches installed?
> > 
> > 
> > Define patches
> 
> Sorry, should have clarified. https://www.mrcc.hu/index.php/download-mrcc/mrcc-binary-2/category/5-mrcc-patches

Wow, talking about a blast from the past....

**Comment by susilehtola** [comment]
After installing the binary patches, I get the error
```
psi4.driver.p4util.exceptions.MissingMethodError: Method=ccsdt is not available for any derivative level. Did you mean? ccd ccsd ccsd(t) cisd cisdt cisdtq lccsd ksdt
```

**Comment by loriab** [comment]
Make sure `dmrcc` is in your path https://github.com/psi4/psi4/blob/master/psi4/driver/procrouting/proc_table.py#L269

other logic is https://github.com/psi4/psi4/blob/master/psi4/driver/procrouting/proc.py#L1369
