### ISSUE TITLE
Unrecognized point group bits: 80

### ISSUE THREAD

**Issue by jevandezande** [psi4/psi4#3213]
When running Psi4 1.9.1, the following structure causes Psi4 to crash, but shifting it a little bit makes things work fine.

```
molecule {
  C     0.0000000182   -0.0000000013    0.0000000175
  H    -0.6691384315    0.8462762237   -0.0845771730
  H    -0.3913180530   -0.8282585144   -0.5761431456
  H     0.0839750469   -0.2910425067    1.0389058590
  H     0.9764814973    0.2730248868   -0.3781855106
}

energy("BP86/sto-3g")
```

Traceback
```
Traceback (most recent call last):
  File "/home/jevandezande/rowansci/peregrine/.pixi/envs/dev/bin/psi4", line 387, in <module>
    exec(content)
  File "<string>", line 26, in <module>
  File "/home/jevandezande/rowansci/peregrine/.pixi/envs/dev/lib/python3.12/site-packages/psi4/driver/driver.py", line 525, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jevandezande/rowansci/peregrine/.pixi/envs/dev/lib/python3.12/site-packages/psi4/driver/procrouting/proc.py", line 2588, in run_scf
    scf_wfn = scf_helper(name, post_scf=False, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jevandezande/rowansci/peregrine/.pixi/envs/dev/lib/python3.12/site-packages/psi4/driver/procrouting/proc.py", line 1778, in scf_helper
    base_wfn = core.Wavefunction.build(scf_molecule, core.get_global_option('BASIS'))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jevandezande/rowansci/peregrine/.pixi/envs/dev/lib/python3.12/site-packages/psi4/driver/p4util/python_helpers.py", line 217, in _core_wavefunction_build
    basis = core.BasisSet.build(mol, "ORBITAL", basis, quiet=quiet)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jevandezande/rowansci/peregrine/.pixi/envs/dev/lib/python3.12/site-packages/psi4/driver/p4util/python_helpers.py", line 157, in _pybuild_basis
    bs, basisdict = qcdb.BasisSet.pyconstruct(mol.to_dict(),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jevandezande/rowansci/peregrine/.pixi/envs/dev/lib/python3.12/site-packages/psi4/driver/qcdb/libmintsbasisset.py", line 722, in pyconstruct
    bs, msg, ecp = BasisSet.construct(parser, mol,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jevandezande/rowansci/peregrine/.pixi/envs/dev/lib/python3.12/site-packages/psi4/driver/qcdb/libmintsbasisset.py", line 984, in construct
    oneatombasis = BasisSet(basisset, at)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jevandezande/rowansci/peregrine/.pixi/envs/dev/lib/python3.12/site-packages/psi4/driver/qcdb/libmintsbasisset.py", line 136, in __init__
    self.constructor_basisset_center(*args)
  File "/home/jevandezande/rowansci/peregrine/.pixi/envs/dev/lib/python3.12/site-packages/psi4/driver/qcdb/libmintsbasisset.py", line 423, in constructor_basisset_center
    self.molecule = Molecule.from_arrays(elem=[mol.symbol(center)],
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jevandezande/rowansci/peregrine/.pixi/envs/dev/lib/python3.12/site-packages/psi4/driver/qcdb/molecule.py", line 1237, in from_arrays
    return Molecule.from_dict(molrec)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jevandezande/rowansci/peregrine/.pixi/envs/dev/lib/python3.12/site-packages/psi4/driver/qcdb/molecule.py", line 1672, in from_dict
    mol._internal_from_dict(molrec=molrec, verbose=verbose)
  File "/home/jevandezande/rowansci/peregrine/.pixi/envs/dev/lib/python3.12/site-packages/psi4/driver/qcdb/molecule.py", line 1749, in _internal_from_dict
    self.update_geometry()
  File "/home/jevandezande/rowansci/peregrine/.pixi/envs/dev/lib/python3.12/site-packages/psi4/driver/qcdb/libmintsmolecule.py", line 1570, in update_geometry
    self.set_point_group(self.find_point_group())
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jevandezande/rowansci/peregrine/.pixi/envs/dev/lib/python3.12/site-packages/psi4/driver/qcdb/libmintsmolecule.py", line 2423, in find_point_group
    pg = self.find_highest_point_group(tol)  # D2h subgroup
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jevandezande/rowansci/peregrine/.pixi/envs/dev/lib/python3.12/site-packages/psi4/driver/qcdb/libmintsmolecule.py", line 2523, in find_highest_point_group
    return PointGroup(pg_bits)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/jevandezande/rowansci/peregrine/.pixi/envs/dev/lib/python3.12/site-packages/psi4/driver/qcdb/libmintspointgrp.py", line 1530, in __init__
    self.constructor_bits(*args)
  File "/home/jevandezande/rowansci/peregrine/.pixi/envs/dev/lib/python3.12/site-packages/psi4/driver/qcdb/libmintspointgrp.py", line 1573, in constructor_bits
    self.symb = self.bits_to_basic_name(self.PYbits)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jevandezande/rowansci/peregrine/.pixi/envs/dev/lib/python3.12/site-packages/psi4/driver/qcdb/libmintspointgrp.py", line 1755, in bits_to_basic_name
    raise ValidationError('Unrecognized point group bits: %d\n' % (bits))

psi4.driver.qcdb.exceptions.ValidationError: Unrecognized point group bits: 80



Printing out the relevant lines from the Psithon --> Python processed input file:
      H    -0.3913180530   -0.8282585144   -0.5761431456
      H     0.0839750469   -0.2910425067    1.0389058590
      H     0.9764814973    0.2730248868   -0.3781855106
    """)
    core.IO.set_default_namespace("")
--> energy("BP86/sto-3g")

!------------------------------------!
!                                    !
!  Unrecognized point group bits: 80 !
!                                    !
!------------------------------------!

    Psi4 stopped on: Friday, 30 August 2024 04:55PM
    Psi4 wall time for execution: 0:00:00.03

*** Psi4 encountered an error. Buy a developer more coffee!
*** Resources and help at github.com/psi4/psi4.
```

**Comment by loriab** [comment]
Thanks, another one for #948 . Hopefully the slight shift is ok.

**Comment by jevandezande** [comment]
A similar geometry results in `Unrecognized point group bits: 115`

```
C     0.0000000182   -0.0000000013    0.0000000175
H    -0.6691384190    0.8462762017   -0.0845771731
H    -0.3913180466   -0.8282585434   -0.5761431408
H     0.0839750436   -0.2910425113    1.0389058623
H     0.9764814897    0.2730248785   -0.3781855142
```
