### ISSUE TITLE
psi4 1.9.1 fails to run

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#3214]
A fresh compile of psi4 1.9.1 on Fedora (yay, finally updating from 1.3.2!) fails to run; all the tests fail with the error
```
/usr/include/c++/14/bits/stl_vector.h:1130: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = double; _Alloc = std::allocator<double>; reference = double&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
Exit Status: overall (1)
```
which suggests that there is critical path code that is accessing a `std::vector` out-of-bounds.

All Fedora packages are compiled with the following default optimization flags
```
-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Wno-complain-wrong-lang -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer
```

**Comment by susilehtola** [comment]
I am unable to produce a backtrace at the moment, since the build is running in a chroot. The key is to include `-Wp,-D_GLIBCXX_ASSERTIONS ` in the compile flags.

**Comment by susilehtola** [comment]
The backtrace was wrong; the conda installation was corrupt and even `xc-info` failed to run.

The real issue turned out to be fixed by #3194.

**Comment by susilehtola** [comment]
Actually, there are more failures
```
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0)
    at pthread_kill.c:44
#1  0x00007f21b9c426d3 in __pthread_kill_internal (threadid=<optimized out>, signo=6) at pthread_kill.c:78
#2  0x00007f21b9be9c4e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007f21b9bd1902 in __GI_abort () at abort.c:79
#4  0x00007f21862e80af in std::__glibcxx_assert_fail (file=<optimized out>, line=<optimized out>, 
    function=<optimized out>, condition=<optimized out>)
    at ../../../../../libstdc++-v3/src/c++11/assert_fail.cc:41
#5  0x00007f21aa275614 in std::vector<double const*, libint2::detail::ext_stack_allocator<double const*, 121ul> >::operator[] (this=0x56025b76c988, __n=6) at /usr/include/c++/14/bits/stl_vector.h:1149
#6  0x00007f21aa2a709b in psi::Libint2TwoElectronInt::compute_shell_deriv1 (this=0x56025b7bb980, s1=0, s2=0, 
    s3=0, s4=0) at /home/work/psi4-1.9.1/psi4/src/psi4/libmints/eribase.cc:3245
#7  0x00007f21a9f71d73 in _ZN3psi11MintsHelper11metric_gradERSt3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt10shared_ptrINS_6MatrixEESt4lessIS7_ESaISt4pairIKS7_SA_EEERSE_._omp_fn.0(void) ()
    at /home/work/psi4-1.9.1/psi4/src/psi4/libmints/mintshelper.cc:2343
#8  0x00007f219d9a89c4 in __kmp_api_GOMP_parallel_40_alias ()
   from /home/susi/.conda/envs/p4env/lib/libgomp.so.1
#9  0x00007f21a9f5f757 in psi::MintsHelper::metric_grad (this=0x56025ac87f20, D=..., aux_name=...)
    at /home/work/psi4-1.9.1/psi4/src/psi4/libmints/mintshelper.cc:2335
#10 0x00007f21a9b85c92 in psi::scfgrad::DFJKGrad::build_AB_x_terms (this=0x56025a8b4200)
    at /home/work/psi4-1.9.1/psi4/src/psi4/scfgrad/jk_grad.cc:862
#11 0x00007f21a9b818c2 in psi::scfgrad::DFJKGrad::compute_gradient (this=0x56025a8b4200)
--Type <RET> for more, q to quit, c to continue without paging--
    at /home/work/psi4-1.9.1/psi4/src/psi4/scfgrad/jk_grad.cc:257
#12 0x00007f21a9b7595c in psi::scfgrad::SCFDeriv::compute_gradient (this=0x7ffc67b35840)
    at /home/work/psi4-1.9.1/psi4/src/psi4/scfgrad/scf_grad.cc:249
#13 0x00007f21a9b3855d in psi::scfgrad::scfgrad (ref_wfn=..., options=...)
    at /home/work/psi4-1.9.1/psi4/src/psi4/scfgrad/wrapper.cc:46
#14 0x00007f21a841948d in py_psi_scfgrad (ref_wfn=...) at /home/work/psi4-1.9.1/psi4/src/core.cc:317
#15 0x00007f21a84ae799 in pybind11::detail::argument_loader<std::shared_ptr<psi::scf::HF> >::call_impl<std::shared_ptr<psi::Matrix>, std::shared_ptr<psi::Matrix> (*&)(std::shared_ptr<psi::scf::HF>), 0ul, pybind11::detail::void_type>(std::shared_ptr<psi::Matrix> (*&)(std::shared_ptr<psi::scf::HF>), std::integer_sequence<unsigned long, 0ul>, pybind11::detail::void_type&&) && (this=0x7ffc67b35f10, 
    f=@0x56025a2cca88: 0x7f21a84193f0 <py_psi_scfgrad(std::shared_ptr<psi::scf::HF>)>)
    at /usr/include/pybind11/cast.h:1480
#16 0x00007f21a84a146f in pybind11::detail::argument_loader<std::shared_ptr<psi::scf::HF> >::call<std::shared_ptr<psi::Matrix>, pybind11::detail::void_type, std::shared_ptr<psi::Matrix> (*&)(std::shared_ptr<psi::scf::HF>)>(std::shared_ptr<psi::Matrix> (*&)(std::shared_ptr<psi::scf::HF>)) && (this=0x7ffc67b35f10, 
    f=@0x56025a2cca88: 0x7f21a84193f0 <py_psi_scfgrad(std::shared_ptr<psi::scf::HF>)>)
    at /usr/include/pybind11/cast.h:1449
#17 0x00007f21a848627d in pybind11::cpp_function::initialize<std::shared_ptr<psi::Matrix> (*&)(std::shared_ptr<psi::scf::HF>), std::shared_ptr<psi::Matrix>, std::shared_ptr<psi::scf::HF>, pybind11::name, pybind11::scope, pybind11::sibling, pybind11::arg, char [61]>(std::shared_ptr<psi::Matrix> (*&)(std::shared_ptr<psi::scf::HF>), std::shared_ptr<psi::Matrix> (*)(std::shared_ptr<psi::scf::HF>), pybind11::name const&, pybind11::scope const&, pybind11::sibling const&, pybind11::arg const&, char const (&) [61])::{lambda(pybind11::detail::function_call&)--Type <RET> for more, q to quit, c to continue without paging--
#1}::operator()(pybind11::detail::function_call&) const (__closure=0x0, call=...)
    at /usr/include/pybind11/pybind11.h:254
#18 0x00007f21a84864e2 in pybind11::cpp_function::initialize<std::shared_ptr<psi::Matrix> (*&)(std::shared_ptr<psi::scf::HF>), std::shared_ptr<psi::Matrix>, std::shared_ptr<psi::scf::HF>, pybind11::name, pybind11::scope, pybind11::sibling, pybind11::arg, char [61]>(std::shared_ptr<psi::Matrix> (*&)(std::shared_ptr<psi::scf::HF>), std::shared_ptr<psi::Matrix> (*)(std::shared_ptr<psi::scf::HF>), pybind11::name const&, pybind11::scope const&, pybind11::sibling const&, pybind11::arg const&, char const (&) [61])::{lambda(pybind11::detail::function_call&)#1}::_FUN(pybind11::detail::function_call&) () at /usr/include/pybind11/pybind11.h:224

#19 0x00007f21a8441138 in pybind11::cpp_function::dispatcher (self=0x7f2185ffe790, args_in=0x7f21476cd000, 
    kwargs_in=0x0) at /usr/include/pybind11/pybind11.h:946
#20 0x000056022a991401 in cfunction_call (func=0x7f2186005210, args=0x7f21476cd000, kwargs=0x0)
    at /usr/local/src/conda/python-3.12.5/Objects/methodobject.c:537
#21 0x000056022a97109b in _PyObject_MakeTpCall (tstate=0x56022ae03058 <_PyRuntime+459704>, 
    callable=0x7f2186005210, args=<optimized out>, nargs=1, keywords=0x0)
    at /usr/local/src/conda/python-3.12.5/Objects/call.c:240
#22 0x000056022a877f65 in _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=0x7f21b9ea9af0, 
    throwflag=<optimized out>) at Python/bytecodes.c:2714
#23 0x000056022aa2bece in PyEval_EvalCode (co=co@entry=0x56025a2e86d0, globals=globals@entry=0x7f21abff9900, 
    locals=locals@entry=0x7f21abff9900) at /usr/local/src/conda/python-3.12.5/Python/ceval.c:578
#24 0x000056022aa50d9a in run_eval_code_obj (tstate=tstate@entry=0x56022ae03058 <_PyRuntime+459704>, 
    co=co@entry=0x56025a2e86d0, globals=globals@entry=0x7f21abff9900, locals=locals@entry=0x7f21abff9900)
    at /usr/local/src/conda/python-3.12.5/Python/pythonrun.c:1722
--Type <RET> for more, q to quit, c to continue without paging--
#25 0x000056022aa4bf4b in run_mod (mod=mod@entry=0x56025a306440, 
    filename=filename@entry=0x56022ad98b00 <_PyRuntime+24160>, globals=globals@entry=0x7f21abff9900, 
    locals=locals@entry=0x7f21abff9900, flags=flags@entry=0x7ffc67b366b8, arena=arena@entry=0x7f215015b370)
    at /usr/local/src/conda/python-3.12.5/Python/pythonrun.c:1743
#26 0x000056022aa3ccb2 in PyRun_StringFlags (
    str=str@entry=0x56025a2d4098 "\nimport psi4\nfrom psi4 import *\nfrom psi4.core import *\nfrom psi4.driver.diatomic import anharmonicity\nfrom psi4.driver.gaussian_n import *\nfrom psi4.driver.frac import ip_fitting, frac_traverse\nfrom "..., start=start@entry=257, globals=globals@entry=0x7f21abff9900, 
    locals=locals@entry=0x7f21abff9900, flags=flags@entry=0x7ffc67b366b8)
    at /usr/local/src/conda/python-3.12.5/Python/pythonrun.c:1618
#27 0x000056022aa47f97 in builtin_exec_impl (module=<optimized out>, closure=<optimized out>, 
    locals=0x7f21abff9900, globals=0x7f21abff9900, source=0x56025a2d4070)
    at /usr/local/src/conda/python-3.12.5/Python/bltinmodule.c:1121
#28 builtin_exec (module=<optimized out>, args=<optimized out>, nargs=<optimized out>, 
    kwnames=<optimized out>) at /usr/local/src/conda/python-3.12.5/Python/clinic/bltinmodule.c.h:586
#29 0x000056022a986246 in cfunction_vectorcall_FASTCALL_KEYWORDS (func=<optimized out>, args=0x7f21b9ea9078, 
    nargsf=<optimized out>, kwnames=0x0) at /usr/local/src/conda/python-3.12.5/Objects/methodobject.c:438
#30 0x000056022a985fcf in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=9223372036854775809, 
    args=0x7f21b9ea9078, callable=0x7f21abf9c770, tstate=0x56022ae03058 <_PyRuntime+459704>)
    at /usr/local/src/conda/python-3.12.5/Include/internal/pycore_call.h:92
#31 PyObject_Vectorcall (callable=0x7f21abf9c770, args=0x7f21b9ea9078, nargsf=9223372036854775809, 
    kwnames=0x0) at /usr/local/src/conda/python-3.12.5/Objects/call.c:325
--Type <RET> for more, q to quit, c to continue without paging--
#32 0x000056022a877f65 in _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=0x7f21b9ea9020, 
    throwflag=<optimized out>) at Python/bytecodes.c:2714
#33 0x000056022aa2bece in PyEval_EvalCode (co=co@entry=0x560259e3fbd0, globals=globals@entry=0x7f21abff9900, 
    locals=locals@entry=0x7f21abff9900) at /usr/local/src/conda/python-3.12.5/Python/ceval.c:578
#34 0x000056022aa50d9a in run_eval_code_obj (tstate=tstate@entry=0x56022ae03058 <_PyRuntime+459704>, 
    co=co@entry=0x560259e3fbd0, globals=globals@entry=0x7f21abff9900, locals=locals@entry=0x7f21abff9900)
    at /usr/local/src/conda/python-3.12.5/Python/pythonrun.c:1722
#35 0x000056022aa4bf4b in run_mod (mod=mod@entry=0x560259ddd528, filename=filename@entry=0x7f21abe2c090, 
    globals=globals@entry=0x7f21abff9900, locals=locals@entry=0x7f21abff9900, 
    flags=flags@entry=0x7ffc67b36bd0, arena=arena@entry=0x7f21abf1bcb0)
    at /usr/local/src/conda/python-3.12.5/Python/pythonrun.c:1743
#36 0x000056022aa64bd0 in pyrun_file (fp=fp@entry=0x560259cb7470, filename=filename@entry=0x7f21abe2c090, 
    start=start@entry=257, globals=globals@entry=0x7f21abff9900, locals=locals@entry=0x7f21abff9900, 
    closeit=closeit@entry=1, flags=0x7ffc67b36bd0)
    at /usr/local/src/conda/python-3.12.5/Python/pythonrun.c:1643
#37 0x000056022aa6420e in _PyRun_SimpleFileObject (fp=0x560259cb7470, filename=0x7f21abe2c090, closeit=1, 
    flags=0x7ffc67b36bd0) at /usr/local/src/conda/python-3.12.5/Python/pythonrun.c:433
#38 0x000056022aa63ee4 in _PyRun_AnyFileObject (fp=0x560259cb7470, filename=filename@entry=0x7f21abe2c090, 
    closeit=closeit@entry=1, flags=flags@entry=0x7ffc67b36bd0)
    at /usr/local/src/conda/python-3.12.5/Python/pythonrun.c:78
#39 0x000056022aa5cf42 in pymain_run_file_obj (skip_source_first_line=0, filename=0x7f21abe2c090, 
    program_name=0x7f21abe2c270) at /usr/local/src/conda/python-3.12.5/Modules/main.c:360
--Type <RET> for more, q to quit, c to continue without paging--
#40 pymain_run_file (config=0x56022ada5c38 <_PyRuntime+77720>)
    at /usr/local/src/conda/python-3.12.5/Modules/main.c:379
#41 pymain_run_python (exitcode=0x7ffc67b36ba4) at /usr/local/src/conda/python-3.12.5/Modules/main.c:633
#42 Py_RunMain () at /usr/local/src/conda/python-3.12.5/Modules/main.c:713
#43 0x000056022aa147e7 in Py_BytesMain (argc=<optimized out>, argv=<optimized out>)
    at /usr/local/src/conda/python-3.12.5/Modules/main.c:767
#44 0x00007f21b9bd3088 in __libc_start_call_main (main=main@entry=0x56022aa14720 <main>, argc=argc@entry=6, 
    argv=argv@entry=0x7ffc67b36e38) at ../sysdeps/nptl/libc_start_call_main.h:58
#45 0x00007f21b9bd314b in __libc_start_main_impl (main=0x56022aa14720 <main>, argc=6, argv=0x7ffc67b36e38, 
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffc67b36e28)
    at ../csu/libc-start.c:360
#46 0x000056022aa14681 in _start ()
(gdb) 
```
which corresponds to
https://github.com/psi4/psi4/blob/3484122eaaec9e185bc33581c6cdef4669f21534/psi4/src/psi4/libmints/eribase.cc#L241

**Comment by TiborGY** [comment]
Should be fixed now with 1.10, right?
