### ISSUE TITLE
ImportError: libpugixml.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by sustech-lz** [psi4/psi4#3254]
Traceback (most recent call last):
  File "/home/lz/anaconda3/envs/digress/bin/psi4", line 232, in <module>
    import psi4  # isort:skip
  File "/home/lz/anaconda3/envs/digress/lib/python3.9/site-packages/psi4/__init__.py", line 71, in <module>
    from . import core
ImportError: libpugixml.so.1: cannot open shared object file: No such file or directory

**Comment by JonathonMisiewicz** [comment]
This isn't enough information.

How did you install Psi4? Did you try to install Psi4 through means other than conda? What's the output of conda list? What's your operating system? What did you do to to produce this input file?

**Comment by corinwagen** [comment]
Have you tried installing `pugixml`? A quick search suggests you can do so through [homebrew](https://formulae.brew.sh/formula/pugixml), [pip](https://pypi.org/project/pugixml/), or [conda](https://anaconda.org/conda-forge/pugixml).

**Comment by loriab** [comment]
Post your `conda list` please. In particular, I'm looking for ecpint, as I think xml is a dependency there.

**Comment by sustech-lz** [comment]
<img width="1190" alt="image" src="https://github.com/user-attachments/assets/b8e2f6b8-d894-4c97-aea9-920ff58d9120" />
<img width="1002" alt="image" src="https://github.com/user-attachments/assets/2f02dfc2-4ca8-4638-8711-cb59aac42d9e" />
<img width="1990" alt="image" src="https://github.com/user-attachments/assets/280744aa-dc97-42fc-867a-19d4179de4f6" />

Hello, apologies for the delayed response. I tried setting up a few different Conda environments to investigate the issue. Upon closer inspection, it seems that the .core file is missing from the installation package. Let me know if there are additional steps I should take or further information I can provide to help diagnose the problem.

**Comment by JonathonMisiewicz** [comment]
In the terminal, activate the conda environment that is having these problems (which seems to be named `digress`), type the command `conda list`, and then post the output here.

**Comment by AlexL1996** [comment]
Hello, dear @loriab @JonathonMisiewicz !
I've faced with the same problem as other applicants, so I'll be very gratefulf for any help
Here is my problem: when I try to test PSI4 throught command psi4 --test, the program gives me:

Traceback (most recent call last):
  File "/home/alexlester/miniconda3/bin/psi4", line 232, in <module>
    import psi4  # isort:skip
    ^^^^^^^^^^^
  File "/home/alexlester/miniconda3/lib/python3.12/site-packages/psi4/__init__.py", line 71, in <module>
    from . import core
ImportError: /home/alexlester/miniconda3/lib/python3.12/site-packages/psi4/core.cpython-312-x86_64-linux-gnu.so: undefined symbol: __dkh_main_MOD_dkh


At the same time, I have to note, that commands psi4 --psiapi and psi4 --help gives me all information i.e. it works 

My path variables:

export PATH=/home/alexlester/miniconda3/lib/python3.12/site-packages/psi4:$PATH

export PATH=/home/alexlester/miniconda3/bin/psi4:$PATH

export LD_LIBRARY_PATH=/home/alexlester/miniconda3/lib:$LD_LIBRARY_PATH

export PYTHONPATH=/home/alexlester/miniconda3/lib/python3.12/site-packages:$PYTHONPATH

The commands "which python" and "which psi4" give me /home/alexlester/miniconda3/bin/python and /home/alexlester/miniconda3/bin/psi4, respectively. 

The command "conda list" gives me:

# packages in environment at /home/alexlester/miniconda3:
#

- [ ] 1. # Name                    Version                   Build  Channel
- [ ] 2. _libgcc_mutex             0.1                 conda_forge    conda-forge
- [ ] 3. _openmp_mutex             4.5                  2_kmp_llvm    conda-forge
- [ ] 4. anaconda-anon-usage       0.5.0           py312hfc0e8ea_100
- [ ] 5. annotated-types           0.6.0           py312h06a4308_0
- [ ] 6. archspec                  0.2.3              pyhd3eb1b0_0
- [ ] 7. boltons                   24.1.0          py312h06a4308_0
- [ ] 8. brotli-python             1.0.9           py312h6a678d5_9
- [ ] 9. bzip2                     1.0.8                h5eee18b_6
- [ ] 10. c-ares                    1.19.1               h5eee18b_0
- [ ] 11. ca-certificates           2025.1.31            hbcca054_0    conda-forge
- [ ] 12. certifi                   2025.1.31       py312h06a4308_0
- [ ] 13. cffi                      1.17.1          py312h1fdaa30_1
- [ ] 14. charset-normalizer        3.3.2              pyhd3eb1b0_0
- [ ] 15. colorama                  0.4.6              pyhd8ed1ab_1    conda-forge
- [ ] 16. conda                     25.1.1          py312h7900ff3_1    conda-forge
- [ ] 17. conda-anaconda-telemetry  0.1.2           py312h06a4308_0
- [ ] 18. conda-anaconda-tos        0.1.2           py312h06a4308_0
- [ ] 19. conda-content-trust       0.2.0           py312h06a4308_1
- [ ] 20. conda-libmamba-solver     25.1.1             pyhd3eb1b0_0
- [ ] 21. conda-package-handling    2.4.0           py312h06a4308_0
- [ ] 22. conda-package-streaming   0.11.0          py312h06a4308_0
- [ ] 23. cpp-expected              1.1.0                hdb19cb5_0
- [ ] 24. cryptography              43.0.3          py312h7825ff9_1
- [ ] 25. distro                    1.9.0           py312h06a4308_0
- [ ] 26. dkh                       1.2                  h173d85e_2    psi4
- [ ] 27. exceptiongroup            1.2.2              pyhd8ed1ab_1    conda-forge
- [ ] 28. expat                     2.6.4                h6a678d5_0
- [ ] 29. fmt                       11.0.2               h434a139_0    conda-forge
- [ ] 30. frozendict                2.4.2           py312h06a4308_0
- [ ] 31. gau2grid                  2.0.7                hd18ef5c_0    psi4
- [ ] 32. icu                       73.1                 h6a678d5_0
- [ ] 33. idna                      3.7             py312h06a4308_0
- [ ] 34. importlib-metadata        8.6.1              pyha770c72_0    conda-forge
- [ ] 35. importlib_metadata        8.6.1                hd8ed1ab_0    conda-forge
- [ ] 36. importlib_resources       6.5.2              pyhd8ed1ab_0    conda-forge
- [ ] 37. iniconfig                 2.0.0              pyhd8ed1ab_1    conda-forge
- [ ] 38. jsonpatch                 1.33            py312h06a4308_1
- [ ] 39. jsonpointer               2.1                pyhd3eb1b0_0
- [ ] 40. krb5                      1.20.1               h143b758_1
- [ ] 41. ld_impl_linux-64          2.40                 h12ee557_0
- [ ] 42. libarchive                3.7.7                hfab0078_0
- [ ] 43. libblas                   3.9.0            20_linux64_mkl    conda-forge
- [ ] 44. libcblas                  3.9.0            20_linux64_mkl    conda-forge
- [ ] 45. libcurl                   8.11.1               hc9e6f67_0
- [ ] 46. libecpint                 1.0.7                hfebba4c_0    psi4
- [ ] 47. libedit                   3.1.20230828         h5eee18b_0
- [ ] 48. libev                     4.33                 h7f8727e_1
- [ ] 49. libexpat                  2.6.4                h5888daf_0    conda-forge
- [ ] 50. libffi                    3.4.4                h6a678d5_1
- [ ] 51. libgcc                    14.2.0               h767d61c_2    conda-forge
- [ ] 52. libgcc-ng                 14.2.0               h69a702a_2    conda-forge
- [ ] 53. libgfortran               14.2.0               h69a702a_2    conda-forge
- [ ] 54. libgfortran-ng            14.2.0               h69a702a_2    conda-forge
- [ ] 55. libgfortran5              14.2.0               hf1ad2bd_2    conda-forge
- [ ] 56. libgomp                   14.2.0               h767d61c_2    conda-forge
- [ ] 57. libhwloc                  2.11.2          default_h0d58e46_1001    conda-forge
- [ ] 58. libint                    2.9.0                h23769fb_2    conda-forge
- [ ] 59. liblapack                 3.9.0            20_linux64_mkl    conda-forge
- [ ] 60. libmamba                  2.0.3                hf72d635_0    conda-forge
- [ ] 61. libmambapy                2.0.3           py312hf3f0a4e_0    conda-forge
- [ ] 62. libnghttp2                1.57.0               h2d74bed_0
- [ ] 63. libnsl                    2.0.1                hd590300_0    conda-forge
- [ ] 64. libpcm                    1.2.3                h4175798_8    conda-forge
- [ ] 65. libsolv                   0.7.30               he621ea3_1
- [ ] 66. libsqlite                 3.46.0               hde9e2c9_0    conda-forge
- [ ] 67. libssh2                   1.11.1               h251f7ec_0
- [ ] 68. libstdcxx                 14.2.0               h8f9b012_2    conda-forge
- [ ] 69. libstdcxx-ng              14.2.0               h4852527_2    conda-forge
- [ ] 70. libuuid                   2.38.1               h0b41bf4_0    conda-forge
- [ ] 71. libxc-c                   7.0.0            cpu_h20a523f_2    conda-forge
- [ ] 72. libxcrypt                 4.4.36               hd590300_1    conda-forge
- [ ] 73. libxml2                   2.13.5               hfdd30dd_0
- [ ] 74. libzlib                   1.2.13               h4ab18f5_6    conda-forge
- [ ] 75. llvm-openmp               19.1.7               h024ca30_0    conda-forge
- [ ] 76. lz4-c                     1.9.4                h6a678d5_1
- [ ] 77. markdown-it-py            2.2.0           py312h06a4308_1
- [ ] 78. mdurl                     0.1.0           py312h06a4308_0
- [ ] 79. menuinst                  2.2.0           py312h06a4308_1
- [ ] 80. mkl                       2023.2.0         h84fe81f_50496    conda-forge
- [ ] 81. msgpack-python            1.1.0           py312h68727a3_0    conda-forge
- [ ] 82. ncurses                   6.4                  h6a678d5_0
- [ ] 83. networkx                  3.4.2              pyh267e887_2    conda-forge
- [ ] 84. nlohmann_json             3.11.3               he02047a_1    conda-forge
- [ ] 85. numpy                     2.2.3           py312h72c5963_0    conda-forge
- [ ] 86. openssl                   3.4.1                h7b32b05_0    conda-forge
- [ ] 87. optking                   0.3.0              pyhd8ed1ab_0    conda-forge
- [ ] 88. packaging                 24.2            py312h06a4308_0
- [ ] 89. pcmsolver                 1.2.3                     py_14    conda-forge
- [ ] 90. pcre2                     10.42                hebb0a14_1
- [ ] 91. pint                      0.17               pyhd8ed1ab_0    psi4
- [ ] 92. pip                       25.0            py312h06a4308_0
- [ ] 93. platformdirs              3.10.0          py312h06a4308_0
- [ ] 94. pluggy                    1.5.0           py312h06a4308_0
- [ ] 95. psi4                      1.9.1           py312ha9da0b5_8    conda-forge
- [ ] 96. psutil                    6.1.1           py312h66e93f0_0    conda-forge
- [ ] 97. pugixml                   1.15                 h3f63f65_0    conda-forge
- [ ] 98. py-cpuinfo                9.0.0              pyhd8ed1ab_1    conda-forge
- [ ] 99. pybind11-abi              4                    hd8ed1ab_3    conda-forge
- [ ] 100. pycosat                   0.6.6           py312h5eee18b_2
- [ ] 101. pycparser                 2.21               pyhd3eb1b0_0
- [ ] 102. pydantic                  2.10.3          py312h06a4308_0
- [ ] 103. pydantic-core             2.27.1          py312h4aa5aa6_0
- [ ] 104. pygments                  2.15.1          py312h06a4308_1
- [ ] 105. pysocks                   1.7.1           py312h06a4308_0
- [ ] 106. pytest                    7.4.4              pyhd8ed1ab_0    conda-forge
- [ ] 107. python                    3.12.2          hab00c5b_0_cpython    conda-forge
- [ ] 108. python_abi                3.12                    5_cp312    conda-forge
- [ ] 109. pyyaml                    6.0.2           py312h178313f_2    conda-forge
- [ ] 110. qcelemental               0.29.0             pyhd8ed1ab_0    conda-forge
- [ ] 111. qcengine                  0.31.0             pyhd8ed1ab_0    conda-forge
- [ ] 112. readline                  8.2                  h5eee18b_0
- [ ] 113. reproc                    14.2.4               h6a678d5_2
- [ ] 114. reproc-cpp                14.2.4               h6a678d5_2
- [ ] 115. requests                  2.32.3          py312h06a4308_1
- [ ] 116. rich                      13.9.4          py312h06a4308_0
- [ ] 117. ruamel.yaml               0.18.6          py312h5eee18b_0
- [ ] 118. ruamel.yaml.clib          0.2.8           py312h5eee18b_0
- [ ] 119. scipy                     1.15.2          py312ha707e6e_0    conda-forge
- [ ] 120. setuptools                75.8.0          py312h06a4308_0
- [ ] 121. simdjson                  3.10.1               hdb19cb5_0
- [ ] 122. spdlog                    1.14.1               hed91bc2_1    conda-forge
- [ ] 123. sqlite                    3.45.3               h5eee18b_0
- [ ] 124. tbb                       2021.13.0            hceb3a55_1    conda-forge
- [ ] 125. tk                        8.6.14               h39e8969_0
- [ ] 126. tomli                     2.2.1              pyhd8ed1ab_1    conda-forge
- [ ] 127. tqdm                      4.67.1          py312he106c6f_0
- [ ] 128. truststore                0.10.0          py312h06a4308_0
- [ ] 129. typing-extensions         4.12.2          py312h06a4308_0
- [ ] 130. typing_extensions         4.12.2          py312h06a4308_0
- [ ] 131. tzdata                    2025a                h04d1e81_0
- [ ] 132. urllib3                   2.3.0           py312h06a4308_0
- [ ] 133. wheel                     0.45.1          py312h06a4308_0
- [ ] 134. xz                        5.4.6                h5eee18b_1
- [ ] 135. yaml                      0.2.5                h7f98852_2    conda-forge
- [ ] 136. yaml-cpp                  0.8.0                h6a678d5_1
- [ ] 137. zipp                      3.21.0             pyhd8ed1ab_1    conda-forge
- [ ] 138. zlib                      1.2.13               h4ab18f5_6    conda-forge
- [ ] 139. zstandard                 0.23.0          py312h2c38b39_1
- [ ] 140. zstd                      1.5.6                hc292b87_0
- [ ] 141. 

So, I need your help, cause I'm in little frustration because of this (:
