### ISSUE TITLE
DF-MP3 gradients fail

### ISSUE THREAD

**Issue by bozkaya** [psi4/psi4#428]
When I run a df-mp3 geometry opt job I got the following error:

An error has occurred python-side. Traceback (most recent call last):

  File "<string>", line 44, in <module>

  File "/usr/local/programs/psi4intel/share/psi4/python/driver.py", line 1019, in optimize
    G, wfn = gradient(lowername, return_wfn=True, molecule=moleculeclone, **kwargs)

  File "/usr/local/programs/psi4intel/share/psi4/python/driver.py", line 588, in gradient
    wfn = procedures['gradient'][lowername](lowername, molecule=molecule, **kwargs)

  File "/usr/local/programs/psi4intel/share/psi4/python/procedures/proc.py", line 364, in select_mp3_gradient
    return func(name, **kwargs)

  File "/usr/local/programs/psi4intel/share/psi4/python/procedures/proc.py", line 1381, in run_dfocc_gradient
    dfocc_wfn = psi4.dfocc(ref_wfn)

RuntimeError:
Fatal Error: PSIO Error
Error occurred in file: /home/ubgroup/psi4/src/lib/libpsio/error.cc on line: 128
The most recent 5 function calls were:

psi::PsiException::PsiException(std::string, char const*, int)
psi::psio_error(unsigned int, unsigned int)
psi::PSIO::read(unsigned int, char const*, char*, unsigned long, psi::psio_address, psi::psio_address*)
psi::PSIO::read_entry(unsigned int, char const*, char*, unsigned long)
psi::dfoccwave::Tensor2d::read(boost::shared_ptr<psi::PSIO>, unsigned int)

@loriab

**Comment by bozkaya** [comment]
I got it. It is my fault. I comment out the wrong line):

@loriab
