### ISSUE TITLE
PSIO error in dmrg calculation

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#464]
I'm trying to reproduce some dmrg calculations in the literature on polyenes in the STO-3G basis set.

However, I get the following error

```
###########################################################
###                                                     ###
###                       DMRG-SCF                      ###
###                                                     ###
###            CheMPS2 by Sebastian Wouters             ###
###        https://github.com/SebWouters/CheMPS2        ###
###   Comput. Phys. Commun. 185 (6), 1501-1514 (2014)   ###
###                                                     ###
###########################################################

Number of variables in the x-matrix = 342
CheMPS2 output is temporarily written to the file output.dat.chemps2 and will be copied here.
iwl_buf_init: Can't open file 33
An error has occurred python-side. Traceback (most recent call last):

  File "<string>", line 80, in <module>

  File "/global/home/groups-sw/mhg/psi4/install/share/psi4/python/driver.py", line 444, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)

  File "/global/home/groups-sw/mhg/psi4/install/share/psi4/python/procedures/proc.py", line 2686, in run_dmrgci
    dmrg_wfn = psi4.dmrg(ref_wfn)

RuntimeError: 
Fatal Error: PSIO Error
Error occurred in file: /global/home/groups-sw/mhg/psi4/psi4.git/src/lib/libpsio/error.cc on line: 128
The most recent 5 function calls were:

psi::PsiException::PsiException(std::string, char const*, int)
psi::psio_error(unsigned int, unsigned int)
psi::PSIO::read(unsigned int, char const*, char*, unsigned long, psi::psio_address, psi::psio_address*)
psi::IWL::fetch()
psi::DiskJK::compute_JK()
```

when I try to run a calculation with

```
numOrbitals = [ 47 , 9 ]
R(O)HF DOCC = [ 28 , 4 ]
R(O)HF SOCC = [ 0 , 1 ]
frozen_docc = [ 9 , 0 ]
active      = [ 38 , 9 ]
virtual     = [ 0 , 0 ]
nElectrons  = 65
nEl. active = 47
```

I'm having trouble seeing why this would fail. First of all, the scratch partition on the node has over 2 TB of free space, and second, there are only 65 basis functions in the system, so even if one didn't use any kind of symmetries for the repulsion integrals, one would still only need 143MB of storage. All the jobs smaller than above run succesfully, and all the jobs larger than above fail with a similar error.

**Comment by loriab** [comment]
A diagnosis doesn't come to mind, but if you send a full input file, I can try it out.

**Comment by susilehtola** [comment]
Sure

```
molecule {
0 2
C
H 1 RCH
H 1 RCH 2 A
C 1 RCd 3 A 2 D180
H 4 RCH 1 A 3 D
C 4 RCs 5 A 2 D180
H 6 RCH 4 A 5 D180
C 6 RCd 7 A 4 D180
H 8 RCH 6 A 7 D180
C 8 RCs 9 A 6 D180
H 10 RCH 8 A 9 D180
C 10 RCd 11 A 8 D180
H 12 RCH 10 A 11 D180
C 12 RCs 13 A 10 D180
H 14 RCH 12 A 13 D180
C 14 RCd 15 A 12 D180
H 16 RCH 14 A 15 D180
C 16 RCs 17 A 14 D180
H 18 RCH 16 A 17 D180
H 18 RCH 16 A 19 D180

RCs=1.45
RCd=1.36
RCH=1.08
A=120.0
D=0.0
D180=180.0
}

set basis STO-3G
set reference rohf
set scf_type pk
set docc [ 28,  4 ]
set socc [  0,  1 ]
set e_convergence  1e-13
set d_convergence  1e-13
set ints_tolerance 0.0
# Include 20% old density
set damping_percentage 20
# and stop damping once density has converged to 1e-3
set damping_convergence 1e-3

set dmrg wfn_irrep            1
set dmrg wfn_multp            2
set dmrg frozen_docc [  9,  0 ]
set dmrg active      [ 38,  9 ]

set dmrg dmrg_states          [  250,  250 ]
set dmrg dmrg_e_convergence   [ 1e-8, 1e-8 ]
set dmrg dmrg_maxsweeps       [   10,    10 ]
set dmrg dmrg_noiseprefactors [ 0.05, 0.00 ]
set dmrg dmrg_dvdson_rtol     [ 1e-5, 1e-8 ]
set dmrg dmrg_print_corr      false
set dmrg dmrg_chkpt           false

set dmrg dmrg_active_space    loc
set dmrg dmrg_loc_random      true

set dmrg dmrg_molden          true  # DMRG-CI pseudocanonical orbitals
set dmrg dmrg_density_ao      true  # DMRG-CI density in the AO basis

energy('dmrg-ci')
```

**Comment by kannon92** [comment]
Could you try running:

    scf_energy, scf_wfn = energy('scf', return_wfn=True)
    energy('dmrg-ci', ref_wfn=scf_wfn)

I see this error quite a bit, but it is usually because I forget to use an scf_type that writes the integrals to disk.  I am not really confident that this would work, but it is worth a shot.

**Comment by loriab** [comment]
I updated the input file to the [new syntax](https://github.com/psi4/psi4/issues/150#issuecomment-228951911), and it does the SCF and seemingly gets into the DMRG. Is this any improvement to what you experienced?

```
molecule {
0 2
C
H 1 RCH
H 1 RCH 2 A
C 1 RCd 3 A 2 D180
H 4 RCH 1 A 3 D
C 4 RCs 5 A 2 D180
H 6 RCH 4 A 5 D180
C 6 RCd 7 A 4 D180
H 8 RCH 6 A 7 D180
C 8 RCs 9 A 6 D180
H 10 RCH 8 A 9 D180
C 10 RCd 11 A 8 D180
H 12 RCH 10 A 11 D180
C 12 RCs 13 A 10 D180
H 14 RCH 12 A 13 D180
C 14 RCd 15 A 12 D180
H 16 RCH 14 A 15 D180
C 16 RCs 17 A 14 D180
H 18 RCH 16 A 17 D180
H 18 RCH 16 A 19 D180

RCs=1.45
RCd=1.36
RCH=1.08
A=120.0
D=0.0
D180=180.0
}

set basis STO-3G
set reference rohf
set scf_type pk
set docc [ 28,  4 ]
set socc [  0,  1 ]
set e_convergence  1e-13
set d_convergence  1e-13
set ints_tolerance 0.0
# Include 20% old density
set damping_percentage 20
# and stop damping once density has converged to 1e-3
set damping_convergence 1e-3

set dmrg_irrep            1
set dmrg_multiplicity     2
set restricted_docc       [  9,  0 ]
set active                [ 38,  9 ]

set dmrg_sweep_states          [  250,  250 ]
set dmrg_sweep_energy_conv     [ 1e-8, 1e-8 ]
set dmrg_sweep_max_sweeps      [   10,    10 ]
set dmrg_sweep_noise_prefac    [ 0.05, 0.00 ]
set dmrg_sweep_dvdson_rtol     [ 1e-5, 1e-8 ]
set dmrg_print_corr            false
set dmrg_mps_write             false

set dmrg_scf_active_space      loc
set dmrg_local_init            true

set dmrg_molden_write          true  # DMRG-CI pseudocanonical orbitals
set dmrg_opdm_ao_print         true  # DMRG-CI density in the AO basis

energy('dmrg-ci')
```

```
   @ROHF iter  32:  -342.84910912994206   -1.13687e-13   7.97882e-15 DIIS
   @ROHF iter  33:  -342.84910912994206    0.00000e+00   5.47136e-15 DIIS
```

```
Psi4 symmetry group was found to be <cs>.
wfn_irrep   = 1
wfn_multp   = 2
numOrbitals = [ 47 , 9 ]
R(O)HF DOCC = [ 28 , 4 ]
R(O)HF SOCC = [ 0 , 1 ]
frozen_docc = [ 9 , 0 ]
active      = [ 38 , 9 ]
virtual     = [ 0 , 0 ]
nElectrons  = 65
nEl. active = 47
###########################################################
###                                                     ###
###                       DMRG-SCF                      ###
###                                                     ###
###            CheMPS2 by Sebastian Wouters             ###
###        https://github.com/SebWouters/CheMPS2        ###
###   Comput. Phys. Commun. 185 (6), 1501-1514 (2014)   ###
###                                                     ###
###########################################################

Number of variables in the x-matrix = 342
CheMPS2 output is temporarily written to the file susi2.out.chemps2 and will be copied here.
	Presorting SO-basis two-electron integrals.
	Sorting File: SO Ints (nn|nn) nbuckets = 1
	Transforming the one-electron integrals and constructing Fock matrices
	Starting first half-transformation.
	Sorting half-transformed integrals.
	First half integral transformation complete.
	Starting second half-transformation.
	Two-electron integral transformation complete.
CheMPS2 output is temporarily written to the file susi2.out.chemps2 and will be copied here.
   EdmistonRuedenberg::Optimize : Cost function at start = 11.6978759080747
                                  Cost function at stop  = 39.88912832949
                                  Gradient norm = 1.14176119927824e-09 after 14 iterations.
   EdmistonRuedenberg::FiedlerExchange : Cost function at start = 855.317140538854
   EdmistonRuedenberg::FiedlerExchange : Cost function at end   = 13.7691914991716
	Starting first half-transformation.
	Sorting half-transformed integrals.
	First half integral transformation complete.
	Starting second half-transformation.
	Two-electron integral transformation complete.
Rotated the active space to localized orbitals, sorted according to the exchange matrix.
CheMPS2 output is temporarily written to the file 
```

**Comment by susilehtola** [comment]
My version is a bit out-of-date because of issues #460 and #452, so I'm eagerly waiting for #442 to be accepted...

**Comment by susilehtola** [comment]
@kannon92 the syntax can't be wrong since smaller molecules run fine with the same input.

**Comment by kannon92** [comment]
@susilehtola I wasn't talking about your syntax.  I was mostly talking about the commands I wrote.

**Comment by loriab** [comment]
Ah yes, #442. Unfortunately, it's more a matter of finishing it than just accepting it. It's in a fairly stable state ... except for CheMPS2 and PCMSolver, so not so good for you. You could try the conda psi4 1.0 that includes CheMPS2. It's got good math libs behind it, though `-xHost` is off.

**Comment by loriab** [comment]
btw, here's the output file, if it's any use on its own.
[susi2_output.txt](https://github.com/psi4/psi4/files/454443/susi2_output.txt)

**Comment by susilehtola** [comment]
Thanks, although this was a reduced input file - I'm running with much more virtual states in the DMRG.

**Comment by loriab** [comment]
If you'd like to be adventurous, the current development head at https://github.com/jturney/psi4/commits/CMakeRewrite-KillTheBoost should meet your requirements of clean build, new dmrg syntax, and current CheMPS2 (1.8+). It's in a state where all CheMPS2 build issues are in final form, and the non-CheMPS2 code is steady again (only one of 300+ tests broken and that one, finite diff freq of mcscf, won't interfere with you). 

You'll need a fairly modern compiler (https://github.com/jturney/psi4/blob/CMakeRewrite-KillTheBoost/cmake/CheckCompilerVersion.cmake) and gcc>=4.9 (unless using Clang). But otherwise, should be clean with something like:

```
cmake -H. -Bobjdir \
 -DCMAKE_C_COMPILER=icc \
 -DCMAKE_CXX_COMPILER=icpc \
 -DMAX_AM_ERI=5 \
 -DENABLE_CheMPS2=ON \
 -DPYTHON_EXECUTABLE=/theoryfs2/ds/cdsgroup/miniconda/envs/py2basics/bin/python2.7 \
 -DPYTHON_LIBRARY=/theoryfs2/ds/cdsgroup/miniconda/envs/py2basics/lib/libpython2.7.so \
 -DPYTHON_INCLUDE_DIR=/theoryfs2/ds/cdsgroup/miniconda/envs/py2basics/include/python2.7 
```

**Comment by loriab** [comment]
Big merge is in, and CheMPS2 1.8+ is working within it. Let us know if it gives you any problems.

**Comment by amjames** [comment]
It looks like this problem has been resolved, can we close this issue  ?

**Comment by susilehtola** [comment]
Yes, this indeed has been solved!
