### ISSUE TITLE
Unexpected error when using basis_guess with basis set

### ISSUE THREAD

**Issue by tovrstra** [psi4/psi4#484]
The attached input uses basis_guess to specify a basis set for the initial guess: [sapt.zip](https://github.com/psi4/psi4/files/557209/sapt.zip)

This worked with a previous PSI4 release. I guess that was 4.0b6 back then. With a recent development version of PSI4 (commit 7e4ecf968ec7920ab404cb357de827cf3785a254, Wed Oct 19 16:52:24 2016 -0400), I get the following error:

```
toon@molmod49 ~/sapt> psi4 sapt.in 

QcdbException BasisSetNotFound: BasisSet::construct: Unable to find a basis set for atom 1 for role JKFIT among:
  Shell Entries: [u'N']
  Basis Sets: [(u'1', u'1', None)]
  File Path: /home/toon/sapt, /home/toon/sapt, /home/toon/.local/share/psi4/basis
  Input Blocks: 



Traceback (most recent call last):
  File "/home/toon/.local/bin/psi4", line 161, in <module>
    exec(content)
  File "<string>", line 53, in <module>
  File "/home/toon/.local/bin/../lib/psi4/driver/driver.py", line 447, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/toon/.local/bin/../lib/psi4/driver/procedures/proc.py", line 3133, in run_sapt
    dimer_wfn = scf_helper('RHF', molecule=sapt_dimer, **kwargs)
  File "/home/toon/.local/bin/../lib/psi4/driver/procedures/proc.py", line 1199, in scf_helper
    ref_wfn = scf_wavefunction_factory(core.get_option('SCF', 'REFERENCE'), base_wfn)
  File "/home/toon/.local/bin/../lib/psi4/driver/procedures/proc.py", line 1028, in scf_wavefunction_factory
    puream=wfn.basisset().has_puream())
  File "/home/toon/.local/lib/psi4/driver/p4util/python_helpers.py", line 60, in pybuild_basis
    key, target, fitrole, other, return_atomlist=return_atomlist)
  File "/home/toon/.local/bin/../lib/psi4/driver/qcdb/libmintsbasisset.py", line 631, in pyconstruct
    return_atomlist=return_atomlist)
  File "/home/toon/.local/bin/../lib/psi4/driver/qcdb/libmintsbasisset.py", line 805, in construct
    (at + 1, role, text2))
psi4.driver.qcdb.exceptions.BasisSetNotFound: BasisSet::construct: Unable to find a basis set for atom 1 for role JKFIT among:
  Shell Entries: [u'N']
  Basis Sets: [(u'1', u'1', None)]
  File Path: /home/toon/sapt, /home/toon/sapt, /home/toon/.local/share/psi4/basis
  Input Blocks: 
```

Unlike the test cases that come with PSI4, this input explicitly refers to a basis set for the initial guess: cc-pvdz. (That may seem a heavy-handed choice but we found it to be more robust when processing databases of molecular dimers.)

**Comment by tovrstra** [comment]
P.S. The basis file it complains about does exist. In my case, I do have the following file:

    /home/toon/.local/share/psi4/basis/cc-pvdz-jkfit.gbs

**Comment by dgasmith** [comment]
Looks like a logic breakdown around `/psi4/driver/procedures/proc.py:1140`. For now if you simply comment out `/psi4/driver/procedures/proc.py:1164-1165` everything should work as expected. Ill fix this up in a patch and switch one of our `basis_guess` test cases to an explicit basis so we can catch this in the future.

**Comment by tovrstra** [comment]
Thanks for the quick reply!
