### ISSUE TITLE
Error with X2C and Decontracted Basis Set Input

### ISSUE THREAD

**Issue by jevandezande** [psi4/psi4#662]
When I try to run the input file from the X2C section, it fails.
```
molecule {
    H
    F 1 0.92
}

set {
    scf_type pk
    basis cc-pvdz-decon
    relativistic x2c
}

energy('hf')
```

It runs fine if I either remove the `-decon`, remove the `relativistic x2c` option, or add the `basis_relativistic` option.

The error I get is:
```
Traceback (most recent call last):
  File "/usr/local/bin/psi4", line 247, in <module>
    exec(content)
  File "<string>", line 28, in <module>
  File "/usr/local/lib/psi4/driver/driver.py", line 454, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/usr/local/lib/psi4/driver/procrouting/proc.py", line 2797, in run_dft
    scf_wfn = run_scf(name, **kwargs)
  File "/usr/local/lib/psi4/driver/procrouting/proc.py", line 1941, in run_scf
    scf_wfn = scf_helper(name, **kwargs)
  File "/usr/local/lib/psi4/driver/procrouting/proc.py", line 1250, in scf_helper
    scf_wfn = scf_wavefunction_factory(core.get_option('SCF', 'REFERENCE'), base_wfn)
  File "/usr/local/lib/psi4/driver/procrouting/proc.py", line 1035, in scf_wavefunction_factory
    puream=wfn.basisset().has_puream())
  File "/usr/local/lib/psi4/driver/p4util/python_helpers.py", line 64, in pybuild_basis
    key, target, fitrole, other, return_atomlist=return_atomlist)
  File "/usr/local/lib/psi4/driver/qcdb/libmintsbasisset.py", line 641, in pyconstruct
    return_atomlist=return_atomlist)
  File "/usr/local/lib/psi4/driver/qcdb/libmintsbasisset.py", line 770, in construct
    filename = cls.make_filename(basgbs)
  File "/usr/local/lib/psi4/driver/qcdb/libmintsbasisset.py", line 1309, in make_filename
    basisname = basisname.lower()

AttributeError: 'NoneType' object has no attribute 'lower'
```

I'm guessing that this is related to issue #617.

**Comment by loriab** [comment]
Haven't checked, but that's a redundant input, isn't it? `basis cc-pvdz` + `relativistic x2c` triggers the primary basis to decontract. That said, the answer in the docs for the x2c example is known wrong. Were you going to address that, @WDerricotte?

Let me know if I'm mistaken about any of this, as I don't run relativistic regularly. And if there's something that _should_ work, please make a test case of it so it will continue to work.

**Comment by WDerricotte** [comment]
X2C doesn't decontract the basis by default so it is not automatically a redundant input. I'm getting the same error when trying to run X2C with a decontracted basis with the newest PSI4, I haven't run any X2C calculations in a while and was unaware of this issue. I'll look into this, making sure @fevangelista is also aware of this also.

**Comment by loriab** [comment]
Thanks, @WDerricotte, I'm confused, as I expected this input (w/o "-decon") to work like https://github.com/psi4/psi4/blob/master/tests/x2c2/input.dat, which does trigger decontraction via `relativistic x2c`.

**Comment by jturney** [comment]
I know @bzloink recently ran some X2C computations. @bzloink do you have anything to add?

**Comment by bzloink** [comment]
I ran into a similar issue, and my "fix" was what worked for @jevandezande - adding the basis_relativistic option. I was unable to automatically trigger the basis set decontraction.

**Comment by loriab** [comment]
How is `x2c2` working, pray? You all don't have `PSIDATADIR`s pointing to mysterious other drivers, do you?

**Comment by WDerricotte** [comment]
x2c2 works because the dk basis sets are defined in share/basis/  with their own .gbs file, and thus don't run into this issue. This issue seems to be arising only when the "-decon" flag is used to decontract the basis without specifying the relativistic basis.

**Comment by loriab** [comment]
Ah, ok. If any of you affected could post an input _with_ the compare_values statements that it should match (an analog of x2c2 would be fine), I will turn it from a broken one to a working one.

**Comment by WDerricotte** [comment]
I'll post one in a few minutes, I'l also specify that relativistic_basis must be included in the input.

**Comment by WDerricotte** [comment]
This input runs fine for HF, for me. Let me know if you need anything else.

```python
ref_nuc_energy =   5.176733562293478
ref_rel_energy = -100.10780818747669


molecule hf{
H
F 1 0.92
}

set {
    scf_type pk
    basis cc-pvdz-decon
    basis_relativistic cc-pvdz-decon #Must Specify relativistic basis
                                     #when using decontracted primary basis
    relativistic x2c
}

testrel = energy('hf')

compare_values(ref_nuc_energy, hf.nuclear_repulsion_energy(), 9, "Nuclear repulsion energy") #TEST
compare_values(ref_rel_energy,testrel, 9, "X2C relativistic SCF energy")                #TEST
```

**Comment by fevangelista** [comment]
Ok, I am just catching up with this discussion.

@loriab: basis cc-pvdz + relativistic x2c does (should) not triggers the primary basis to decontract but decontracts the `basis_relativistic` basis, which is used internally by x2c to solve the Dirac equation. This is the recommended procedure for basis sets like cc-pVXZ-DK.

This table should help:

|              `basis`             | `basis_relativistic ` |  Procedure | Good idea? |
| ------------- | ------------------- | ------------------------------------------------- |------------------- |
| cc-pVDZ-DK     |                                  | solve Dirac eq in cc-pVDZ-DK-decon basis/recontract to cc-pVDZ-DK| Yes, default |
| cc-pVDZ-DK     | cc-pVDZ-DK-decon  | Same as above | Option above is preferred  |
| cc-pVDZ-DK     | cc-pVDZ-DK           | solve Dirac eq in cc-pVDZ-DK basis/return Hx2c in cc-pVDZ-DK basis| No, need to solve Dirac eq in decon basis to get accurate results |
| cc-pVDZ-DK-decon     |            | solve Dirac eq in cc-pVDZ-DK-decon basis/return Hx2c in cc-pVDZ-DK-decon basis| Yes, if you need high accuracy. Very expensive |
| cc-pVDZ-DK-decon     |   cc-pVDZ-DK-decon         | Same as above| Option above is preferred |
| cc-pVDZ-DK-decon     | cc-pVDZ-DK   | solve Dirac eq in cc-pVDZ-DK basis/return Hx2c in cc-pVDZ-DK-decon basis| No, need to solve Dirac eq in decon basis to get accurate results |

My student Sam recently posted about this issue. This input should run:

```
molecule {
H
F 1 0.92
}

set {
    basis cc-pvdz-dk-decon
    relativistic x2c
}

energy('hf')
```
but fails on the python side. This is equivalent to this other input (which should also run):
```
molecule {
H
F 1 0.92
}

set {
    basis cc-pvdz-dk-decon
    basis_relativistic cc-pvdz-dk-decon
    relativistic x2c
}

energy('hf')
```


@loriab "That said, the answer in the docs for the x2c example is known wrong". I have the fix, the example should read:
```
molecule {
H
F 1 0.92
}

set {
    scf_type pk
    basis cc-pvdz
    relativistic x2c
}

energy('hf')
```

@jevandezande: If you are **not** interested in explicitly decontracting the basis the recommended way to run this input is:

```
molecule {
    H
    F 1 0.92
}

set {
    scf_type pk
    basis cc-pvdz-dk
    relativistic x2c
}

energy('hf')
```

**Comment by fevangelista** [comment]
In reply to @WDerricotte's last post. This runs on my laptop too.

```
    basis cc-pvdz-decon
    basis_relativistic cc-pvdz-decon
```
but 
```
    basis cc-pvdz-dk-decon
    basis_relativistic cc-pvdz-dk-decon
```
does not. The second version (not working) should be the preferred one because the non-DK basis are not meant to be used for relativistic computations.

**Comment by loriab** [comment]
A Table! Wonderful, will examine. On the "My student Sam ...", was that psi4/psi4#617? That should have been fixed by the commit that closed it. If not, please let me know.

**Comment by fevangelista** [comment]
Yes, it was that psi4/psi4#617. That example runs, but it also fails when `roos-ano-dz` -> `roos-ano-dz-decon`.

**Comment by loriab** [comment]
I see, thanks. This topic clearly needs a case list for me to work from. As I suspect you've kindly provided me one via The Table, I'll try to get them working simultaneously.

**Comment by fevangelista** [comment]
I am open to finding a way to force the user into using only the appropriate combinations of `basis`/`basis_relativistic` if that sounds like a more sensible choice. In principle it would be enough to eliminate `basis_relativistic` and always decontract `basis`. However, this could be problematic when the decontracted basis has linear dependencies (I am working on this issue but I am currently slightly stuck/too busy).
The reason we have so many options was just for testing reasons, and to allow cases where `basis_relativistic` is a basis different from `basis` (e.g. to remove linear dependencies directly in the deconstructed basis).

The HF example above should do. Once you address the Python issue I can run some checks. Besdie external tests, there is at least one way to tell if things are internally consistent in psi4.

**Comment by jevandezande** [comment]
There is at least one group that I know of that is working on developing basis sets specifically contracted for X2C computations. Thus, it may not be a good idea to automatically decontract the basis set.

**Comment by dgasmith** [comment]
Close #1471 IMO.

**Comment by PeterKraus** [comment]
I just ran into this, but with `relativistic dkh` (which I wanted to use with the `TZP-DKH` basis set from EMSL): the driver doesn't work with "custom" basis sets full stop, they have to be in the system folder (`PSIPATH` is not enough).
