### ISSUE TITLE
CI runtime error in conda package

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#764]
Running the following input

```
molecule mol {
0 1
H 0.0 0.0 0.000000
H 0.0 0.0 0.700000
H 0.0 0.0 1.400000
H 0.0 0.0 2.100000
H 0.0 0.0 2.800000
H 0.0 0.0 3.500000
}

memory 3500 mb

set basis aug-cc-pVDZ
set reference rohf
set guess core
set scf_type df

scf_e, scf_wfn = energy('scf', return_wfn = True)

set restricted_docc [ 0, 0, 0, 0, 0, 0, 0, 0 ]
set restricted_uocc [ 0, 0, 6, 6, 0, 0, 6, 6 ]
set qc_module detci
set nat_orbs true

ci_e, ci_wfn = energy('cisd', ref_wfn = scf_wfn, return_wfn = True)
```

crashes with
```
RuntimeError: 
Fatal Error: Matrix::doublet: Dimension mismatch
Error occurred in file: /builddir/build/BUILD/psi4-add49b95b6be2441c522f71bddb47f1371e16958/psi4/src/psi4/libmints/matrix.cc on line: 1517
```

both in the Fedora package of Psi4 1.1 as well as the conda package.

The script runs without errors in the up-to-date trunk.

Could this issue be fixed in the conda package? Alternatively, is there a conda channel for the development version?

**Comment by loriab** [comment]
`-c psi4/label/dev`

http://psicode.org/psi4manual/master/conda.html#faq-updatepsi4

**Comment by susilehtola** [comment]
It's not working:
```
Traceback (most recent call last):
  File "/global/scratch/slehtola/psi4conda/bin/psi4", line 158, in <module>
    import psi4
  File "/global/scratch/slehtola/psi4conda/lib//python2.7/site-packages/psi4/__init__.py", line 60, in <module>
    raise ImportError("{0}".format(err))
ImportError: /global/scratch/slehtola/psi4conda/lib//python2.7/site-packages/psi4/core.so: undefined symbol: __svml_sin4
```

**Comment by loriab** [comment]
`conda list` and `ldd lib/python.../site-packages/psi4/core.so`, please

**Comment by susilehtola** [comment]
```
$ conda list
# packages in environment at /global/scratch/slehtola/psi4conda:
#
alabaster                 0.7.10                   py27_0  
asn1crypto                0.22.0                   py27_0  
babel                     2.4.0                    py27_0  
bzip2                     1.0.6                         3  
cffi                      1.10.0                   py27_0  
chemps2                   1.8.3                         5  
cloog                     0.18.0                        0  
cmake                     3.6.3                         0  
conda                     4.3.23                   py27_0  
conda-env                 2.6.0                         0  
cryptography              1.8.1                    py27_0  
curl                      7.54.1                        0  
dftd3                     3.2.0                         7  
dkh                       1.2                           0  
docutils                  0.12                     py27_2  
enum34                    1.1.6                    py27_0  
erd                       3.0.6                         0  
expat                     2.1.0                         0  
gcc-5                     5.2.0                         1  
gcc-5-mp                  5.2.0                         0  
gcp                       2.0.1                         0  
gdma                      2.2.6                         2  
gmp                       6.1.0                         0  
hdf5                      1.8.17                        2  
idna                      2.5                      py27_0  
imagesize                 0.7.1                    py27_0  
ipaddress                 1.0.18                   py27_0  
isl                       0.12.2                        0  
jinja2                    2.9.6                    py27_0  
krb5                      1.13.2                        0  
libefp                    1.4.2                         0  
libffi                    3.2.1                         1  
libgfortran               3.0.0                         1  
libint                    1.2.1                         0  
libssh2                   1.8.0                         0  
libxc                     3.0.0                         3  
markupsafe                0.23                     py27_2  
mkl                       2017.0.3                      0  
mpc                       1.0.1                         0  
mpfr                      3.1.2                         0  
ncurses                   5.9                          10  
numpy                     1.13.1                   py27_0  
openblas                  0.2.19                        0  
openssl                   1.0.2l                        0  
packaging                 16.8                     py27_0  
pcmsolver                 1.1.10                   py27_0  
pip                       9.0.1                    py27_1  
psi4                      1.2a1.dev458+efadaad          py27_1    psi4/label/dev
psi4-deps                 1.0                      py27_1  
psi4-lt-mp                1.1                      py27_0  
py                        1.4.34                   py27_0  
pyasn1                    0.2.3                    py27_0  
pycosat                   0.6.2                    py27_0  
pycparser                 2.17                     py27_0  
pygments                  2.2.0                    py27_0  
pyopenssl                 17.0.0                   py27_0  
pyparsing                 2.1.4                    py27_0  
pytest                    3.1.2                    py27_0  
python                    2.7.13                        0  
pytz                      2017.2                   py27_0  
readline                  6.2                           2  
requests                  2.14.2                   py27_0  
ruamel_yaml               0.11.14                  py27_1  
setuptools                27.2.0                   py27_0  
simint                    0.7                           0  
six                       1.10.0                   py27_0  
snowballstemmer           1.2.1                    py27_0  
sphinx                    1.5.6                    py27_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
v2rdm_casscf              0.3                      py27_1  
wheel                     0.29.0                   py27_0  
xz                        5.2.2                         1  
yaml                      0.1.6                         0  
zlib                      1.2.8                         3  
$ ldd /global/scratch/slehtola/psi4conda/lib/python2.7/site-packages/psi4/core.so 
	linux-vdso.so.1 =>  (0x00007ffc11de9000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00002ad7d9684000)
	libc.so.6 => /lib64/libc.so.6 (0x00002ad7d98a2000)
	libpcm.so.1 => /global/scratch/slehtola/psi4conda/lib/python2.7/site-packages/psi4/../../../libpcm.so.1 (0x00002ad7d9c36000)
	libxc.so => /global/scratch/slehtola/psi4conda/lib/python2.7/site-packages/psi4/../../../libxc.so (0x00002ad7e0554000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00002ad7e08c8000)
	libgdma.so => /global/scratch/slehtola/psi4conda/lib/python2.7/site-packages/psi4/../../../libgdma.so (0x00002ad7e0acc000)
	libderiv.so => /global/scratch/slehtola/psi4conda/lib/python2.7/site-packages/psi4/../../../libderiv.so (0x00002ad7e0eb8000)
	libint.so => /global/scratch/slehtola/psi4conda/lib/python2.7/site-packages/psi4/../../../libint.so (0x00002ad7e3ac5000)
	libdkh.so => /global/scratch/slehtola/psi4conda/lib/python2.7/site-packages/psi4/../../../libdkh.so (0x00002ad7e473d000)
	liberd.so => /global/scratch/slehtola/psi4conda/lib/python2.7/site-packages/psi4/../../../liberd.so (0x00002ad7e4a58000)
	libsimint.so => /global/scratch/slehtola/psi4conda/lib/python2.7/site-packages/psi4/../../../libsimint.so (0x00002ad7e4f84000)
	libefp.so => /global/scratch/slehtola/psi4conda/lib/python2.7/site-packages/psi4/../../../libefp.so (0x00002ad7e7580000)
	libmkl_rt.so => /global/scratch/slehtola/psi4conda/lib/python2.7/site-packages/psi4/../../../libmkl_rt.so (0x00002ad7e80db000)
	libiomp5.so => /global/scratch/slehtola/psi4conda/lib/python2.7/site-packages/psi4/../../../libiomp5.so (0x00002ad7e86ec000)
	libchemps2.so.2 => /global/scratch/slehtola/psi4conda/lib/python2.7/site-packages/psi4/../../../libchemps2.so.2 (0x00002ad7e8a96000)
	/lib64/ld-linux-x86-64.so.2 (0x00002ad7d644f000)
	libz.so.1 => /global/scratch/slehtola/psi4conda/lib/python2.7/site-packages/psi4/../../.././libz.so.1 (0x00002ad7e9bf0000)
	libm.so.6 => /lib64/libm.so.6 (0x00002ad7e9e06000)
	libgcc_s.so.1 => /global/scratch/slehtola/psi4conda/lib/python2.7/site-packages/psi4/../../.././libgcc_s.so.1 (0x00002ad7ea08b000)
	librt.so.1 => /lib64/librt.so.1 (0x00002ad7ea2a1000)
	libhdf5.so.10 => /global/scratch/slehtola/psi4conda/lib/python2.7/site-packages/psi4/../../.././libhdf5.so.10 (0x00002ad7ea4a9000)
	libhdf5_hl.so.10 => /global/scratch/slehtola/psi4conda/lib/python2.7/site-packages/psi4/../../.././libhdf5_hl.so.10 (0x00002ad7ea98d000)
```

**Comment by loriab** [comment]
Go ahead and pull down updated versions of the packages with blas/lapack dependencies `conda update chemps2 libefp v2rdm_casscf -c psi4/label/dev -c psi4`. We switched over math handling recently from statically linked mkl to single dynamic library mkl. If you want, you can grab the whole updated list `conda update pcmsolver libxc gdma libint dkh erd simint libefp chemps2 v2rdm_casscf -c psi4/label/dev -c psi4` as they now come with more instruction sets embedded.

**Comment by susilehtola** [comment]
Thanks, that solved it!
