### ISSUE TITLE
UnboundLocalError in libmintsgshell

### ISSUE THREAD

**Issue by rmcgibbo** [psi4/psi4#846]
[This block of code](https://github.com/psi4/psi4/blob/master/psi4/driver/qcdb/libmintsgshell.py#L222-L228) in libmintsgshell.py throws a UnboundLocalError when trying to recover from the ZeroDivisionError

```
        try:
            norm = math.sqrt(1.0 / (tmp * e_sum))
        except ZeroDivisionError:
            self.PYcoef[i] = [1.0 for i in range(self.nprimitive())]
        # Set the normalization
        for i in range(self.nprimitive()):
            self.PYcoef[i] *= norm
```

Traceback
```
Traceback (most recent call last):
  File "/prefix/bin/psi4", line 260, in <module>
    exec(content)
  File "<string>", line 27, in <module>
  File "/prefix/lib//psi4/driver/driver.py", line 460, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/prefix/lib//psi4/driver/procrouting/proc.py", line 1990, in run_scf
    scf_wfn = scf_helper(name, post_scf=False, **kwargs)
  File "/prefix/lib//psi4/driver/procrouting/proc.py", line 1279, in scf_helper
    base_wfn = core.Wavefunction.build(scf_molecule, core.get_global_option('BASIS'))
  File "/prefix/lib//psi4/driver/p4util/python_helpers.py", line 101, in pybuild_wavefunction
    basis = core.BasisSet.build(mol, "ORBITAL", basis)
  File "/prefix/lib//psi4/driver/p4util/python_helpers.py", line 68, in pybuild_basis
    key, resolved_target, fitrole, other, return_atomlist=return_atomlist)
  File "/prefix/lib//psi4/driver/qcdb/libmintsbasisset.py", line 661, in pyconstruct
    return_atomlist=return_atomlist)
  File "/prefix/lib//psi4/driver/qcdb/libmintsbasisset.py", line 876, in construct
    ecpbasisset = BasisSet(key, mol, ecp_atom_basis_shell)
  File "/prefix/lib//psi4/driver/qcdb/libmintsbasisset.py", line 148, in __init__
    self.constructor_role_mol_shellmap(*args)
  File "/prefix/lib//psi4/driver/qcdb/libmintsbasisset.py", line 349, in constructor_role_mol_shellmap
    n, xyz_ptr, bf_count, pt='Unnormalized', rpowers=rpowers[tst:tsp])
  File "/prefix/lib//psi4/driver/qcdb/libmintsgshell.py", line 193, in __init__
    self.normalize_shell()
  File "/prefix/lib//psi4/driver/qcdb/libmintsgshell.py", line 238, in normalize_shell
    self.contraction_normalization()
  File "/prefix/lib//psi4/driver/qcdb/libmintsgshell.py", line 228, in contraction_normalization
    self.PYcoef[i] *= norm

UnboundLocalError: local variable 'norm' referenced before assignment
```

**Comment by JonathonMisiewicz** [comment]
@rmcgibbo We should be able to close this now.

**Comment by rmcgibbo** [comment]
Great, thanks!
